// Begriffe für Wortraten: [Lösung (mit „|“ getrennte Schreibweisen), 6 Hinweise vom ungenauen bis zum fast eindeutigen].
export const WORDS = [
    // Essen und Trinken
    ['Pizza', 'Essen', 'Italien', 'Teig', 'Käse', 'Ofen', 'Margherita'],
    ['Schokolade', 'Süß', 'Kakao', 'Tafel', 'Braun', 'Ostern', 'Milka'],
    ['Kaffee', 'Getränk', 'Bohne', 'Morgens', 'Koffein', 'Tasse', 'Espresso'],
    ['Spaghetti', 'Italien', 'Lang', 'Nudel', 'Tomatensoße', 'Gabel', 'Bolognese'],
    ['Pommes|Pommes frites|Fritten', 'Kartoffel', 'Fett', 'Imbiss', 'Ketchup', 'Mayo', 'Frittiert'],
    ['Erdbeere', 'Frucht', 'Rot', 'Sommer', 'Samen außen', 'Sahne', 'Marmelade'],
    ['Honig', 'Süß', 'Biene', 'Glas', 'Bär', 'Brotaufstrich', 'Imker'],
    ['Eis|Speiseeis|Eiscreme', 'Sommer', 'Kalt', 'Kugel', 'Waffel', 'Vanille', 'Eisdiele'],
    ['Brezel|Breze', 'Bäckerei', 'Knoten', 'Salz', 'Bayern', 'Laugen', 'Oktoberfest'],
    ['Popcorn', 'Mais', 'Kino', 'Knallen', 'Salzig', 'Süß', 'Tüte'],
    ['Sushi', 'Japan', 'Reis', 'Fisch', 'Stäbchen', 'Wasabi', 'Algen'],
    ['Döner|Dönerkebab|Döner Kebab', 'Spieß', 'Fleisch', 'Fladenbrot', 'Türkei', 'Soße', 'Imbiss'],
    ['Banane', 'Gelb', 'Frucht', 'Krumm', 'Affe', 'Schale', 'Kalium'],
    ['Kartoffel', 'Knolle', 'Erde', 'Beilage', 'Salz', 'Püree', 'Kloß'],
    // Tiere
    ['Elefant', 'Tier', 'Grau', 'Afrika', 'Rüssel', 'Stoßzähne', 'Dumbo'],
    ['Pinguin', 'Vogel', 'Kalt', 'Schwarz-weiß', 'Watscheln', 'Antarktis', 'Eis'],
    ['Giraffe', 'Tier', 'Afrika', 'Gefleckt', 'Hals', 'Blätter', 'Höchstes Landtier'],
    ['Delfin|Delphin', 'Meer', 'Säugetier', 'Intelligent', 'Flipper', 'Springen', 'Klicklaute'],
    ['Eichhörnchen', 'Wald', 'Nüsse', 'Rot', 'Buschiger Schwanz', 'Baum', 'Vorrat'],
    ['Schmetterling|Falter', 'Insekt', 'Flügel', 'Bunt', 'Raupe', 'Puppe', 'Tagpfauenauge'],
    ['Krokodil', 'Reptil', 'Wasser', 'Zähne', 'Grün', 'Nil', 'Tränen'],
    ['Papagei', 'Vogel', 'Bunt', 'Sprechen', 'Tropen', 'Schnabel', 'Pirat'],
    ['Hai|Haifisch', 'Meer', 'Flosse', 'Zähne', 'Gefährlich', 'Weißer', 'Jaws'],
    ['Känguru', 'Australien', 'Beutel', 'Hüpfen', 'Tier', 'Boxen', 'Joey'],
    ['Biene', 'Insekt', 'Gelb', 'Summen', 'Honig', 'Stachel', 'Königin'],
    ['Spinne', 'Tier', 'Netz', 'Acht Beine', 'Fliegen fangen', 'Giftig', 'Phobie'],
    ['Eule|Uhu', 'Vogel', 'Nacht', 'Wald', 'Große Augen', 'Hedwig', 'Huhu'],
    ['Hund', 'Haustier', 'Bellen', 'Treue', 'Knochen', 'Gassi', 'Leine'],
    ['Pferd', 'Reiten', 'Hufe', 'Mähne', 'Stall', 'Wiehern', 'Galopp'],
    ['Wal|Blauwal', 'Meer', 'Säugetier', 'Riesig', 'Fontäne', 'Moby Dick', 'Blau'],
    ['Bär', 'Wald', 'Honig', 'Winterschlaf', 'Pelz', 'Teddy', 'Grizzly'],
    ['Löwe', 'Afrika', 'Savanne', 'Mähne', 'Rudel', 'Brüllen', 'König der Tiere'],
    // Orte
    ['Strand', 'Urlaub', 'Sand', 'Meer', 'Muscheln', 'Sonnenschirm', 'Liegestuhl'],
    ['Flughafen', 'Reise', 'Gate', 'Koffer', 'Check-in', 'Start', 'Landebahn'],
    ['Bibliothek|Bücherei', 'Ruhe', 'Bücher', 'Ausleihen', 'Regale', 'Lesen', 'Leseausweis'],
    ['Zirkus', 'Zelt', 'Clown', 'Manege', 'Artisten', 'Zauberer', 'Dompteur'],
    ['Schule', 'Kinder', 'Lernen', 'Hausaufgaben', 'Pause', 'Zeugnis', 'Klassenzimmer'],
    ['Krankenhaus|Klinik', 'Ärzte', 'Betten', 'Notaufnahme', 'Krankenschwester', 'OP', 'Besuchszeit'],
    ['Supermarkt', 'Einkaufen', 'Wagen', 'Kasse', 'Regale', 'Pfand', 'Angebote'],
    ['Kino', 'Dunkel', 'Leinwand', 'Popcorn', 'Film', 'Sitzreihe', 'Tickets'],
    ['Zoo|Tierpark', 'Tiere', 'Käfige', 'Eintritt', 'Affen', 'Streichelgehege', 'Gehege'],
    ['Bahnhof', 'Züge', 'Gleis', 'Fahrplan', 'Reisende', 'Verspätung', 'Bahnsteig'],
    ['Schloss', 'Gebäude', 'Königin', 'Türme', 'Märchen', 'Neuschwanstein', 'Prinzessin'],
    ['Vulkan', 'Berg', 'Heiß', 'Asche', 'Krater', 'Ausbruch', 'Lava'],
    // Gegenstände
    ['Regenschirm|Schirm', 'Wetter', 'Handlich', 'Tropfen', 'Griff', 'Aufspannen', 'Mary Poppins'],
    ['Brille', 'Gesicht', 'Gläser', 'Sehen', 'Nase', 'Bügel', 'Optiker'],
    ['Fahrrad|Rad', 'Räder', 'Pedale', 'Lenker', 'Klingel', 'Kette', 'Helm'],
    ['Zahnbürste', 'Bad', 'Borsten', 'Zahnpasta', 'Putzen', 'Elektrisch', 'Zähne'],
    ['Kerze', 'Licht', 'Wachs', 'Docht', 'Flamme', 'Geburtstagstorte', 'Auspusten'],
    ['Gitarre', 'Musik', 'Saiten', 'Holz', 'Akkord', 'Lagerfeuer', 'Zupfen'],
    ['Staubsauger', 'Haushalt', 'Putzen', 'Teppich', 'Beutel', 'Düse', 'Dyson'],
    ['Handy|Smartphone', 'Tasche', 'Display', 'Anrufen', 'Nachrichten', 'Apps', 'Akku'],
    ['Kühlschrank', 'Küche', 'Kalt', 'Lebensmittel', 'Magnete', 'Licht', 'Tür'],
    ['Schlüssel', 'Metall', 'Bund', 'Schloss', 'Tür', 'Aufsperren', 'Anhänger'],
    ['Rucksack', 'Reise', 'Schultern', 'Wandern', 'Träger', 'Schule', 'Reißverschluss'],
    ['Uhr', 'Zeit', 'Zifferblatt', 'Zeiger', 'Armband', 'Ticken', 'Wecker'],
    ['Spiegel', 'Glas', 'Bad', 'Reflexion', 'Schneewittchen', 'Rahmen', 'Bild'],
    ['Regenbogen', 'Himmel', 'Farben', 'Sieben', 'Regen', 'Sonne', 'Gold am Ende'],
    ['Magnet', 'Eisen', 'Anziehen', 'Pol', 'Kühlschrank', 'Kompass', 'Nord'],
    ['Luftballon|Ballon', 'Party', 'Gummi', 'Helium', 'Aufblasen', 'Platzen', 'Geburtstag'],
    ['Schneemann', 'Winter', 'Kugeln', 'Karottennase', 'Hut', 'Besen', 'Olaf'],
    // Berufe
    ['Feuerwehrmann|Feuerwehr', 'Notfall', 'Uniform', 'Helm', 'Löschen', 'Leiter', 'Schlauch'],
    ['Bäcker', 'Früh', 'Mehl', 'Backstube', 'Brötchen', 'Teig', 'Ofen'],
    ['Pilot', 'Beruf', 'Uniform', 'Cockpit', 'Fliegen', 'Kapitän', 'Flugzeug'],
    ['Friseur', 'Beruf', 'Schere', 'Kamm', 'Haare', 'Föhn', 'Salon'],
    ['Astronaut', 'Beruf', 'Raumanzug', 'Schwerelos', 'Rakete', 'ISS', 'Mond'],
    ['Detektiv', 'Spuren', 'Lupe', 'Rätsel', 'Sherlock', 'Fall', 'Verbrecher'],
    ['Zauberer', 'Zauberstab', 'Hut', 'Kaninchen', 'Tricks', 'Abrakadabra', 'Magie'],
    ['Pirat|Seeräuber', 'Meer', 'Schatz', 'Augenklappe', 'Papagei', 'Totenkopf', 'Schiff'],
    // Feste und Tätigkeiten
    ['Weihnachten', 'Winter', 'Geschenke', 'Tannenbaum', 'Plätzchen', 'Heiligabend', 'Weihnachtsmann'],
    ['Geburtstag', 'Feiern', 'Kuchen', 'Kerzen', 'Geschenke', 'Gäste', 'Wunsch'],
    ['Hochzeit', 'Fest', 'Ring', 'Brautkleid', 'Standesamt', 'Ja-Wort', 'Brautstrauß'],
    ['Karneval|Fasching|Fastnacht', 'Verkleiden', 'Konfetti', 'Umzug', 'Köln', 'Kamelle', 'Narren'],
    ['Camping|Zelten', 'Draußen', 'Zelt', 'Schlafsack', 'Lagerfeuer', 'Wohnwagen', 'Natur'],
    ['Schwimmen', 'Sport', 'Wasser', 'Bahnen', 'Kraulen', 'Brille', 'Becken'],
    ['Fußball', 'Sport', 'Rasen', 'Tor', 'Elfmeter', 'Weltmeisterschaft', 'Abseits'],
    ['Skifahren|Ski', 'Winter', 'Berge', 'Piste', 'Lift', 'Stöcke', 'Schnee'],
    ['Angeln', 'Fisch', 'See', 'Geduld', 'Rute', 'Köder', 'Haken'],
    ['Tanzen', 'Musik', 'Bewegung', 'Rhythmus', 'Paar', 'Disco', 'Tango'],
    ['Kochen', 'Küche', 'Herd', 'Rezept', 'Topf', 'Zutaten', 'Löffel'],
    ['Schach', 'Brettspiel', 'Könige', 'Schwarz-weiß', 'Matt', 'Läufer', 'Turm'],
    ['Puzzle', 'Teile', 'Zusammensetzen', 'Rahmen', 'Karton', 'Bild', 'Tausend'],
    ['Lagerfeuer', 'Draußen', 'Flammen', 'Marshmallows', 'Nacht', 'Holz', 'Gitarre'],
    // Himmel, Wahrzeichen, Fabelwesen
    ['Mond', 'Himmel', 'Nacht', 'Krater', 'Werwolf', 'Gezeiten', 'Apollo'],
    ['Sonne', 'Stern', 'Gelb', 'Heiß', 'Tag', 'Sommer', 'Mittelpunkt'],
    ['Computer|PC|Rechner', 'Maus', 'Tastatur', 'Bildschirm', 'Internet', 'Programme', 'Laptop'],
    ['Fernseher|TV|Fernsehen', 'Wohnzimmer', 'Fernbedienung', 'Programm', 'Bildschirm', 'Sendung', 'Streaming'],
    ['Eiffelturm', 'Frankreich', 'Wahrzeichen', 'Eisen', 'Paris', 'Aussichtsplattform', '330 Meter'],
    ['Pyramide|Pyramiden', 'Ägypten', 'Pharao', 'Stein', 'Dreieck', 'Gizeh', 'Wüste'],
    ['Titanic', 'Schiff', 'Eisberg', 'Film', '1912', 'Rose', 'Jack'],
    ['Brandenburger Tor', 'Berlin', 'Quadriga', 'Wahrzeichen', 'Säulen', 'Mauer', 'Pariser Platz'],
    ['Kolosseum|Colosseum', 'Rom', 'Gladiatoren', 'Ruine', 'Arena', 'Antike', 'Italien'],
    ['Roboter', 'Maschine', 'Metall', 'Fabrik', 'Programmiert', 'Künstliche Intelligenz', 'R2-D2'],
    ['Drache', 'Fabelwesen', 'Feuer', 'Flügel', 'Schatz', 'Ritter', 'Smaug'],
    ['Einhorn', 'Fabelwesen', 'Pferd', 'Horn', 'Regenbogen', 'Glitzer', 'Weiß'],
    ['Vampir', 'Nacht', 'Blut', 'Zähne', 'Knoblauch', 'Dracula', 'Fledermaus'],
    ['Gespenst|Geist', 'Spuk', 'Nacht', 'Weißes Laken', 'Burg', 'Halloween', 'Buh'],
    ['Hexe', 'Besen', 'Zauber', 'Hut', 'Kessel', 'Halloween', 'Schwarze Katze'],
];

export const HINTS_PER_WORD = 6;
