// Inhalte für die Minispiele von Sternenjagd: Wissensfragen, Flaggen und Begriffe zum Zeichnen.
// Fragen: [Frage, richtige Antwort, falsch 1, falsch 2, falsch 3]. Die Reihenfolge der Antworten wird beim Spiel gemischt.

export const QUESTIONS = [
    // Geografie
    ['Was ist die Hauptstadt von Australien?', 'Canberra', 'Sydney', 'Melbourne', 'Perth'],
    ['Welcher Fluss ist der längste Europas?', 'Wolga', 'Donau', 'Rhein', 'Elbe'],
    ['Welches Land hat die größte Fläche der Erde?', 'Russland', 'Kanada', 'China', 'USA'],
    ['Was ist die Hauptstadt der Schweiz?', 'Bern', 'Zürich', 'Genf', 'Basel'],
    ['Wie heißt der höchste Berg der Erde?', 'Mount Everest', 'K2', 'Kilimandscharo', 'Mont Blanc'],
    ['Welches Meer liegt zwischen Europa und Afrika?', 'Mittelmeer', 'Rotes Meer', 'Schwarzes Meer', 'Nordsee'],
    ['Was ist die Hauptstadt von Kanada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    ['Wie viele Bundesländer hat Deutschland?', '16', '12', '14', '18'],
    ['Welcher ist der größte Ozean der Erde?', 'Pazifik', 'Atlantik', 'Indischer Ozean', 'Arktischer Ozean'],
    ['Was ist die Hauptstadt von Spanien?', 'Madrid', 'Barcelona', 'Valencia', 'Sevilla'],
    ['Welches Land hat die Form eines Stiefels?', 'Italien', 'Spanien', 'Griechenland', 'Portugal'],
    ['In welchem Land steht der Eiffelturm?', 'Frankreich', 'Italien', 'Belgien', 'Spanien'],
    ['Was ist die Hauptstadt von Serbien?', 'Belgrad', 'Novi Sad', 'Niš', 'Zagreb'],
    ['Was ist die Hauptstadt von Kroatien?', 'Zagreb', 'Split', 'Sarajevo', 'Ljubljana'],
    ['Welches ist die größte Insel der Welt?', 'Grönland', 'Madagaskar', 'Borneo', 'Neuguinea'],
    ['Was ist die Hauptstadt von Japan?', 'Tokio', 'Osaka', 'Kyoto', 'Seoul'],
    ['Welcher Fluss fließt durch Paris?', 'Seine', 'Loire', 'Rhône', 'Themse'],
    ['Was ist die Hauptstadt von Österreich?', 'Wien', 'Salzburg', 'Graz', 'Linz'],
    ['Welcher Fluss ist der längste Afrikas?', 'Nil', 'Kongo', 'Niger', 'Sambesi'],
    ['In welcher Stadt steht das Brandenburger Tor?', 'Berlin', 'München', 'Hamburg', 'Dresden'],
    ['Welches ist das kleinste Land der Welt?', 'Vatikanstadt', 'Monaco', 'San Marino', 'Liechtenstein'],
    ['Auf welcher Insel liegt die Stadt Palma?', 'Mallorca', 'Ibiza', 'Teneriffa', 'Kreta'],
    ['Welcher Kontinent ist der kälteste?', 'Antarktis', 'Arktis', 'Europa', 'Asien'],
    ['Was ist die Hauptstadt von Brasilien?', 'Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'],
    ['Was ist die Hauptstadt der Türkei?', 'Ankara', 'Istanbul', 'Izmir', 'Antalya'],
    ['Was ist die Hauptstadt von Polen?', 'Warschau', 'Krakau', 'Danzig', 'Posen'],
    ['Durch welche Stadt fließt die Spree?', 'Berlin', 'Köln', 'Frankfurt', 'Leipzig'],
    ['Was ist die Hauptstadt der Niederlande?', 'Amsterdam', 'Rotterdam', 'Den Haag', 'Utrecht'],
    ['Was ist die Hauptstadt von Portugal?', 'Lissabon', 'Porto', 'Faro', 'Coimbra'],
    ['Was ist die Hauptstadt von Griechenland?', 'Athen', 'Thessaloniki', 'Patras', 'Heraklion'],
    ['Was ist die Hauptstadt von Schweden?', 'Stockholm', 'Göteborg', 'Malmö', 'Uppsala'],
    ['Was ist die Hauptstadt von Norwegen?', 'Oslo', 'Bergen', 'Trondheim', 'Stavanger'],
    ['Was ist die Hauptstadt von Ungarn?', 'Budapest', 'Debrecen', 'Szeged', 'Pécs'],
    ['Was ist die Hauptstadt von Tschechien?', 'Prag', 'Brünn', 'Pilsen', 'Ostrava'],
    ['Was ist die Hauptstadt von Irland?', 'Dublin', 'Cork', 'Galway', 'Belfast'],
    ['Was ist die Hauptstadt der USA?', 'Washington, D.C.', 'New York', 'Los Angeles', 'Chicago'],
    ['Was ist die Hauptstadt von Mexiko?', 'Mexiko-Stadt', 'Guadalajara', 'Cancún', 'Monterrey'],
    ['Was ist die Hauptstadt von Argentinien?', 'Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'],
    ['Was ist die Hauptstadt von Bosnien und Herzegowina?', 'Sarajevo', 'Mostar', 'Banja Luka', 'Tuzla'],
    ['Was ist die Hauptstadt von Montenegro?', 'Podgorica', 'Kotor', 'Budva', 'Cetinje'],
    ['Was ist die Hauptstadt von Nordmazedonien?', 'Skopje', 'Ohrid', 'Bitola', 'Tetovo'],
    ['Was ist die Hauptstadt von Slowenien?', 'Ljubljana', 'Maribor', 'Bled', 'Koper'],
    ['Was ist die Hauptstadt von Bulgarien?', 'Sofia', 'Plowdiw', 'Warna', 'Burgas'],
    ['Was ist die Hauptstadt von Rumänien?', 'Bukarest', 'Cluj-Napoca', 'Timișoara', 'Konstanza'],
    ['Was ist die Hauptstadt von Albanien?', 'Tirana', 'Durrës', 'Vlora', 'Shkodra'],
    ['An welchem Meer liegt die Stadt Dubrovnik?', 'Adria', 'Ägäis', 'Schwarzes Meer', 'Ionisches Meer'],
    ['Welcher Fluss fließt durch Belgrad?', 'Donau', 'Rhein', 'Elbe', 'Seine'],
    ['In welcher Stadt steht der Schiefe Turm?', 'Pisa', 'Rom', 'Florenz', 'Venedig'],
    ['In welcher Stadt steht das Hochhaus Burj Khalifa, das höchste Gebäude der Welt?', 'Dubai', 'Doha', 'Kuwait-Stadt', 'Riad'],
    ['Welche Stadt wird „Big Apple“ genannt?', 'New York', 'Los Angeles', 'Chicago', 'Boston'],
    ['Welches Land schenkte den USA die Freiheitsstatue?', 'Frankreich', 'England', 'Italien', 'Spanien'],
    ['Welches Land ist für seine Tulpen bekannt?', 'Niederlande', 'Belgien', 'Dänemark', 'Schweiz'],
    ['Welche Sprache wird in Brasilien gesprochen?', 'Portugiesisch', 'Spanisch', 'Englisch', 'Französisch'],
    ['Welche Sprache wird in Argentinien gesprochen?', 'Spanisch', 'Portugiesisch', 'Italienisch', 'Englisch'],
    // Natur und Tiere
    ['Welches ist das größte Landtier?', 'Afrikanischer Elefant', 'Nashorn', 'Giraffe', 'Nilpferd'],
    ['Wie viele Beine hat eine Spinne?', '8', '6', '10', '12'],
    ['Welches Tier ist an Land am schnellsten?', 'Gepard', 'Löwe', 'Antilope', 'Pferd'],
    ['Wie nennt man ein junges Pferd?', 'Fohlen', 'Kalb', 'Ferkel', 'Lamm'],
    ['Welcher dieser Vögel kann nicht fliegen?', 'Pinguin', 'Möwe', 'Adler', 'Schwalbe'],
    ['Welches ist das größte Säugetier der Erde?', 'Blauwal', 'Elefant', 'Pottwal', 'Giraffe'],
    ['Was wird aus einer Kaulquappe?', 'Ein Frosch', 'Ein Fisch', 'Ein Molch', 'Eine Schlange'],
    ['Wie viele Herzen hat ein Oktopus?', '3', '1', '2', '4'],
    ['Welches Tier hängt oft kopfüber im Baum und bewegt sich sehr langsam?', 'Faultier', 'Koala', 'Affe', 'Leopard'],
    ['Welches dieser Tiere ist ein Säugetier?', 'Delfin', 'Hai', 'Thunfisch', 'Krokodil'],
    ['Wo lebt der Eisbär?', 'In der Arktis', 'In der Antarktis', 'In der Sahara', 'In der Savanne'],
    ['Aus welcher Pflanze wird Schokolade hergestellt?', 'Kakao', 'Kaffee', 'Vanille', 'Zuckerrohr'],
    ['Welches Gas geben Pflanzen bei der Photosynthese ab?', 'Sauerstoff', 'Stickstoff', 'Kohlendioxid', 'Wasserstoff'],
    ['Welches Gas kommt in der Luft am häufigsten vor?', 'Stickstoff', 'Sauerstoff', 'Kohlendioxid', 'Argon'],
    ['Wie viele Beine hat ein Insekt?', '6', '4', '8', '10'],
    ['Welches Tier ist das Wappentier Deutschlands?', 'Adler', 'Löwe', 'Bär', 'Wolf'],
    ['Wie nennt man Tiere, die nur Pflanzen fressen?', 'Pflanzenfresser', 'Fleischfresser', 'Allesfresser', 'Insektenfresser'],
    // Wissenschaft
    ['Wie viele Planeten hat unser Sonnensystem?', '8', '7', '9', '10'],
    ['Welcher Planet ist der Sonne am nächsten?', 'Merkur', 'Venus', 'Mars', 'Erde'],
    ['Welcher Planet wird „der Rote Planet“ genannt?', 'Mars', 'Venus', 'Jupiter', 'Merkur'],
    ['Welcher Planet ist für seine Ringe berühmt?', 'Saturn', 'Mars', 'Venus', 'Merkur'],
    ['Welcher ist der größte Planet unseres Sonnensystems?', 'Jupiter', 'Saturn', 'Neptun', 'Erde'],
    ['Wie heißt die Galaxie, in der unsere Sonne liegt?', 'Milchstraße', 'Andromeda', 'Whirlpool', 'Sombrero'],
    ['Bei wie viel Grad Celsius gefriert Wasser normalerweise?', '0 Grad', '4 Grad', '10 Grad', '−10 Grad'],
    ['Bei wie viel Grad Celsius kocht Wasser auf Meereshöhe?', '100 Grad', '90 Grad', '80 Grad', '120 Grad'],
    ['Wie viele Knochen hat ein erwachsener Mensch ungefähr?', '206', '106', '306', '412'],
    ['Welches ist das größte Organ des Menschen?', 'Die Haut', 'Die Leber', 'Das Herz', 'Die Lunge'],
    ['Wie viele Zähne hat ein erwachsener Mensch mit Weisheitszähnen?', '32', '28', '30', '36'],
    ['Welches Metall ist bei Zimmertemperatur flüssig?', 'Quecksilber', 'Blei', 'Zinn', 'Eisen'],
    ['Welches chemische Symbol hat Gold?', 'Au', 'Ag', 'Go', 'Gd'],
    ['Wer wird mit der Entdeckung der Schwerkraft verbunden (Apfel-Legende)?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla'],
    ['Wie schnell ist Licht ungefähr?', '300.000 km pro Sekunde', '30.000 km pro Sekunde', '3.000.000 km pro Sekunde', '150.000 km pro Sekunde'],
    ['In welcher Einheit wird elektrische Spannung gemessen?', 'Volt', 'Watt', 'Ampere', 'Ohm'],
    ['Wie heißt der längste Knochen des menschlichen Körpers?', 'Oberschenkelknochen', 'Schienbein', 'Oberarmknochen', 'Wirbelsäule'],
    ['Welches Vitamin bildet der Körper mithilfe von Sonnenlicht?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B12'],
    ['Welche Zahl ist eine Primzahl?', '13', '15', '21', '27'],
    ['Wie viel ist die Quadratwurzel aus 144?', '12', '14', '11', '16'],
    ['Wie viel ist 7 mal 8?', '56', '54', '48', '63'],
    ['Wofür steht die Abkürzung USB?', 'Universal Serial Bus', 'United System Board', 'Ultra Speed Byte', 'Unified Storage Box'],
    ['Wofür steht „www“?', 'World Wide Web', 'Wide World Window', 'World Web Wire', 'Web Wide World'],
    // Geschichte und Kultur
    ['In welchem Jahr fiel die Berliner Mauer?', '1989', '1961', '1990', '1979'],
    ['Wer betrat als Erster den Mond?', 'Neil Armstrong', 'Buzz Aldrin', 'Juri Gagarin', 'Alan Shepard'],
    ['In welchem Jahr wurde Deutschland wiedervereinigt?', '1990', '1989', '1991', '1985'],
    ['Wer baute die Pyramiden von Gizeh?', 'Die alten Ägypter', 'Die Römer', 'Die Griechen', 'Die Perser'],
    ['In welchem Jahr begann der Erste Weltkrieg?', '1914', '1918', '1939', '1905'],
    ['Wie hieß das Schiff, das 1912 nach einem Eisberg sank?', 'Titanic', 'Bismarck', 'Santa Maria', 'Gorch Fock'],
    ['Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?', 'Konrad Adenauer', 'Willy Brandt', 'Helmut Kohl', 'Ludwig Erhard'],
    ['Wer malte die Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Raffael', 'Pablo Picasso'],
    ['Welcher Komponist wurde im Laufe seines Lebens fast taub?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Joseph Haydn'],
    ['Wer schrieb das Drama „Faust“?', 'Johann Wolfgang von Goethe', 'Friedrich Schiller', 'Gotthold Ephraim Lessing', 'Bertolt Brecht'],
    ['Wer erfand den Buchdruck mit beweglichen Lettern?', 'Johannes Gutenberg', 'Martin Luther', 'Albrecht Dürer', 'Leonardo da Vinci'],
    ['Wann endete der Zweite Weltkrieg in Europa?', '1945', '1944', '1946', '1950'],
    ['Wer gründete zusammen mit Paul Allen die Firma Microsoft?', 'Bill Gates', 'Steve Jobs', 'Mark Zuckerberg', 'Elon Musk'],
    ['Welches Unternehmen stellt das iPhone her?', 'Apple', 'Samsung', 'Nokia', 'Huawei'],
    ['Aus welchem Land stammt Sushi?', 'Japan', 'China', 'Thailand', 'Korea'],
    ['Aus welchem Land stammt die Pizza?', 'Italien', 'Griechenland', 'Frankreich', 'Spanien'],
    ['Welcher Käse stammt ursprünglich aus Griechenland?', 'Feta', 'Gouda', 'Emmentaler', 'Camembert'],
    ['Aus welcher Frucht wird Wein hergestellt?', 'Trauben', 'Äpfeln', 'Kirschen', 'Birnen'],
    ['Was ist die Hauptzutat von Guacamole?', 'Avocado', 'Tomate', 'Gurke', 'Paprika'],
    ['Wie heißt die Währung in Japan?', 'Yen', 'Won', 'Yuan', 'Rupie'],
    ['Wie heißt die Währung in der Schweiz?', 'Franken', 'Euro', 'Krone', 'Pfund'],
    ['Was ist die meistgesprochene Muttersprache der Welt?', 'Mandarin-Chinesisch', 'Englisch', 'Spanisch', 'Hindi'],
    // Sport und Alltag
    ['Wie viele Spieler hat eine Fußballmannschaft auf dem Feld?', '11', '10', '9', '12'],
    ['Wie oft finden die Olympischen Sommerspiele statt?', 'Alle 4 Jahre', 'Alle 2 Jahre', 'Jedes Jahr', 'Alle 5 Jahre'],
    ['Wie viele Ringe hat das Olympia-Symbol?', '5', '4', '6', '7'],
    ['Wie viele Spieler hat ein Volleyballteam auf dem Feld?', '6', '5', '7', '8'],
    ['Aus wie vielen Feldern besteht ein Schachbrett?', '64', '56', '72', '81'],
    ['Welche Schachfigur darf über andere Figuren springen?', 'Der Springer', 'Der Läufer', 'Der Turm', 'Die Dame'],
    ['Wie viele Tasten hat ein klassisches Klavier?', '88', '76', '92', '100'],
    ['Wie viele Saiten hat eine normale Gitarre?', '6', '4', '5', '7'],
    ['Wie viele Sekunden hat eine Stunde?', '3600', '1800', '6000', '360'],
    ['Wie viele Tage hat ein Schaltjahr?', '366', '365', '364', '367'],
    ['Wie viele Kontinente gibt es?', '7', '5', '6', '8'],
    ['Wie viele Farben hat ein Regenbogen traditionell?', '7', '5', '6', '8'],
    ['Welche Farbe entsteht, wenn man Blau und Gelb mischt?', 'Grün', 'Orange', 'Lila', 'Braun'],
    ['Wie viele Augen stehen bei einem Würfel auf gegenüberliegenden Seiten zusammen?', '7', '6', '8', '9'],
    ['Welche Farben hat die deutsche Flagge von oben nach unten?', 'Schwarz, Rot, Gold', 'Rot, Gelb, Schwarz', 'Gold, Schwarz, Rot', 'Schwarz, Gold, Rot'],
    ['Welcher Monat hat in einem normalen Jahr nur 28 Tage?', 'Februar', 'April', 'Juni', 'September'],
];

// Flaggen: [Ländercode (für flagcdn.com), deutscher Name]
export const FLAGS = [
    ['de', 'Deutschland'], ['at', 'Österreich'], ['ch', 'Schweiz'], ['fr', 'Frankreich'], ['it', 'Italien'], ['es', 'Spanien'], ['pt', 'Portugal'],
    ['nl', 'Niederlande'], ['be', 'Belgien'], ['gb', 'Vereinigtes Königreich'], ['ie', 'Irland'], ['dk', 'Dänemark'], ['se', 'Schweden'], ['no', 'Norwegen'],
    ['fi', 'Finnland'], ['is', 'Island'], ['pl', 'Polen'], ['cz', 'Tschechien'], ['sk', 'Slowakei'], ['hu', 'Ungarn'], ['ro', 'Rumänien'], ['bg', 'Bulgarien'],
    ['gr', 'Griechenland'], ['tr', 'Türkei'], ['rs', 'Serbien'], ['hr', 'Kroatien'], ['si', 'Slowenien'], ['ba', 'Bosnien und Herzegowina'], ['me', 'Montenegro'],
    ['mk', 'Nordmazedonien'], ['al', 'Albanien'], ['ua', 'Ukraine'], ['ru', 'Russland'], ['lt', 'Litauen'], ['lv', 'Lettland'], ['ee', 'Estland'],
    ['us', 'USA'], ['ca', 'Kanada'], ['mx', 'Mexiko'], ['br', 'Brasilien'], ['ar', 'Argentinien'], ['cl', 'Chile'], ['co', 'Kolumbien'], ['pe', 'Peru'],
    ['cu', 'Kuba'], ['jm', 'Jamaika'], ['jp', 'Japan'], ['cn', 'China'], ['kr', 'Südkorea'], ['in', 'Indien'], ['th', 'Thailand'], ['vn', 'Vietnam'],
    ['id', 'Indonesien'], ['ph', 'Philippinen'], ['au', 'Australien'], ['nz', 'Neuseeland'], ['za', 'Südafrika'], ['eg', 'Ägypten'], ['ma', 'Marokko'],
    ['ng', 'Nigeria'], ['ke', 'Kenia'], ['il', 'Israel'], ['sa', 'Saudi-Arabien'], ['ae', 'Vereinigte Arabische Emirate'], ['ir', 'Iran'], ['pk', 'Pakistan'], ['np', 'Nepal'],
];

// Begriffe zum Zeichnen (einfach darzustellen)
export const WORDS = [
    'Haus', 'Baum', 'Sonne', 'Katze', 'Hund', 'Fisch', 'Auto', 'Fahrrad', 'Flugzeug', 'Schiff', 'Blume', 'Apfel', 'Banane', 'Pizza', 'Herz', 'Stern', 'Mond',
    'Regenschirm', 'Brille', 'Schlüssel', 'Uhr', 'Telefon', 'Computer', 'Buch', 'Stuhl', 'Tisch', 'Bett', 'Tür', 'Fenster', 'Brücke', 'Berg', 'Wolke',
    'Regenbogen', 'Schmetterling', 'Biene', 'Spinne', 'Schlange', 'Elefant', 'Giraffe', 'Pinguin', 'Eis', 'Kuchen', 'Kerze', 'Geschenk', 'Ballon', 'Krone',
    'Schloss', 'Rakete', 'Roboter', 'Gitarre', 'Klavier', 'Zahnbürste', 'Schere', 'Hammer', 'Leiter', 'Zelt', 'Lagerfeuer', 'Burger', 'Kaffeetasse',
    'Schneemann', 'Weihnachtsbaum', 'Drache', 'Pirat', 'Fußball', 'Basketball', 'Fahne', 'Kamel', 'Eiffelturm', 'Windmühle', 'Leuchtturm', 'Vulkan', 'Hai',
    'Krokodil', 'Frosch', 'Ente', 'Hase', 'Pilz', 'Kaktus', 'Palme', 'Insel', 'Sonnenbrille', 'Brezel', 'Kürbis', 'Igel', 'Eule', 'Schnecke', 'Zug', 'Ufo',
];
