// Songliste fürs Lieder-Raten: nur Titel, Künstler, Jahrzehnt und Sprache (de = deutsch, en = alle anderen).
// Die Audio-Ausschnitte werden zur Laufzeit über die iTunes-Suche geholt, hier liegt keine Musik.
// Findet die Suche einen Eintrag nicht, wird er in dieser Runde einfach übersprungen.

const L = [
    // ---- 60er und 70er ----
    ['Hey Jude', 'The Beatles', 1960, 'en'], ['Let It Be', 'The Beatles', 1970, 'en'], ['Yesterday', 'The Beatles', 1960, 'en'],
    ['Come Together', 'The Beatles', 1960, 'en'], ['Here Comes the Sun', 'The Beatles', 1960, 'en'], ['Twist and Shout', 'The Beatles', 1960, 'en'],
    ['Penny Lane', 'The Beatles', 1960, 'en'], ['Help!', 'The Beatles', 1960, 'en'],
    ['Satisfaction', 'The Rolling Stones', 1960, 'en'], ['Paint It Black', 'The Rolling Stones', 1960, 'en'], ['Angie', 'The Rolling Stones', 1970, 'en'],
    ['Start Me Up', 'The Rolling Stones', 1980, 'en'], ['Sympathy for the Devil', 'The Rolling Stones', 1960, 'en'],
    ['Bohemian Rhapsody', 'Queen', 1970, 'en'], ["Don't Stop Me Now", 'Queen', 1970, 'en'], ['We Will Rock You', 'Queen', 1970, 'en'],
    ['We Are the Champions', 'Queen', 1970, 'en'], ['Another One Bites the Dust', 'Queen', 1980, 'en'], ['Somebody to Love', 'Queen', 1970, 'en'],
    ['Under Pressure', 'Queen', 1980, 'en'], ['I Want to Break Free', 'Queen', 1980, 'en'], ['Radio Ga Ga', 'Queen', 1980, 'en'],
    ['Killer Queen', 'Queen', 1970, 'en'], ['A Kind of Magic', 'Queen', 1980, 'en'],
    ['Dancing Queen', 'ABBA', 1970, 'en'], ['Mamma Mia', 'ABBA', 1970, 'en'], ['Waterloo', 'ABBA', 1970, 'en'], ['Gimme! Gimme! Gimme!', 'ABBA', 1970, 'en'],
    ['Super Trouper', 'ABBA', 1980, 'en'], ['Take a Chance on Me', 'ABBA', 1970, 'en'], ['Money, Money, Money', 'ABBA', 1970, 'en'],
    ['The Winner Takes It All', 'ABBA', 1980, 'en'], ['Fernando', 'ABBA', 1970, 'en'], ['Voulez-Vous', 'ABBA', 1970, 'en'], ['Chiquitita', 'ABBA', 1970, 'en'],
    ["Stayin' Alive", 'Bee Gees', 1970, 'en'], ['Night Fever', 'Bee Gees', 1970, 'en'], ['How Deep Is Your Love', 'Bee Gees', 1970, 'en'],
    ['Rasputin', 'Boney M.', 1970, 'en'], ['Daddy Cool', 'Boney M.', 1970, 'en'], ['Rivers of Babylon', 'Boney M.', 1970, 'en'], ['Ma Baker', 'Boney M.', 1970, 'en'],
    ['Sunny', 'Boney M.', 1970, 'en'], ['Brown Girl in the Ring', 'Boney M.', 1970, 'en'],
    ['Rocket Man', 'Elton John', 1970, 'en'], ['Your Song', 'Elton John', 1970, 'en'], ['Tiny Dancer', 'Elton John', 1970, 'en'],
    ["I'm Still Standing", 'Elton John', 1980, 'en'], ["Don't Go Breaking My Heart", 'Elton John', 1970, 'en'], ['Crocodile Rock', 'Elton John', 1970, 'en'],
    ['Dreams', 'Fleetwood Mac', 1970, 'en'], ['Go Your Own Way', 'Fleetwood Mac', 1970, 'en'], ['Everywhere', 'Fleetwood Mac', 1980, 'en'],
    ['Hotel California', 'Eagles', 1970, 'en'], ['Take It Easy', 'Eagles', 1970, 'en'],
    ['Another Brick in the Wall', 'Pink Floyd', 1970, 'en'], ['Wish You Were Here', 'Pink Floyd', 1970, 'en'], ['Comfortably Numb', 'Pink Floyd', 1970, 'en'],
    ['Stairway to Heaven', 'Led Zeppelin', 1970, 'en'], ['Whole Lotta Love', 'Led Zeppelin', 1960, 'en'],
    ['Heroes', 'David Bowie', 1970, 'en'], ['Space Oddity', 'David Bowie', 1960, 'en'], ["Let's Dance", 'David Bowie', 1980, 'en'], ['Starman', 'David Bowie', 1970, 'en'],
    ["Da Ya Think I'm Sexy?", 'Rod Stewart', 1970, 'en'], ['Maggie May', 'Rod Stewart', 1970, 'en'], ['Sailing', 'Rod Stewart', 1970, 'en'],
    ['I Feel Love', 'Donna Summer', 1970, 'en'], ['Hot Stuff', 'Donna Summer', 1970, 'en'], ['Last Dance', 'Donna Summer', 1970, 'en'],
    ['I Will Survive', 'Gloria Gaynor', 1970, 'en'], ['Le Freak', 'Chic', 1970, 'en'], ['Good Times', 'Chic', 1970, 'en'],
    ['Y.M.C.A.', 'Village People', 1970, 'en'], ['In the Navy', 'Village People', 1970, 'en'], ['Macho Man', 'Village People', 1970, 'en'],
    ['Celebration', 'Kool & The Gang', 1980, 'en'], ['Get Down on It', 'Kool & The Gang', 1980, 'en'], ["Ladies' Night", 'Kool & The Gang', 1970, 'en'],
    ['September', 'Earth, Wind & Fire', 1970, 'en'], ['Boogie Wonderland', 'Earth, Wind & Fire', 1970, 'en'], ["Let's Groove", 'Earth, Wind & Fire', 1980, 'en'],
    ['Superstition', 'Stevie Wonder', 1970, 'en'], ['Sir Duke', 'Stevie Wonder', 1970, 'en'], ['I Just Called to Say I Love You', 'Stevie Wonder', 1980, 'en'],
    ["Isn't She Lovely", 'Stevie Wonder', 1970, 'en'], ["Let's Get It On", 'Marvin Gaye', 1970, 'en'], ['I Heard It Through the Grapevine', 'Marvin Gaye', 1960, 'en'],
    ['Respect', 'Aretha Franklin', 1960, 'en'], ['Proud Mary', 'Tina Turner', 1970, 'en'], ["What's Love Got to Do with It", 'Tina Turner', 1980, 'en'],
    ['The Best', 'Tina Turner', 1980, 'en'], ['The Logical Song', 'Supertramp', 1970, 'en'], ['Breakfast in America', 'Supertramp', 1970, 'en'],
    ['Ballroom Blitz', 'Sweet', 1970, 'en'], ['Merry Xmas Everybody', 'Slade', 1970, 'en'], ["Cum On Feel the Noize", 'Slade', 1970, 'en'],
    ['Living Next Door to Alice', 'Smokie', 1970, 'en'], ['Get It On', 'T. Rex', 1970, 'en'], ['Born to Be Wild', 'Steppenwolf', 1960, 'en'],
    ['Have You Ever Seen the Rain?', 'Creedence Clearwater Revival', 1970, 'en'], ['Bad Moon Rising', 'Creedence Clearwater Revival', 1960, 'en'],
    ['Smoke on the Water', 'Deep Purple', 1970, 'en'], ['Highway to Hell', 'AC/DC', 1970, 'en'], ['Back in Black', 'AC/DC', 1980, 'en'],
    ['You Shook Me All Night Long', 'AC/DC', 1980, 'en'], ['Thunderstruck', 'AC/DC', 1990, 'en'],
    ['The Sound of Silence', 'Simon & Garfunkel', 1960, 'en'], ['Mrs. Robinson', 'Simon & Garfunkel', 1960, 'en'],
    ["California Dreamin'", 'The Mamas & The Papas', 1960, 'en'], ['Good Vibrations', 'The Beach Boys', 1960, 'en'],
    ['What a Wonderful World', 'Louis Armstrong', 1960, 'en'], ['My Way', 'Frank Sinatra', 1960, 'en'], ['Fly Me to the Moon', 'Frank Sinatra', 1960, 'en'],
    ["Can't Help Falling in Love", 'Elvis Presley', 1960, 'en'], ['Jailhouse Rock', 'Elvis Presley', 1950, 'en'], ['Suspicious Minds', 'Elvis Presley', 1960, 'en'],
    ['No Woman, No Cry', 'Bob Marley & The Wailers', 1970, 'en'], ['Three Little Birds', 'Bob Marley & The Wailers', 1970, 'en'],
    ['Is This Love', 'Bob Marley & The Wailers', 1970, 'en'], ['Buffalo Soldier', 'Bob Marley & The Wailers', 1980, 'en'],
    ['Imagine', 'John Lennon', 1970, 'en'], ['Sweet Caroline', 'Neil Diamond', 1960, 'en'], ["You're the First, the Last, My Everything", 'Barry White', 1970, 'en'],
    ['Funkytown', 'Lipps Inc.', 1980, 'en'], ['You Sexy Thing', 'Hot Chocolate', 1970, 'en'], ['Mr. Blue Sky', 'Electric Light Orchestra', 1970, 'en'],
    ['Heart of Glass', 'Blondie', 1970, 'en'], ['Call Me', 'Blondie', 1980, 'en'], ['Roxanne', 'The Police', 1970, 'en'],
    ['Every Breath You Take', 'The Police', 1980, 'en'], ['Message in a Bottle', 'The Police', 1970, 'en'], ['Sultans of Swing', 'Dire Straits', 1970, 'en'],
    ['Money for Nothing', 'Dire Straits', 1980, 'en'], ['Black Magic Woman', 'Santana', 1970, 'en'], ["I Want You Back", 'The Jackson 5', 1970, 'en'],

    // ---- 80er ----
    ['Thriller', 'Michael Jackson', 1980, 'en'], ['Billie Jean', 'Michael Jackson', 1980, 'en'], ['Beat It', 'Michael Jackson', 1980, 'en'],
    ['Smooth Criminal', 'Michael Jackson', 1980, 'en'], ['Bad', 'Michael Jackson', 1980, 'en'], ['Man in the Mirror', 'Michael Jackson', 1980, 'en'],
    ["Don't Stop 'Til You Get Enough", 'Michael Jackson', 1970, 'en'], ['Black or White', 'Michael Jackson', 1990, 'en'],
    ['Like a Virgin', 'Madonna', 1980, 'en'], ['Material Girl', 'Madonna', 1980, 'en'], ['Like a Prayer', 'Madonna', 1980, 'en'],
    ['La Isla Bonita', 'Madonna', 1980, 'en'], ['Vogue', 'Madonna', 1990, 'en'], ['Holiday', 'Madonna', 1980, 'en'], ["Papa Don't Preach", 'Madonna', 1980, 'en'],
    ['Into the Groove', 'Madonna', 1980, 'en'], ['Hung Up', 'Madonna', 2000, 'en'],
    ['Purple Rain', 'Prince', 1980, 'en'], ['Kiss', 'Prince', 1980, 'en'], ['When Doves Cry', 'Prince', 1980, 'en'], ['1999', 'Prince', 1980, 'en'],
    ['I Wanna Dance with Somebody (Who Loves Me)', 'Whitney Houston', 1980, 'en'], ['I Will Always Love You', 'Whitney Houston', 1990, 'en'],
    ['How Will I Know', 'Whitney Houston', 1980, 'en'], ['Greatest Love of All', 'Whitney Houston', 1980, 'en'],
    ['Girls Just Want to Have Fun', 'Cyndi Lauper', 1980, 'en'], ['Time After Time', 'Cyndi Lauper', 1980, 'en'], ['True Colors', 'Cyndi Lauper', 1980, 'en'],
    ['Last Christmas', 'Wham!', 1980, 'en'], ['Wake Me Up Before You Go-Go', 'Wham!', 1980, 'en'], ['Club Tropicana', 'Wham!', 1980, 'en'],
    ['Careless Whisper', 'George Michael', 1980, 'en'], ['Faith', 'George Michael', 1980, 'en'], ['Freedom! \'90', 'George Michael', 1990, 'en'],
    ['Rio', 'Duran Duran', 1980, 'en'], ['Hungry Like the Wolf', 'Duran Duran', 1980, 'en'], ['Ordinary World', 'Duran Duran', 1990, 'en'],
    ['Take On Me', 'a-ha', 1980, 'en'], ['The Sun Always Shines on T.V.', 'a-ha', 1980, 'en'],
    ['Enjoy the Silence', 'Depeche Mode', 1990, 'en'], ['Personal Jesus', 'Depeche Mode', 1980, 'en'], ["Just Can't Get Enough", 'Depeche Mode', 1980, 'en'],
    ['Sweet Dreams (Are Made of This)', 'Eurythmics', 1980, 'en'], ['Here Comes the Rain Again', 'Eurythmics', 1980, 'en'],
    ['Karma Chameleon', 'Culture Club', 1980, 'en'], ['Do You Really Want to Hurt Me', 'Culture Club', 1980, 'en'],
    ["Livin' on a Prayer", 'Bon Jovi', 1980, 'en'], ['You Give Love a Bad Name', 'Bon Jovi', 1980, 'en'], ["It's My Life", 'Bon Jovi', 2000, 'en'],
    ['Always', 'Bon Jovi', 1990, 'en'], ['Bad Medicine', 'Bon Jovi', 1980, 'en'],
    ["Sweet Child o' Mine", "Guns N' Roses", 1980, 'en'], ['Welcome to the Jungle', "Guns N' Roses", 1980, 'en'], ['Paradise City', "Guns N' Roses", 1980, 'en'],
    ['November Rain', "Guns N' Roses", 1990, 'en'], ['The Final Countdown', 'Europe', 1980, 'en'],
    ['Africa', 'Toto', 1980, 'en'], ['Rosanna', 'Toto', 1980, 'en'], ['Hold the Line', 'Toto', 1970, 'en'],
    ["Don't Stop Believin'", 'Journey', 1980, 'en'], ['Any Way You Want It', 'Journey', 1980, 'en'], ['Eye of the Tiger', 'Survivor', 1980, 'en'],
    ['Total Eclipse of the Heart', 'Bonnie Tyler', 1980, 'en'], ['Holding Out for a Hero', 'Bonnie Tyler', 1980, 'en'],
    ['White Wedding', 'Billy Idol', 1980, 'en'], ['Rebel Yell', 'Billy Idol', 1980, 'en'], ['Never Gonna Give You Up', 'Rick Astley', 1980, 'en'],
    ['Kids in America', 'Kim Wilde', 1980, 'en'], ["You Keep Me Hangin' On", 'Kim Wilde', 1980, 'en'], ['True', 'Spandau Ballet', 1980, 'en'],
    ['Shout', 'Tears for Fears', 1980, 'en'], ['Everybody Wants to Rule the World', 'Tears for Fears', 1980, 'en'],
    ['In the Air Tonight', 'Phil Collins', 1980, 'en'], ['Against All Odds (Take a Look at Me Now)', 'Phil Collins', 1980, 'en'],
    ['Another Day in Paradise', 'Phil Collins', 1980, 'en'], ['Sussudio', 'Phil Collins', 1980, 'en'],
    ['Hello', 'Lionel Richie', 1980, 'en'], ['All Night Long (All Night)', 'Lionel Richie', 1980, 'en'], ['Dancing on the Ceiling', 'Lionel Richie', 1980, 'en'],
    ['I Want to Know What Love Is', 'Foreigner', 1980, 'en'], ['We Built This City', 'Starship', 1980, 'en'], ['The Power of Love', 'Huey Lewis & The News', 1980, 'en'],
    ["Summer of '69", 'Bryan Adams', 1980, 'en'], ['Heaven', 'Bryan Adams', 1980, 'en'], ['(Everything I Do) I Do It for You', 'Bryan Adams', 1990, 'en'],
    ['Born in the U.S.A.', 'Bruce Springsteen', 1980, 'en'], ['Dancing in the Dark', 'Bruce Springsteen', 1980, 'en'],
    ['With or Without You', 'U2', 1980, 'en'], ['Beautiful Day', 'U2', 2000, 'en'], ['One', 'U2', 1990, 'en'], ['Sunday Bloody Sunday', 'U2', 1980, 'en'],
    ["I Still Haven't Found What I'm Looking For", 'U2', 1980, 'en'], ['Losing My Religion', 'R.E.M.', 1990, 'en'],
    ["Don't You (Forget About Me)", 'Simple Minds', 1980, 'en'], ['West End Girls', 'Pet Shop Boys', 1980, 'en'], ["It's a Sin", 'Pet Shop Boys', 1980, 'en'],
    ['Tainted Love', 'Soft Cell', 1980, 'en'], ["Don't You Want Me", 'The Human League', 1980, 'en'], ['Relax', 'Frankie Goes to Hollywood', 1980, 'en'],
    ['Come On Eileen', 'Dexys Midnight Runners', 1980, 'en'], ['Down Under', 'Men at Work', 1980, 'en'], ['Electric Avenue', 'Eddy Grant', 1980, 'en'],
    ['Cruel Summer', 'Bananarama', 1980, 'en'], ['Venus', 'Bananarama', 1980, 'en'], ['You Spin Me Round (Like a Record)', 'Dead or Alive', 1980, 'en'],
    ['The Look', 'Roxette', 1980, 'en'], ['It Must Have Been Love', 'Roxette', 1990, 'en'], ['Listen to Your Heart', 'Roxette', 1980, 'en'],
    ['I Should Be So Lucky', 'Kylie Minogue', 1980, 'en'], ['Need You Tonight', 'INXS', 1980, 'en'], ['Maneater', 'Daryl Hall & John Oates', 1980, 'en'],
    ['You Make My Dreams', 'Daryl Hall & John Oates', 1980, 'en'], ['Drive', 'The Cars', 1980, 'en'], ['Ghostbusters', 'Ray Parker Jr.', 1980, 'en'],
    ['Footloose', 'Kenny Loggins', 1980, 'en'], ['Danger Zone', 'Kenny Loggins', 1980, 'en'], ['Take My Breath Away', 'Berlin', 1980, 'en'],
    ['Flashdance... What a Feeling', 'Irene Cara', 1980, 'en'], ['Love Is a Battlefield', 'Pat Benatar', 1980, 'en'], ["I Love Rock 'n' Roll", 'Joan Jett & The Blackhearts', 1980, 'en'],
    ['Jump', 'Van Halen', 1980, 'en'], ['Pour Some Sugar on Me', 'Def Leppard', 1980, 'en'], ['Every Rose Has Its Thorn', 'Poison', 1980, 'en'],
    ['Here I Go Again', 'Whitesnake', 1980, 'en'], ['Wind of Change', 'Scorpions', 1990, 'en'], ['Rock You Like a Hurricane', 'Scorpions', 1980, 'en'],
    ['Nothing Else Matters', 'Metallica', 1990, 'en'], ['Enter Sandman', 'Metallica', 1990, 'en'],

    // ---- 90er ----
    ['I Want It That Way', 'Backstreet Boys', 1990, 'en'], ["Everybody (Backstreet's Back)", 'Backstreet Boys', 1990, 'en'],
    ['As Long as You Love Me', 'Backstreet Boys', 1990, 'en'], ['Larger than Life', 'Backstreet Boys', 1990, 'en'],
    ['Bye Bye Bye', '*NSYNC', 2000, 'en'], ["It's Gonna Be Me", '*NSYNC', 2000, 'en'], ["Tearin' Up My Heart", '*NSYNC', 1990, 'en'],
    ['Wannabe', 'Spice Girls', 1990, 'en'], ['Spice Up Your Life', 'Spice Girls', 1990, 'en'], ['Stop', 'Spice Girls', 1990, 'en'],
    ['...Baby One More Time', 'Britney Spears', 1990, 'en'], ['Oops!... I Did It Again', 'Britney Spears', 2000, 'en'], ['Toxic', 'Britney Spears', 2000, 'en'],
    ['Womanizer', 'Britney Spears', 2000, 'en'], ['Back for Good', 'Take That', 1990, 'en'], ['Never Forget', 'Take That', 1990, 'en'], ['Patience', 'Take That', 2000, 'en'],
    ['Relight My Fire', 'Take That', 1990, 'en'], ['Wonderwall', 'Oasis', 1990, 'en'], ["Don't Look Back in Anger", 'Oasis', 1990, 'en'],
    ['Champagne Supernova', 'Oasis', 1990, 'en'], ['Live Forever', 'Oasis', 1990, 'en'], ['Song 2', 'Blur', 1990, 'en'], ['Parklife', 'Blur', 1990, 'en'],
    ['Smells Like Teen Spirit', 'Nirvana', 1990, 'en'], ['Come as You Are', 'Nirvana', 1990, 'en'], ['Under the Bridge', 'Red Hot Chili Peppers', 1990, 'en'],
    ['Californication', 'Red Hot Chili Peppers', 1990, 'en'], ['Scar Tissue', 'Red Hot Chili Peppers', 1990, 'en'], ["Can't Stop", 'Red Hot Chili Peppers', 2000, 'en'],
    ['Basket Case', 'Green Day', 1990, 'en'], ['Good Riddance (Time of Your Life)', 'Green Day', 1990, 'en'], ['No Scrubs', 'TLC', 1990, 'en'], ['Waterfalls', 'TLC', 1990, 'en'],
    ['Say My Name', "Destiny's Child", 1990, 'en'], ['Survivor', "Destiny's Child", 2000, 'en'], ['Bootylicious', "Destiny's Child", 2000, 'en'],
    ['Barbie Girl', 'Aqua', 1990, 'en'], ['Dr. Jones', 'Aqua', 1990, 'en'], ['Roses Are Red', 'Aqua', 1990, 'en'], ['Blue (Da Ba Dee)', 'Eiffel 65', 1990, 'en'],
    ['What Is Love', 'Haddaway', 1990, 'en'], ['Rhythm Is a Dancer', 'SNAP!', 1990, 'en'], ['No Limit', '2 Unlimited', 1990, 'en'], ['Get Ready for This', '2 Unlimited', 1990, 'en'],
    ['Mr. Vain', 'Culture Beat', 1990, 'en'], ["It's My Life", 'Dr. Alban', 1990, 'en'], ['Be My Lover', 'La Bouche', 1990, 'en'], ['Cotton Eye Joe', 'Rednex', 1990, 'en'],
    ['More and More', 'Captain Hollywood Project', 1990, 'en'], ['Another Night', 'Real McCoy', 1990, 'en'], ['The Sign', 'Ace of Base', 1990, 'en'],
    ['All That She Wants', 'Ace of Base', 1990, 'en'], ['Lemon Tree', "Fool's Garden", 1990, 'en'], ['We Like to Party!', 'Vengaboys', 1990, 'en'],
    ['Boom, Boom, Boom, Boom!!', 'Vengaboys', 1990, 'en'], ["We're Going to Ibiza!", 'Vengaboys', 1990, 'en'], ['Mambo No. 5 (A Little Bit of...)', 'Lou Bega', 1990, 'en'],
    ['Believe', 'Cher', 1990, 'en'], ['Angels', 'Robbie Williams', 1990, 'en'], ['Rock DJ', 'Robbie Williams', 2000, 'en'], ['Let Me Entertain You', 'Robbie Williams', 1990, 'en'],
    ['Feel', 'Robbie Williams', 2000, 'en'], ['My Heart Will Go On', 'Céline Dion', 1990, 'en'], ['Hero', 'Mariah Carey', 1990, 'en'], ['Fantasy', 'Mariah Carey', 1990, 'en'],
    ['All I Want for Christmas Is You', 'Mariah Carey', 1990, 'en'], ['We Belong Together', 'Mariah Carey', 2000, 'en'],
    ['Man! I Feel Like a Woman!', 'Shania Twain', 1990, 'en'], ["That Don't Impress Me Much", 'Shania Twain', 1990, 'en'],
    ['Livin\' la Vida Loca', 'Ricky Martin', 1990, 'en'], ['Bailamos', 'Enrique Iglesias', 1990, 'en'], ['Fly Away', 'Lenny Kravitz', 1990, 'en'],
    ['Are You Gonna Go My Way', 'Lenny Kravitz', 1990, 'en'], ['Ironic', 'Alanis Morissette', 1990, 'en'], ['You Oughta Know', 'Alanis Morissette', 1990, 'en'],
    ['Zombie', 'The Cranberries', 1990, 'en'], ['Linger', 'The Cranberries', 1990, 'en'], ['Buddy Holly', 'Weezer', 1990, 'en'], ['All Star', 'Smash Mouth', 1990, 'en'],
    ['Tubthumping', 'Chumbawamba', 1990, 'en'], ['Steal My Sunshine', 'Len', 1990, 'en'], ['Torn', 'Natalie Imbruglia', 1990, 'en'],
    ['All I Wanna Do', 'Sheryl Crow', 1990, 'en'], ['Mr. Jones', 'Counting Crows', 1990, 'en'], ['Kiss from a Rose', 'Seal', 1990, 'en'], ['Tears in Heaven', 'Eric Clapton', 1990, 'en'],
    ["Gangsta's Paradise", 'Coolio', 1990, 'en'], ['California Love', '2Pac', 1990, 'en'], ["Gettin' Jiggy wit It", 'Will Smith', 1990, 'en'], ['Men in Black', 'Will Smith', 1990, 'en'],
    ['Killing Me Softly with His Song', 'Fugees', 1990, 'en'], ['Ready or Not', 'Fugees', 1990, 'en'], ['This Is How We Do It', 'Montell Jordan', 1990, 'en'],
    ['Push It', 'Salt-N-Pepa', 1980, 'en'], ['Ice Ice Baby', 'Vanilla Ice', 1990, 'en'], ["U Can't Touch This", 'MC Hammer', 1990, 'en'], ['Pump Up the Jam', 'Technotronic', 1990, 'en'],
    ["I'm Too Sexy", 'Right Said Fred', 1990, 'en'], ['Baby Got Back', 'Sir Mix-A-Lot', 1990, 'en'], ['Macarena (Bayside Boys Mix)', 'Los del Río', 1990, 'en'],
    ['Saturday Night', 'Whigfield', 1990, 'en'], ['Firestarter', 'The Prodigy', 1990, 'en'], ['Praise You', 'Fatboy Slim', 1990, 'en'], ['Insomnia', 'Faithless', 1990, 'en'],
    ['Born Slippy', 'Underworld', 1990, 'en'], ['Sandstorm', 'Darude', 1990, 'en'], ['Freed from Desire', 'Gala', 1990, 'en'], ['Ecuador', 'Sash!', 1990, 'en'],
    ['Coco Jamboo', 'Mr. President', 1990, 'en'], ['Better Off Alone', 'Alice Deejay', 1990, 'en'], ["9 PM (Till I Come)", 'ATB', 1990, 'en'], ['Lady (Hear Me Tonight)', 'Modjo', 2000, 'en'],
    ['Music Sounds Better with You', 'Stardust', 1990, 'en'], ['One More Time', 'Daft Punk', 2000, 'en'], ['Lovefool', 'The Cardigans', 1990, 'en'],
    ['Fields of Gold', 'Sting', 1990, 'en'], ["I'd Do Anything for Love (But I Won't Do That)", 'Meat Loaf', 1990, 'en'],
    ["I Don't Want to Miss a Thing", 'Aerosmith', 1990, 'en'], ['Dream On', 'Aerosmith', 1970, 'en'], ['Crazy', 'Aerosmith', 1990, 'en'],
    ['Alive', 'Pearl Jam', 1990, 'en'], ['Black Hole Sun', 'Soundgarden', 1990, 'en'], ['Creep', 'Radiohead', 1990, 'en'], ['Teardrop', 'Massive Attack', 1990, 'en'],
    ['Stupid Girl', 'Garbage', 1990, 'en'], ['Save Tonight', 'Eagle-Eye Cherry', 1990, 'en'], ['Truly Madly Deeply', 'Savage Garden', 1990, 'en'],
    ["What's Up?", '4 Non Blondes', 1990, 'en'], ['One of Us', 'Joan Osborne', 1990, 'en'], ['Un-Break My Heart', 'Toni Braxton', 1990, 'en'],
    ['No Matter What', 'Boyzone', 1990, 'en'], ['Flying Without Wings', 'Westlife', 1990, 'en'], ['Stay Another Day', 'East 17', 1990, 'en'],
    ['Love Is All Around', 'Wet Wet Wet', 1990, 'en'], ['Dreams', 'Gabrielle', 1990, 'en'],

    // ---- 2000er ----
    ['Lose Yourself', 'Eminem', 2000, 'en'], ['Stan', 'Eminem', 2000, 'en'], ['The Real Slim Shady', 'Eminem', 2000, 'en'], ['Without Me', 'Eminem', 2000, 'en'],
    ['Crazy in Love', 'Beyoncé', 2000, 'en'], ['Single Ladies (Put a Ring on It)', 'Beyoncé', 2000, 'en'], ['Halo', 'Beyoncé', 2000, 'en'], ['Irreplaceable', 'Beyoncé', 2000, 'en'],
    ['Umbrella', 'Rihanna', 2000, 'en'], ['Diamonds', 'Rihanna', 2010, 'en'], ['We Found Love', 'Rihanna', 2010, 'en'], ["Don't Stop the Music", 'Rihanna', 2000, 'en'],
    ['Only Girl (In the World)', 'Rihanna', 2010, 'en'], ['Rude Boy', 'Rihanna', 2010, 'en'], ['Work', 'Rihanna', 2010, 'en'],
    ["Hips Don't Lie", 'Shakira', 2000, 'en'], ['Whenever, Wherever', 'Shakira', 2000, 'en'], ['Waka Waka (This Time for Africa)', 'Shakira', 2010, 'en'],
    ['I Gotta Feeling', 'The Black Eyed Peas', 2000, 'en'], ['Where Is the Love?', 'The Black Eyed Peas', 2000, 'en'], ['Boom Boom Pow', 'The Black Eyed Peas', 2000, 'en'],
    ["Let's Get It Started", 'The Black Eyed Peas', 2000, 'en'], ['My Humps', 'The Black Eyed Peas', 2000, 'en'], ['Hey Ya!', 'OutKast', 2000, 'en'], ['Ms. Jackson', 'OutKast', 2000, 'en'],
    ['Yeah!', 'Usher', 2000, 'en'], ['Burn', 'Usher', 2000, 'en'], ['Cry Me a River', 'Justin Timberlake', 2000, 'en'], ['SexyBack', 'Justin Timberlake', 2000, 'en'],
    ['Rock Your Body', 'Justin Timberlake', 2000, 'en'], ["Can't Stop the Feeling!", 'Justin Timberlake', 2010, 'en'], ['Mirrors', 'Justin Timberlake', 2010, 'en'],
    ['Since U Been Gone', 'Kelly Clarkson', 2000, 'en'], ['Stronger (What Doesn\'t Kill You)', 'Kelly Clarkson', 2010, 'en'], ['Because of You', 'Kelly Clarkson', 2000, 'en'],
    ['In the End', 'Linkin Park', 2000, 'en'], ['Numb', 'Linkin Park', 2000, 'en'], ['Crawling', 'Linkin Park', 2000, 'en'], ["What I've Done", 'Linkin Park', 2000, 'en'],
    ['Viva la Vida', 'Coldplay', 2000, 'en'], ['Clocks', 'Coldplay', 2000, 'en'], ['Yellow', 'Coldplay', 2000, 'en'], ['Fix You', 'Coldplay', 2000, 'en'],
    ['The Scientist', 'Coldplay', 2000, 'en'], ['Paradise', 'Coldplay', 2010, 'en'], ['A Sky Full of Stars', 'Coldplay', 2010, 'en'],
    ['Mr. Brightside', 'The Killers', 2000, 'en'], ['Somebody Told Me', 'The Killers', 2000, 'en'], ['When You Were Young', 'The Killers', 2000, 'en'], ['Human', 'The Killers', 2000, 'en'],
    ['Sex on Fire', 'Kings of Leon', 2000, 'en'], ['Use Somebody', 'Kings of Leon', 2000, 'en'], ['Do I Wanna Know?', 'Arctic Monkeys', 2010, 'en'],
    ['I Bet You Look Good on the Dancefloor', 'Arctic Monkeys', 2000, 'en'], ['Rehab', 'Amy Winehouse', 2000, 'en'], ['Back to Black', 'Amy Winehouse', 2000, 'en'],
    ['Valerie', 'Mark Ronson', 2000, 'en'], ['Crazy', 'Gnarls Barkley', 2000, 'en'], ['Get Busy', 'Sean Paul', 2000, 'en'], ['Temperature', 'Sean Paul', 2000, 'en'],
    ['Hot in Herre', 'Nelly', 2000, 'en'], ['Dilemma', 'Nelly', 2000, 'en'], ['In da Club', '50 Cent', 2000, 'en'], ['Candy Shop', '50 Cent', 2000, 'en'],
    ["Drop It Like It's Hot", 'Snoop Dogg', 2000, 'en'], ['Genie in a Bottle', 'Christina Aguilera', 1990, 'en'], ['Dirrty', 'Christina Aguilera', 2000, 'en'],
    ['Beautiful', 'Christina Aguilera', 2000, 'en'], ['Get the Party Started', 'P!nk', 2000, 'en'], ['Just Like a Pill', 'P!nk', 2000, 'en'], ['So What', 'P!nk', 2000, 'en'],
    ['Raise Your Glass', 'P!nk', 2010, 'en'], ['Just Give Me a Reason', 'P!nk', 2010, 'en'], ['Complicated', 'Avril Lavigne', 2000, 'en'], ['Sk8er Boi', 'Avril Lavigne', 2000, 'en'],
    ['Girlfriend', 'Avril Lavigne', 2000, 'en'], ['Bring Me to Life', 'Evanescence', 2000, 'en'], ["Can't Get You Out of My Head", 'Kylie Minogue', 2000, 'en'],
    ['Spinning Around', 'Kylie Minogue', 2000, 'en'], ['Just Dance', 'Lady Gaga', 2000, 'en'], ['Poker Face', 'Lady Gaga', 2000, 'en'], ['Bad Romance', 'Lady Gaga', 2000, 'en'],
    ['Paparazzi', 'Lady Gaga', 2000, 'en'], ['Born This Way', 'Lady Gaga', 2010, 'en'], ['Shallow', 'Lady Gaga', 2010, 'en'],
    ['I Kissed a Girl', 'Katy Perry', 2000, 'en'], ['Firework', 'Katy Perry', 2010, 'en'], ['California Gurls', 'Katy Perry', 2010, 'en'], ['Roar', 'Katy Perry', 2010, 'en'],
    ['Teenage Dream', 'Katy Perry', 2010, 'en'], ['Dark Horse', 'Katy Perry', 2010, 'en'], ['Dynamite', 'Taio Cruz', 2010, 'en'], ['Low', 'Flo Rida', 2000, 'en'],
    ['Right Round', 'Flo Rida', 2000, 'en'], ['Good Feeling', 'Flo Rida', 2010, 'en'], ['Titanium', 'David Guetta', 2010, 'en'], ['When Love Takes Over', 'David Guetta', 2000, 'en'],
    ['Give Me Everything', 'Pitbull', 2010, 'en'], ['Timber', 'Pitbull', 2010, 'en'], ['Whatcha Say', 'Jason Derulo', 2000, 'en'], ['Talk Dirty', 'Jason Derulo', 2010, 'en'],
    ['TiK ToK', 'Kesha', 2000, 'en'],

    // ---- 2010er und 2020er ----
    ['Just the Way You Are', 'Bruno Mars', 2010, 'en'], ['Grenade', 'Bruno Mars', 2010, 'en'], ['Locked Out of Heaven', 'Bruno Mars', 2010, 'en'],
    ['Uptown Funk', 'Mark Ronson', 2010, 'en'], ['24K Magic', 'Bruno Mars', 2010, 'en'], ["That's What I Like", 'Bruno Mars', 2010, 'en'], ['When I Was Your Man', 'Bruno Mars', 2010, 'en'],
    ['This Love', 'Maroon 5', 2000, 'en'], ['Moves like Jagger', 'Maroon 5', 2010, 'en'], ['Sugar', 'Maroon 5', 2010, 'en'], ['Payphone', 'Maroon 5', 2010, 'en'],
    ['Girls Like You', 'Maroon 5', 2010, 'en'], ['Memories', 'Maroon 5', 2010, 'en'], ['Counting Stars', 'OneRepublic', 2010, 'en'], ['Apologize', 'OneRepublic', 2000, 'en'],
    ['Hey, Soul Sister', 'Train', 2000, 'en'], ['Somebody That I Used to Know', 'Gotye', 2010, 'en'], ['We Are Young', 'fun.', 2010, 'en'], ['Royals', 'Lorde', 2010, 'en'],
    ['Radioactive', 'Imagine Dragons', 2010, 'en'], ['Demons', 'Imagine Dragons', 2010, 'en'], ['Thunder', 'Imagine Dragons', 2010, 'en'], ['Believer', 'Imagine Dragons', 2010, 'en'],
    ["It's Time", 'Imagine Dragons', 2010, 'en'], ['Lonely Boy', 'The Black Keys', 2010, 'en'], ['Kids', 'MGMT', 2000, 'en'], ['Electric Feel', 'MGMT', 2000, 'en'],
    ['Get Lucky', 'Daft Punk', 2010, 'en'], ['Harder, Better, Faster, Stronger', 'Daft Punk', 2000, 'en'], ['Happy', 'Pharrell Williams', 2010, 'en'],
    ['Wake Me Up', 'Avicii', 2010, 'en'], ['Levels', 'Avicii', 2010, 'en'], ['Hey Brother', 'Avicii', 2010, 'en'], ['This Is What You Came For', 'Calvin Harris', 2010, 'en'],
    ['Summer', 'Calvin Harris', 2010, 'en'], ['Feel So Close', 'Calvin Harris', 2010, 'en'], ["Don't You Worry Child", 'Swedish House Mafia', 2010, 'en'], ['Clarity', 'Zedd', 2010, 'en'],
    ['Animals', 'Martin Garrix', 2010, 'en'], ['Firestone', 'Kygo', 2010, 'en'], ['Rather Be', 'Clean Bandit', 2010, 'en'], ['Rockabye', 'Clean Bandit', 2010, 'en'],
    ['Feel the Love', 'Rudimental', 2010, 'en'], ['Latch', 'Disclosure', 2010, 'en'], ['Stay with Me', 'Sam Smith', 2010, 'en'], ['Take Me to Church', 'Hozier', 2010, 'en'],
    ['Shape of You', 'Ed Sheeran', 2010, 'en'], ['Thinking Out Loud', 'Ed Sheeran', 2010, 'en'], ['Perfect', 'Ed Sheeran', 2010, 'en'], ['The A Team', 'Ed Sheeran', 2010, 'en'],
    ['Sing', 'Ed Sheeran', 2010, 'en'], ['Castle on the Hill', 'Ed Sheeran', 2010, 'en'], ['Bad Habits', 'Ed Sheeran', 2020, 'en'],
    ['Rolling in the Deep', 'Adele', 2010, 'en'], ['Someone like You', 'Adele', 2010, 'en'], ['Hello', 'Adele', 2010, 'en'], ['Set Fire to the Rain', 'Adele', 2010, 'en'],
    ['Skyfall', 'Adele', 2010, 'en'], ['Shake It Off', 'Taylor Swift', 2010, 'en'], ['Blank Space', 'Taylor Swift', 2010, 'en'], ['Love Story', 'Taylor Swift', 2000, 'en'],
    ['Bad Blood', 'Taylor Swift', 2010, 'en'], ['You Belong with Me', 'Taylor Swift', 2000, 'en'], ['Anti-Hero', 'Taylor Swift', 2020, 'en'], ['Cruel Summer', 'Taylor Swift', 2010, 'en'],
    ['Baby', 'Justin Bieber', 2010, 'en'], ['Sorry', 'Justin Bieber', 2010, 'en'], ['Love Yourself', 'Justin Bieber', 2010, 'en'], ['Peaches', 'Justin Bieber', 2020, 'en'],
    ['Problem', 'Ariana Grande', 2010, 'en'], ['7 rings', 'Ariana Grande', 2010, 'en'], ['thank u, next', 'Ariana Grande', 2010, 'en'], ['Into You', 'Ariana Grande', 2010, 'en'],
    ['Stitches', 'Shawn Mendes', 2010, 'en'], ['Treat You Better', 'Shawn Mendes', 2010, 'en'], ['Come & Get It', 'Selena Gomez', 2010, 'en'], ['Lose You to Love Me', 'Selena Gomez', 2010, 'en'],
    ['Attention', 'Charlie Puth', 2010, 'en'], ['See You Again', 'Wiz Khalifa', 2010, 'en'], ['Chandelier', 'Sia', 2010, 'en'], ['Cheap Thrills', 'Sia', 2010, 'en'],
    ['All About That Bass', 'Meghan Trainor', 2010, 'en'], ['Stressed Out', 'twenty one pilots', 2010, 'en'], ['New Rules', 'Dua Lipa', 2010, 'en'], ["Don't Start Now", 'Dua Lipa', 2010, 'en'],
    ['Levitating', 'Dua Lipa', 2020, 'en'], ['bad guy', 'Billie Eilish', 2010, 'en'], ['Ocean Eyes', 'Billie Eilish', 2010, 'en'], ['Happier Than Ever', 'Billie Eilish', 2020, 'en'],
    ['Blinding Lights', 'The Weeknd', 2010, 'en'], ["Can't Feel My Face", 'The Weeknd', 2010, 'en'], ['Starboy', 'The Weeknd', 2010, 'en'], ['Save Your Tears', 'The Weeknd', 2020, 'en'],
    ['Watermelon Sugar', 'Harry Styles', 2010, 'en'], ['As It Was', 'Harry Styles', 2020, 'en'], ['Adore You', 'Harry Styles', 2010, 'en'], ['Sign of the Times', 'Harry Styles', 2010, 'en'],
    ['Circles', 'Post Malone', 2010, 'en'], ['Sunflower', 'Post Malone', 2010, 'en'], ['rockstar', 'Post Malone', 2010, 'en'], ['Good as Hell', 'Lizzo', 2010, 'en'], ['About Damn Time', 'Lizzo', 2020, 'en'],
    ['Truth Hurts', 'Lizzo', 2010, 'en'], ['Someone You Loved', 'Lewis Capaldi', 2010, 'en'], ['Before You Go', 'Lewis Capaldi', 2010, 'en'], ['drivers license', 'Olivia Rodrigo', 2020, 'en'],
    ['good 4 u', 'Olivia Rodrigo', 2020, 'en'], ['vampire', 'Olivia Rodrigo', 2020, 'en'], ['Wrecking Ball', 'Miley Cyrus', 2010, 'en'], ['Flowers', 'Miley Cyrus', 2020, 'en'],
    ['Party in the U.S.A.', 'Miley Cyrus', 2000, 'en'], ["We Can't Stop", 'Miley Cyrus', 2010, 'en'], ['Say So', 'Doja Cat', 2010, 'en'], ['Kiss Me More', 'Doja Cat', 2020, 'en'],
    ['Dance Monkey', 'Tones and I', 2010, 'en'], ['Beggin\'', 'Måneskin', 2010, 'en'], ['Zitti e buoni', 'Måneskin', 2020, 'en'], ['Heat Waves', 'Glass Animals', 2020, 'en'],
    ['Let Her Go', 'Passenger', 2010, 'en'], ['Havana', 'Camila Cabello', 2010, 'en'], ['Señorita', 'Shawn Mendes', 2010, 'en'], ['Despacito', 'Luis Fonsi', 2010, 'en'],
    ['Gasolina', 'Daddy Yankee', 2000, 'en'], ['Jenny from the Block', 'Jennifer Lopez', 2000, 'en'], ['On the Floor', 'Jennifer Lopez', 2010, 'en'], ["Let's Get Loud", 'Jennifer Lopez', 1990, 'en'],
    ['Gangnam Style', 'PSY', 2010, 'en'], ["Can't Hold Us", 'Macklemore & Ryan Lewis', 2010, 'en'], ['Thrift Shop', 'Macklemore & Ryan Lewis', 2010, 'en'],
    ['Call Me Maybe', 'Carly Rae Jepsen', 2010, 'en'], ['Blurred Lines', 'Robin Thicke', 2010, 'en'], ['I Like It', 'Cardi B', 2010, 'en'], ['Old Town Road', 'Lil Nas X', 2010, 'en'],
    ['Hotline Bling', 'Drake', 2010, 'en'], ['One Dance', 'Drake', 2010, 'en'], ["God's Plan", 'Drake', 2010, 'en'], ['Lights', 'Ellie Goulding', 2010, 'en'], ['Burn', 'Ellie Goulding', 2010, 'en'],
    ['Love Me like You Do', 'Ellie Goulding', 2010, 'en'], ['Summertime Sadness', 'Lana Del Rey', 2010, 'en'], ['Video Games', 'Lana Del Rey', 2010, 'en'],
    ['Dog Days Are Over', 'Florence + The Machine', 2000, 'en'], ['I Will Wait', 'Mumford & Sons', 2010, 'en'], ['Little Lion Man', 'Mumford & Sons', 2000, 'en'],
    ['Little Talks', 'Of Monsters and Men', 2010, 'en'], ['Ho Hey', 'The Lumineers', 2010, 'en'], ['Pompeii', 'Bastille', 2010, 'en'], ['Pumped Up Kicks', 'Foster the People', 2010, 'en'],
    ['I Took a Pill in Ibiza', 'Mike Posner', 2010, 'en'], ['7 Years', 'Lukas Graham', 2010, 'en'], ['Easy Love', 'Sigala', 2010, 'en'], ['Fast Car', 'Jonas Blue', 2010, 'en'],
    ['Sugar', 'Robin Schulz', 2010, 'en'], ['Prayer in C', 'Lilly Wood & The Prick', 2010, 'en'], ["Ain't Nobody (Loves Me Better)", 'Felix Jaehn', 2010, 'en'],
    ['Are You with Me', 'Lost Frequencies', 2010, 'en'], ['Faded', 'Alan Walker', 2010, 'en'], ['This Girl', 'Kungs', 2010, 'en'], ['Lean On', 'Major Lazer', 2010, 'en'],
    ['Turn Down for What', 'DJ Snake', 2010, 'en'], ['Let Me Love You', 'DJ Snake', 2010, 'en'], ["You Don't Know Me", 'Jax Jones', 2010, 'en'], ['Head & Heart', 'Joel Corry', 2020, 'en'],
    ['Easy on Me', 'Adele', 2020, 'en'], ['Unholy', 'Sam Smith', 2020, 'en'], ['Flowers', 'Miley Cyrus', 2020, 'en'], ['Cold Heart', 'Elton John', 2020, 'en'],

    // ---- Deutsch: Klassiker und Neue Deutsche Welle ----
    ['99 Luftballons', 'Nena', 1980, 'de'], ['Nur geträumt', 'Nena', 1980, 'de'], ['Irgendwie, irgendwo, irgendwann', 'Nena', 1980, 'de'],
    ['Rock Me Amadeus', 'Falco', 1980, 'de'], ['Der Kommissar', 'Falco', 1980, 'de'], ['Jeanny', 'Falco', 1980, 'de'], ['Vienna Calling', 'Falco', 1980, 'de'],
    ['Über sieben Brücken musst du gehn', 'Peter Maffay', 1980, 'de'], ['Männer', 'Herbert Grönemeyer', 1980, 'de'], ['Bochum', 'Herbert Grönemeyer', 1980, 'de'],
    ['Mensch', 'Herbert Grönemeyer', 2000, 'de'], ['Flugzeuge im Bauch', 'Herbert Grönemeyer', 1980, 'de'], ['Du hast den Farbfilm vergessen', 'Nina Hagen', 1970, 'de'],
    ['Da Da Da', 'Trio', 1980, 'de'], ['Major Tom (Völlig losgelöst)', 'Peter Schilling', 1980, 'de'], ['Blaue Augen', 'Ideal', 1980, 'de'],
    ['Hurra, hurra, die Schule brennt', 'Extrabreit', 1980, 'de'], ['Skandal im Sperrbezirk', 'Spider Murphy Gang', 1980, 'de'], ["Ohne dich (schlaf' ich heut' Nacht nicht ein)", 'Münchener Freiheit', 1980, 'de'],
    ["You're My Heart, You're My Soul", 'Modern Talking', 1980, 'en'], ['Brother Louie', 'Modern Talking', 1980, 'en'], ['Cheri, Cheri Lady', 'Modern Talking', 1980, 'en'],
    ['Maria Magdalena', 'Sandra', 1980, 'en'], ['Big in Japan', 'Alphaville', 1980, 'en'], ['Forever Young', 'Alphaville', 1980, 'en'], ['Das Model', 'Kraftwerk', 1970, 'de'],
    ['Cello', 'Udo Lindenberg', 1980, 'de'], ['Sonderzug nach Pankow', 'Udo Lindenberg', 1980, 'de'], ['Aber bitte mit Sahne', 'Udo Jürgens', 1970, 'de'],
    ['Merci, Chérie', 'Udo Jürgens', 1960, 'de'], ['Ein Bett im Kornfeld', 'Jürgen Drews', 1970, 'de'], ['Verlieben, verloren, vergessen, verzeih\'n', 'Wolfgang Petry', 1990, 'de'],
    ['Wahnsinn', 'Wolfgang Petry', 1990, 'de'], ['Santa Maria', 'Roland Kaiser', 1980, 'de'], ['Ein Stern (...der deinen Namen trägt)', 'DJ Ötzi & Nik P.', 2000, 'de'],
    ['Hey Baby', 'DJ Ötzi', 2000, 'de'], ["L'amour toujours", 'Gigi D\'Agostino', 2000, 'en'], ['Das geht ab (Wir feiern die ganze Nacht)', 'Die Atzen', 2010, 'de'],
    ['How Much Is the Fish?', 'Scooter', 1990, 'en'], ['Hyper Hyper', 'Scooter', 1990, 'en'], ['Maria (I Like It Loud)', 'Scooter', 2000, 'en'], ['Fire', 'Scooter', 1990, 'en'],

    // ---- Deutsch: 90er, 2000er, aktuell ----
    ['Die da!?!', 'Die Fantastischen Vier', 1990, 'de'], ['Populär', 'Die Fantastischen Vier', 1990, 'de'], ['Troy', 'Die Fantastischen Vier', 1990, 'de'],
    ['MfG', 'Die Fantastischen Vier', 1990, 'de'], ['Hier kommt Alex', 'Die Toten Hosen', 1980, 'de'], ['Tage wie diese', 'Die Toten Hosen', 2010, 'de'],
    ['Bonnie & Clyde', 'Die Toten Hosen', 1990, 'de'], ['Alles aus Liebe', 'Die Toten Hosen', 1990, 'de'], ['Schrei nach Liebe', 'Die Ärzte', 1990, 'de'],
    ['Männer sind Schweine', 'Die Ärzte', 1990, 'de'], ['Junge', 'Die Ärzte', 2000, 'de'], ['Zu spät', 'Die Ärzte', 1990, 'de'], ['Westerland', 'Die Ärzte', 1990, 'de'],
    ['Küssen verboten', 'Die Prinzen', 1990, 'de'], ['Alles nur geklaut', 'Die Prinzen', 1990, 'de'], ['Millionär', 'Die Prinzen', 1990, 'de'], ['Verdammt lang her', 'BAP', 1980, 'de'],
    ['Du hast', 'Rammstein', 1990, 'de'], ['Sonne', 'Rammstein', 2000, 'de'], ['Engel', 'Rammstein', 1990, 'de'], ['Ich will', 'Rammstein', 2000, 'de'], ['Mein Herz brennt', 'Rammstein', 2000, 'de'],
    ['Amerika', 'Rammstein', 2000, 'de'], ['Liebe ist alles', 'Rosenstolz', 2000, 'de'], ['Abenteuerland', 'PUR', 1990, 'de'], ['Jein', 'Fettes Brot', 1990, 'de'],
    ['Denkmal', 'Wir sind Helden', 2000, 'de'], ['Müssen nur wollen', 'Wir sind Helden', 2000, 'de'], ['Gekommen um zu bleiben', 'Wir sind Helden', 2000, 'de'],
    ['54, 74, 90, 2010', 'Sportfreunde Stiller', 2000, 'de'], ['Ein Kompliment', 'Sportfreunde Stiller', 2000, 'de'], ['Perfekte Welle', 'Juli', 2000, 'de'],
    ['Das Beste', 'Silbermond', 2000, 'de'], ['Symphonie', 'Silbermond', 2000, 'de'], ['Verschwende deine Zeit', 'Silbermond', 2000, 'de'], ['Durch den Monsun', 'Tokio Hotel', 2000, 'de'],
    ['Übers Ende der Welt', 'Tokio Hotel', 2000, 'de'], ['Dickes B', 'Seeed', 2000, 'de'], ['Ding', 'Seeed', 2000, 'de'], ['Aufstehn', 'Seeed', 2000, 'de'],
    ['Alles neu', 'Peter Fox', 2000, 'de'], ['Haus am See', 'Peter Fox', 2000, 'de'], ['Hamma!', 'Culcha Candela', 2000, 'de'], ['Hungriges Herz', 'MIA.', 2000, 'de'],
    ['Halt dich an mir fest', 'Revolverheld', 2000, 'de'], ['Wie soll ein Mensch das ertragen', 'Philipp Poisel', 2010, 'de'], ['Gewinner', 'Clueso', 2000, 'de'],
    ['Easy', 'Cro', 2010, 'de'], ['Traum', 'Cro', 2010, 'de'], ['Hinterland', 'Casper', 2010, 'de'], ['Lila Wolken', 'Marteria', 2010, 'de'],
    ['Ich will nicht nach Berlin', 'Kraftklub', 2010, 'de'], ['Schönste Zeit', 'Bosse', 2010, 'de'], ['Pocahontas', 'AnnenMayKantereit', 2010, 'de'],
    ['Auf uns', 'Andreas Bourani', 2010, 'de'], ['Atemlos durch die Nacht', 'Helene Fischer', 2010, 'de'], ['Phänomen', 'Helene Fischer', 2010, 'de'],
    ['Du lässt mich sterben', 'Helene Fischer', 2010, 'de'], ['Au revoir', 'Mark Forster', 2010, 'de'], ['Chöre', 'Mark Forster', 2010, 'de'], ['Flash mich', 'Mark Forster', 2010, 'de'],
    ['Vincent', 'Sarah Connor', 2000, 'de'], ['Wie schön du bist', 'Sarah Connor', 2010, 'de'], ['Satellite', 'Lena', 2010, 'de'], ['80 Millionen', 'Max Giesinger', 2010, 'de'],
    ['Nur noch kurz die Welt retten', 'Tim Bendzko', 2010, 'de'], ['Lieblingsmensch', 'Namika', 2010, 'de'], ['Sofia', 'Álvaro Soler', 2010, 'en'], ['El Mismo Sol', 'Álvaro Soler', 2010, 'en'],
    ['Leiser', 'LEA', 2010, 'de'], ['Zieh die Schuh aus', 'Roger Cicero', 2000, 'de'], ['Dieser Weg', 'Xavier Naidoo', 2000, 'de'], ['Was wir alleine nicht schaffen', 'Xavier Naidoo', 2000, 'de'],
    ['Roller', 'Apache 207', 2020, 'de'], ['Prinzessin', 'Capital Bra', 2010, 'de'], ['Astronaut', 'Sido', 2010, 'de'],
];

// ---- Schwerpunkt: Party-Pop um 2010 (wird im Spiel häufiger gezogen, siehe CORE_SHARE in engine.js) ----
const by = (artist, decade, ...titles) => titles.map(title => [title, artist, decade, 'en']);
const de = (artist, decade, ...titles) => titles.map(title => [title, artist, decade, 'de']);

const P = [
    ...by('Katy Perry', 2010, 'Last Friday Night (T.G.I.F.)', 'E.T.', 'Hot n Cold', 'Part of Me', 'Wide Awake', 'The One That Got Away', 'Waking Up in Vegas',
        'Birthday', 'This Is How We Do', 'Chained to the Rhythm', 'Swish Swish', 'Never Really Over', 'Daisies', 'Ur So Gay', 'Thinking of You'),
    ...by('Rihanna', 2010, 'S&M', "What's My Name?", 'Where Have You Been', 'Disturbia', 'Take a Bow', 'SOS', 'Pon de Replay', 'Shut Up and Drive', 'Man Down',
        'Stay', 'California King Bed', 'Love the Way You Lie (Part II)', 'Russian Roulette', 'Hard', 'Cheers (Drink to That)', 'Bitch Better Have My Money',
        'Needed Me', 'Kiss It Better', 'Rehab', 'Pour It Up', 'You Da One', 'Cheers (Drink To That)', 'Unfaithful', 'Te Amo', 'Wild Thoughts'),
    ...by('Usher', 2010, "DJ Got Us Fallin' in Love", 'Scream', 'More', 'Without You', 'U Remind Me', 'U Got It Bad', 'Love in This Club', 'Caught Up',
        'Confessions Part II', 'Climax', 'Good Kisser', 'Nice & Slow', 'Trading Places', 'Lil Freak', "Hey Daddy (Daddy's Home)", 'Moving Mountains',
        'There Goes My Baby', 'Bad Girl', 'Papers', 'Yeah!', 'OMG', 'Burn', 'Confessions', 'My Boo'),
    ...by('Macklemore & Ryan Lewis', 2010, 'Same Love', 'Downtown', 'Wings', 'And We Danced', 'Glorious', 'Good Old Days', 'Dance Off', 'White Walls',
        "Can't Hold Us", 'Thrift Shop'),
    ...by('The Black Eyed Peas', 2010, 'The Time (Dirty Bit)', "Just Can't Get Enough", 'Pump It', 'Imma Be', 'Meet Me Halfway', 'Shut Up', "Don't Stop the Party",
        'Rock That Body', 'Hey Mama', "Don't Lie", 'Bebot', 'Where Is the Love?', 'I Gotta Feeling', 'Boom Boom Pow', "Let's Get It Started", 'My Humps'),
    ...by('Pitbull', 2010, 'International Love', 'Hotel Room Service', 'I Know You Want Me (Calle Ocho)', 'Rain Over Me', 'Fireball', 'Feel This Moment',
        'Back in Time', 'We Are One (Ole Ola)', "Don't Stop the Party", 'Time of Our Lives', 'Greenlight', 'Hey Baby (Drop It to the Floor)', 'Culo',
        'Wild Wild Love', 'Give Me Everything', 'Timber', 'Options', 'Bon, Bon'),
    ...by('Flo Rida', 2010, 'Whistle', 'Wild Ones', 'I Cry', 'Sugar', 'My House', "Club Can't Handle Me", 'Good Feeling', 'Right Round', 'Low', 'Elevator',
        'In the Ayer', 'Turn Around (5, 4, 3, 2, 1)', 'How I Feel', 'GDFR'),
    ...by('LMFAO', 2010, 'Party Rock Anthem', 'Sexy and I Know It', 'Sorry for Party Rocking', 'Shots', 'Champagne Showers', 'Yes'),
    ...by('Lady Gaga', 2010, 'Alejandro', 'Telephone', 'Judas', 'The Edge of Glory', 'LoveGame', 'Applause', 'You and I', 'Marry the Night', 'Do What U Want', 'G.U.Y.',
        'Million Reasons', 'Perfect Illusion', 'Stupid Love', 'Just Dance', 'Poker Face', 'Bad Romance', 'Paparazzi', 'Born This Way', 'Shallow', 'Rain on Me'),
    ...by('Britney Spears', 2010, 'Hold It Against Me', 'Till the World Ends', 'I Wanna Go', '3', 'If U Seek Amy', 'Piece of Me', 'Gimme More', 'Circus', 'Radar',
        'Everytime', 'Stronger', 'Me Against the Music', 'Lucky', 'Overprotected', 'Criminal', 'Work B**ch', 'Toxic', 'Womanizer', 'Slave 4 U'),
    ...by('Taio Cruz', 2010, 'Break Your Heart', 'Hangover', 'Higher', 'Telling the World', 'Falling in Love', 'Dynamite'),
    ...by('Jason Derulo', 2010, 'In My Head', "Ridin' Solo", "Don't Wanna Go Home", 'The Other Side', 'Wiggle', 'Trumpets', 'Marry Me', 'It Girl', 'Breathing', 'Swalla',
        'Whatcha Say', 'Talk Dirty', 'Want to Want Me'),
    ...by('Kesha', 2010, 'Your Love Is My Drug', 'We R Who We R', 'Die Young', 'Blow', 'Take It Off', 'Blah Blah Blah', 'Animal', 'Cannibal', 'Praying', 'TiK ToK'),
    ...by('Nicki Minaj', 2010, 'Super Bass', 'Starships', 'Anaconda', 'Pound the Alarm', 'Va Va Voom', 'Beez in the Trap', 'Moment 4 Life', "Roman's Revenge",
        'Pills N Potions', 'The Night Is Still Young', 'Only', 'Your Love', 'Right Thru Me'),
    ...by('Jessie J', 2010, 'Price Tag', 'Domino', 'Do It Like a Dude', 'Who You Are', 'Flashlight', 'Masterpiece', "Nobody's Perfect", 'Bang Bang', 'Burnin\' Up'),
    ...by('David Guetta', 2010, 'Sexy Chick', "Who's That Chick?", 'Turn Me On', 'Without You', 'Little Bad Girl', 'She Wolf (Falling to Pieces)', 'Shot Me Down', 'Bad',
        'Dangerous', 'Play Hard', 'Lovers on the Sun', 'Love Is Gone', 'Gettin\' Over You', 'Titanium', 'Memories', 'When Love Takes Over', 'Hey Mama'),
    ...by('Calvin Harris', 2010, 'I Need Your Love', 'Sweet Nothing', 'Bounce', "Let's Go", 'Thinking About You', 'Blame', 'How Deep Is Your Love', 'Slide', 'Feels',
        'Promises', 'Outside', 'Drinking from the Bottle', 'Under Control', 'This Is What You Came For', 'Summer', 'Feel So Close', 'One Kiss'),
    ...by('Avicii', 2010, 'Silhouettes', 'Addicted to You', 'The Nights', 'Waiting for Love', 'Broken Arrows', 'You Make Me', 'Lonely Together', 'Wake Me Up', 'Levels', 'Hey Brother'),
    ...by('Swedish House Mafia', 2010, 'One', 'Save the World', 'Antidote', 'Miami 2 Ibiza', "Don't You Worry Child"),
    ...by('P!nk', 2010, 'Blow Me (One Last Kiss)', 'Try', 'True Love', 'Funhouse', 'Sober', 'U + Ur Hand', 'Who Knew', 'Trouble', 'Stupid Girls', 'Perfect', 'What About Us',
        'Get the Party Started', 'So What', 'Raise Your Glass', 'Just Give Me a Reason', 'Just Like a Pill'),
    ...by('Taylor Swift', 2010, '22', 'I Knew You Were Trouble', 'Mean', 'Mine', 'Style', 'Out of the Woods', 'Wildest Dreams', 'Fifteen', 'Fearless', 'Back to December',
        'Red', 'Look What You Made Me Do', '...Ready for It?', 'Willow', 'Lover', 'ME!', 'Karma', 'Shake It Off', 'Blank Space', 'Love Story', 'Bad Blood',
        'We Are Never Ever Getting Back Together'),
    ...by('Bruno Mars', 2010, 'Marry You', 'The Lazy Song', 'Treasure', 'Gorilla', 'Runaway Baby', 'Count on Me', 'Talking to the Moon', 'Versace on the Floor',
        'Just the Way You Are', 'Grenade', 'Locked Out of Heaven', '24K Magic', "That's What I Like", 'When I Was Your Man'),
    ...by('Maroon 5', 2010, 'One More Night', 'Misery', 'Daylight', 'Animals', "Don't Wanna Know", 'She Will Be Loved', 'Makes Me Wonder', 'Harder to Breathe',
        'Won\'t Go Home Without You', 'Maps', 'Cold', 'Moves like Jagger', 'Sugar', 'Payphone', 'Girls Like You', 'Memories'),
    ...by('Kelly Clarkson', 2010, 'Mr. Know It All', 'Catch My Breath', 'Heartbeat Song', 'Miss Independent', 'Behind These Hazel Eyes', 'My Life Would Suck Without You',
        'Breakaway', 'Never Again', 'Piece by Piece', 'Since U Been Gone', 'Because of You'),
    ...by('Carly Rae Jepsen', 2010, 'I Really Like You', 'Run Away with Me', 'Cut to the Feeling', 'Call Me Maybe'),
    ...by('Owl City', 2010, 'Fireflies', 'Good Time', 'Vanilla Twilight'),
    ...by('Cobra Starship', 2000, 'Good Girls Go Bad', 'You Make Me Feel...', 'Hot Mess'),
    ...by('Hot Chelle Rae', 2010, 'Tonight Tonight', 'I Like It Like That'),
    ...by('Far East Movement', 2010, 'Like a G6', 'Rocketeer'),
    ...by('Cher Lloyd', 2010, 'Want U Back', 'Swagger Jagger', 'With Ur Love'),
    ...by('Rita Ora', 2010, 'R.I.P.', 'How We Do (Party)', 'Shine Ya Light', 'Poison', 'Anywhere', 'Your Song', 'Let You Love Me'),
    ...by('Little Mix', 2010, 'Wings', 'Black Magic', 'Salute', 'Move', 'Shout Out to My Ex', 'DNA', 'Touch', 'Power', 'Secret Love Song'),
    ...by('One Direction', 2010, 'What Makes You Beautiful', "Live While We're Young", 'Best Song Ever', 'Story of My Life', 'Little Things', 'Drag Me Down',
        'Midnight Memories', 'Kiss You', 'Steal My Girl', 'One Thing', 'Gotta Be You', 'Night Changes'),
    ...by('The Wanted', 2010, 'Glad You Came', 'Chasing the Sun', 'Lightning', 'All Time Low', 'Warzone', 'I Found You'),
    ...by('Enrique Iglesias', 2010, "Tonight (I'm Lovin' You)", 'I Like It', 'Dirty Dancer', 'Finally Found You', 'Bailando', 'Duele el Corazón', 'SUBEME LA RADIO',
        'Heartbeat', 'Escape', 'Be With You', 'Hero'),
    ...by('Shakira', 2010, 'Loca', "Can't Remember to Forget You", 'She Wolf', 'Gypsy', 'Chantaje', 'La La La (Brazil 2014)', 'Underneath Your Clothes', 'Waka Waka (This Time for Africa)'),
    ...by('Jennifer Lopez', 2010, 'Dance Again', 'Live It Up', 'Papi', "I'm Into You", "Goin' In", 'Booty', "Love Don't Cost a Thing", 'Waiting for Tonight',
        'If You Had My Love', "Ain't It Funny", 'Get Right', 'On the Floor'),
    ...by('Beyoncé', 2010, 'Run the World (Girls)', 'Love on Top', 'If I Were a Boy', 'Sweet Dreams', 'Diva', 'Best Thing I Never Had', 'End of Time', 'Partition',
        'Drunk in Love', 'Formation', 'Sorry', '7/11', 'Naughty Girl', 'Baby Boy', 'Déjà Vu', 'Check on It', 'XO', 'Break My Soul', 'Single Ladies (Put a Ring on It)', 'Halo'),
    ...by('Sean Paul', 2000, "She Doesn't Mind", 'Got 2 Luv U', 'Like Glue', 'Give It Up to Me', 'Press It Up', 'We Be Burnin\'', 'Temperature', 'Get Busy'),
    ...by('Akon', 2000, 'Right Now (Na Na Na)', 'Beautiful', 'Smack That', 'Lonely', 'I Wanna Love You', "Don't Matter", 'Sorry, Blame It on Me', 'Locked Up', 'Belly Dancer (Bananza)'),
    ...by('Timbaland', 2000, 'The Way I Are', 'Carry Out', 'Give It to Me', 'Throw It on Me', 'Morning After Dark', 'If We Ever Meet Again'),
    ...by('Kanye West', 2010, 'Gold Digger', 'Stronger', 'Power', 'All of the Lights', 'Good Life', 'Heartless', 'Love Lockdown', 'Jesus Walks', 'Touch the Sky',
        'Flashing Lights', 'Runaway', 'Monster'),
    ...by('JAY-Z', 2000, 'Empire State of Mind', 'Run This Town', '99 Problems', 'Dirt Off Your Shoulder', 'On to the Next One', 'Young Forever'),
    ...by('Eminem', 2010, 'Love the Way You Lie', 'Not Afraid', 'Berzerk', 'Beautiful', 'Mockingbird', 'Rap God', 'The Monster', 'Headlights'),
    ...by('B.o.B', 2010, 'Airplanes', 'Nothin\' on You', 'Magic', 'So Good', 'Strange Clouds', 'Both of Us'),
    ...by('Lil Wayne', 2000, 'Lollipop', 'A Milli', 'How to Love', '6 Foot 7 Foot', 'Mirror', 'She Will', 'Got Money', 'Drop the World', 'Mrs. Officer'),
    ...by('T-Pain', 2000, 'Buy U a Drank (Shawty Snappin\')', 'Bartender', "Can't Believe It", 'Church', 'Kiss Kiss', '5 O\'Clock', 'Take Your Shirt Off'),
    ...by('Ne-Yo', 2000, 'Closer', 'So Sick', 'Miss Independent', 'One in a Million', 'Sexy Love', 'Because of You', 'Let Me Love You (Until You Learn to Love Yourself)',
        'Beautiful Monster', 'Mad'),
    ...by('Chris Brown', 2010, 'Forever', 'Run It!', 'Look at Me Now', 'Turn Up the Music', "Don't Wake Me Up", 'Loyal', 'With You', 'Beautiful People',
        'Next to You', 'Fine China', 'Deuces', 'No Guidance', 'Under the Influence', 'Yeah 3x'),
    ...by('The Script', 2010, 'Hall of Fame', 'Breakeven', "The Man Who Can't Be Moved", 'For the First Time', 'Superheroes', 'Six Degrees of Separation', 'Nothing'),
    ...by('Avril Lavigne', 2010, 'What the Hell', "Here's to Never Growing Up", 'Smile', 'Wish You Were Here', 'Hot', 'My Happy Ending', "When You're Gone",
        'Complicated', 'Sk8er Boi', 'Girlfriend'),
    ...by('Selena Gomez & The Scene', 2010, 'Love You Like a Love Song', 'Who Says', 'Naturally', 'Hit the Lights', 'A Year Without Rain', 'Round & Round'),
    ...by('Selena Gomez', 2010, 'Good for You', 'Hands to Myself', 'The Heart Wants What It Wants', 'Same Old Love', 'Bad Liar', 'Wolves', 'Come & Get It', 'Lose You to Love Me'),
    ...by('Miley Cyrus', 2010, "Can't Be Tamed", 'See You Again', '7 Things', 'The Climb', 'Malibu', 'Midnight Sky', 'Slide Away', 'Wrecking Ball', "We Can't Stop"),
    ...by('Demi Lovato', 2010, 'Skyscraper', 'Give Your Heart a Break', 'Heart Attack', 'Cool for the Summer', 'Sorry Not Sorry', 'Confident', 'Neon Lights',
        'Here We Go Again', 'Stone Cold', 'Anyone', 'I Love Me', 'Really Don\'t Care', 'Made in the USA'),
    ...by('Justin Bieber', 2010, 'One Time', 'Somebody to Love', 'Boyfriend', 'As Long as You Love Me', 'Beauty and a Beat', 'What Do You Mean?', 'Mistletoe', 'U Smile',
        'Never Say Never', 'Eenie Meenie', 'Where Are Ü Now', 'Company', 'Cold Water', "I'll Show You", 'Yummy', 'Intentions', 'Holy', 'Ghost', 'Baby', 'Sorry', 'Love Yourself'),
    ...by('Ellie Goulding', 2010, 'Anything Could Happen', 'Starry Eyed', 'Figure 8', 'Your Song', 'Explosions', 'Goodness Gracious', 'On My Mind', 'Close to Me', 'Hate Me',
        'Lights', 'Burn', 'Love Me like You Do'),
    ...by('MIKA', 2000, 'Grace Kelly', 'Relax, Take It Easy', 'Love Today', 'Lollipop', 'Happy Ending', 'Big Girl (You Are Beautiful)', 'We Are Golden', 'Underwater', 'Popular Song'),
    ...by('Olly Murs', 2010, 'Troublemaker', 'Dance with Me Tonight', 'Heart Skips a Beat', "Please Don't Let Me Go", 'Right Place Right Time', 'Thinking of Me', 'Dear Darling', 'Wrapped Up'),
    ...by('Cascada', 2000, 'Evacuate the Dancefloor', 'Everytime We Touch', 'Truly Madly Deeply', 'Pyromania', 'Miracle', 'Bad Boy', 'What Hurts the Most', 'Fever'),
    ...by('Alexandra Stan', 2010, 'Mr. Saxobeat', 'Lemonade', 'Get Back (ASAP)', 'Cherry Pop'),
    ...by('Inna', 2010, 'Hot', 'Amazing', 'Sun Is Up', 'Endless', 'Un Momento', 'More Than Friends', 'Diggy Down', 'Yalla', 'Good Time', 'Rendez Vous'),
    ...by('Edward Maya', 2010, 'Stereo Love'), ...by('Akcent', 2000, "That's My Name", 'Kylie', 'Stay with Me', 'Jokero'),
    ...by('Basshunter', 2000, 'All I Ever Wanted', "Now You're Gone", 'Boten Anna', 'I Miss You', 'DotA', 'Every Morning'),
    ...by('R.I.O.', 2010, 'Shine On', 'When the Sun Comes Down', 'Like I Love You', 'Party Shaker', 'Animal'),
    ...by('Loreen', 2010, 'Euphoria', 'Tattoo', 'We Got the Power'),
    ...by('Mr. Probz', 2010, 'Waves'), ...by('Conchita Wurst', 2010, 'Rise Like a Phoenix'), ...by('Emmelie de Forest', 2010, 'Only Teardrops'),
    ...by('Måns Zelmerlöw', 2010, 'Heroes'), ...by('Duncan Laurence', 2010, 'Arcade'), ...by('Alexander Rybak', 2000, 'Fairytale'),
    ...by('Jason Mraz', 2000, "I'm Yours", "I Won't Give Up", 'Lucky', 'Make It Mine'),
    ...by('Plain White T\'s', 2000, 'Hey There Delilah', 'Rhythm of Love'), ...by('Natasha Bedingfield', 2000, 'Pocketful of Sunshine', 'Unwritten', 'These Words'),
    ...by('Colbie Caillat', 2000, 'Bubbly', 'Brighter than the Sun', 'Try', 'I Do'),
    ...by('Leona Lewis', 2000, 'Bleeding Love', 'Run', 'Better in Time', 'Happy', 'Forgive Me'),
    ...by('Alexandra Burke', 2000, 'Hallelujah', 'Bad Boys', 'Broken Heels'), ...by('Duffy', 2000, 'Mercy', 'Warwick Avenue', 'Rain on Your Parade'),
    ...by('Cheryl', 2000, 'Fight for This Love', 'Promise This', 'Call My Name'),
    ...by('Girls Aloud', 2000, 'Sound of the Underground', 'The Promise', 'Biology', 'Something Kinda Ooooh', 'Love Machine', 'Sexy! No No No...'),
    ...by('Sugababes', 2000, 'Push the Button', 'About You Now', 'Freak like Me', 'Round Round', 'Overload', 'Hole in the Head', 'Too Lost in You'),
    ...by('Pussycat Dolls', 2000, "Don't Cha", 'Buttons', 'When I Grow Up', 'Stickwitu', 'Beep', 'I Hate This Part', 'Jai Ho! (You Are My Destiny)', 'Hush Hush'),
    ...by('Dizzee Rascal', 2010, 'Bonkers', 'Dance Wiv Me', 'Holiday', 'Sirens', 'Fix Up, Look Sharp', 'Dirtee Disco'),
    ...by('Tinie Tempah', 2010, 'Pass Out', 'Written in the Stars', 'Frisky', 'Miami 2 Ibiza', 'Wonderman', 'Trampoline', 'Children of the Sun', 'Not Letting Go'),
    ...by('Example', 2010, 'Changed the Way You Kiss Me', 'Kick Start', 'Stay Awake', 'Midnight Run', 'Natural Disaster', 'Say Nothing'),
    ...by('Labrinth', 2010, 'Earthquake', 'Beneath Your Beautiful', 'Jealous', 'Express Yourself', 'Last Time'),
    ...by('Professor Green', 2010, 'Read All About It', 'Jungle', 'Just Be Good to Green', 'Lullaby'),
    ...by('Rudimental', 2010, 'Not Giving In', 'Waiting All Night', 'Right Here', 'Feel the Love', 'Free', 'Bloodstream'),
    ...by('Jessie Ware', 2010, 'Wildest Moments', 'Say You Love Me'),
    ...by('JLS', 2010, 'Beat Again', 'Everybody in Love', 'Love You More', 'Eyes Wide Shut', "She Makes Me Wanna", "That's My Girl"),
    ...by('Pixie Lott', 2010, 'Mama Do (Uh Oh, Uh Oh)', 'Boys and Girls', 'Cry Me Out', 'Broken Arrow', 'Nasty', 'All About Tonight'),
    ...by('Capital Cities', 2010, 'Safe and Sound'), ...by('fun.', 2010, 'Some Nights', 'We Are Young'),
    ...by('Paramore', 2000, 'Misery Business', 'Still Into You', 'Ain\'t It Fun', 'Decode', 'The Only Exception'),
    ...by('Fall Out Boy', 2000, 'Sugar, We\'re Goin Down', 'Thnks fr th Mmrs', 'My Songs Know What You Did in the Dark (Light Em Up)', 'Immortals', 'Centuries', 'Uma Thurman'),
    ...by('Panic! At The Disco', 2010, 'I Write Sins Not Tragedies', 'High Hopes', "Don't Threaten Me with a Good Time", 'Hallelujah', 'Victorious'),
    ...by('The Ting Tings', 2000, "That's Not My Name", 'Shut Up and Let Me Go', 'Great DJ'), ...by('Kid Cudi', 2000, "Day 'n' Nite", 'Pursuit of Happiness'),
    ...by('Gym Class Heroes', 2000, 'Stereo Hearts', "Cupid's Chokehold", 'Clothes Off!!'), ...by('Wiz Khalifa', 2010, 'Black and Yellow', 'Roll Up', 'See You Again'),
    ...by('Dev', 2010, 'In the Dark', 'Bass Down Low'),
    ...by('Lenka', 2000, 'The Show', 'Trouble Is a Friend'), ...by('Lady Antebellum', 2010, 'Need You Now', 'Just a Kiss', 'American Honey'),
    ...by('OneRepublic', 2010, 'Counting Stars', 'Apologize', 'Secrets', 'Good Life', 'Stop and Stare', 'I Lived', 'If I Lose Myself', 'Love Runs Out'),
    ...by('Train', 2010, "Hey, Soul Sister", 'Drive By', 'Marry Me', 'Drops of Jupiter (Tell Me)', 'Save Me, San Francisco', 'Play That Song'),
    ...by('Kygo', 2010, 'Firestone', 'Stole the Show', 'It Ain\'t Me', 'Stargazing', 'Higher Love', 'Born to Be Yours'),
    ...by('Zedd', 2010, 'Clarity', 'Stay', 'Beautiful Now', 'The Middle', 'Spectrum', 'I Want You to Know', 'Find You', 'Break Free'),
    ...by('Martin Garrix', 2010, 'Animals', 'In the Name of Love', 'Scared to Be Lonely', 'Ocean', 'High on Life', 'Used to Love'),
    ...by('Clean Bandit', 2010, 'Rather Be', 'Rockabye', 'Symphony', 'Solo', 'Tears', 'Mama'), ...by('Disclosure', 2010, 'Latch', 'White Noise', 'Omen', 'You & Me'),
    ...by('Sam Smith', 2010, 'Stay with Me', 'Too Good at Goodbyes', 'Writing\'s on the Wall', 'Lay Me Down', 'I\'m Not the Only One', 'Money on My Mind'),
    ...by('Hozier', 2010, 'Take Me to Church', 'Work Song', 'Almost (Sweet Music)'), ...by('Passenger', 2010, 'Let Her Go', 'Holes', 'Scare Away the Dark'),
    ...by('Imagine Dragons', 2010, 'Radioactive', 'Demons', 'Thunder', 'Believer', "It's Time", 'On Top of the World', 'Whatever It Takes', 'Natural', 'Bad Liar', 'Enemy'),
    ...by('Ed Sheeran', 2010, 'Shape of You', 'Thinking Out Loud', 'Perfect', 'The A Team', 'Sing', 'Castle on the Hill', 'Bad Habits', 'Photograph', 'Lego House', 'Drunk', 'Don\'t', 'Shivers', 'Galway Girl'),
    ...by('Adele', 2010, 'Rolling in the Deep', 'Someone like You', 'Hello', 'Set Fire to the Rain', 'Skyfall', 'Rumour Has It', 'Turning Tables', 'Chasing Pavements', 'Make You Feel My Love', 'Easy on Me'),
    ...by('Mark Ronson', 2010, 'Uptown Funk', 'Valerie', 'Nothing Breaks like a Heart', 'Late Night Feelings'),
    ...by('Ariana Grande', 2010, 'Problem', '7 rings', 'thank u, next', 'Into You', 'Break Free', 'Bang Bang', 'One Last Time', 'Love Me Harder', 'Side to Side', 'Dangerous Woman', 'Focus', 'positions', 'Rain on Me'),
    ...by('Dua Lipa', 2010, 'New Rules', "Don't Start Now", 'Levitating', 'One Kiss', 'Physical', 'IDGAF', 'Hotter than Hell', 'Be the One', 'Houdini'),
    ...by('Sia', 2010, 'Chandelier', 'Cheap Thrills', 'Elastic Heart', 'Unstoppable', 'Titanium', 'The Greatest', 'Alive'),
    ...by('Justin Timberlake', 2000, 'SexyBack', 'Cry Me a River', 'Rock Your Body', "Can't Stop the Feeling!", 'Mirrors', 'Suit & Tie', "Love Never Felt So Good", 'My Love', 'What Goes Around... Comes Around', 'Señorita', 'Like I Love You', 'Summer Love'),
    ...by('Christina Aguilera', 2000, 'Genie in a Bottle', 'Dirrty', 'Beautiful', 'Fighter', 'Candyman', 'Ain\'t No Other Man', 'Hurt', 'Moves like Jagger', 'Your Body', 'Not Myself Tonight', 'Express'),
];

// Beliebte Interpreten aus der Zeit um 2010, deren ältere Einträge ebenfalls zum Schwerpunkt zählen
const CORE_ARTISTS = new Set([
    'Katy Perry', 'Rihanna', 'Usher', 'Macklemore & Ryan Lewis', 'The Black Eyed Peas', 'Pitbull', 'Flo Rida', 'LMFAO', 'Lady Gaga', 'Britney Spears', 'Taio Cruz',
    'Jason Derulo', 'Kesha', 'Nicki Minaj', 'Jessie J', 'David Guetta', 'Calvin Harris', 'Avicii', 'Swedish House Mafia', 'P!nk', 'Taylor Swift', 'Bruno Mars', 'Maroon 5',
    'Kelly Clarkson', 'Justin Bieber', 'Beyoncé', 'Shakira', 'Jennifer Lopez', 'Selena Gomez', 'Miley Cyrus', 'Demi Lovato', 'Ariana Grande', 'Dua Lipa', 'Sia',
    'Ellie Goulding', 'Mark Ronson', 'Ed Sheeran', 'Adele', 'OneRepublic', 'Train', 'Carly Rae Jepsen', 'PSY', 'Lorde', 'Imagine Dragons', 'Zedd', 'Martin Garrix', 'Kygo',
    'Clean Bandit', 'Justin Timberlake', 'Christina Aguilera', 'Nelly', '50 Cent', 'Sean Paul', 'Eminem', 'Flo Rida', 'Enrique Iglesias', 'Avril Lavigne', 'Chris Brown',
]);

// Deutscher Party-Pop und Hits um 2010
const G = [
    ...de('Deichkind', 2010, 'Remmidemmi (Yippie Yippie Yeah)', 'Bück dich hoch', 'Leider geil', "So 'ne Musik", 'Like mich am Arsch', 'Denken Sie groß'),
    ...de('Jan Delay', 2000, 'Oh Jonny', 'Klar', 'Large', 'Ahnma', 'Feuer', 'Wir Kinder vom Bahnhof Soul', 'Disko'),
    ...de('Frida Gold', 2010, 'Wovon sollen wir träumen', 'Liebe ist meine Rebellion', 'Zeig mir wie du tanzt', 'Alina'),
    ...de('Ich + Ich', 2000, 'Vom selben Stern', 'Stark', 'Pflaster', 'Du erinnerst mich an Liebe', 'Gute Reise'),
    ...de('Unheilig', 2010, 'Geboren um zu leben', 'Prinz', "Als wär's das erste Mal", 'Zeit zu gehen', 'Große Freiheit', 'Für immer'),
    ...de('Madsen', 2000, 'Du schreibst Geschichte', 'Die Perfektion', 'Vielleicht', 'Nachbeben'),
    ...de('Beatsteaks', 2000, 'Hello Joe', 'Let Me In', 'Hand in Hand', 'Milk & Honey'),
    ...de('Culcha Candela', 2000, 'Monsta', 'Schöne neue Welt', 'Eiskalt', 'Wenn der Mond', 'Hamma!', 'Powerfrau', 'Ey DJ'),
    ...de('LaFee', 2000, 'Prinzesschen', 'Heul doch', 'Ich bin', 'Mädchen'),
    ...de('Lena', 2010, 'Taken by a Stranger', 'Satellite', 'Mr. Arrow Key', 'Better News', 'Home'),
    ...de('Cro', 2010, 'Du', 'Bye Bye', 'Einmal um die Welt', 'Whatever', 'Traum', 'Easy', 'Bad Chick', 'Hi Kids'),
    ...de('Mark Forster', 2010, 'Bauch und Kopf', 'Wir sind groß', 'Sowieso', '194 Länder', 'Flash mich', 'Einmal', 'Au revoir', 'Chöre', 'Übermorgen'),
    ...de('Tim Bendzko', 2010, 'Wenn Worte meine Sprache wären', 'Keine Maschine', 'Am seidenen Faden', 'Nur noch kurz die Welt retten', 'Hoch', 'Programmiert'),
    ...de('Johannes Oerding', 2010, 'An guten Tagen', 'Kreise', 'Hundert Leben', 'Alles brennt', 'Stück vom Himmel'),
    ...de('Christina Stürmer', 2000, 'Ich lebe', 'Mama (Ana Ahabak)', 'Millionen Lichter', 'Engel fliegen einsam', 'Vorbei'),
    ...de('Sido', 2000, 'Mein Block', 'Straßenjunge', 'Bilder im Kopf', 'Astronaut', 'Hey du', 'Beweg dein Arsch'),
    ...de('Bushido', 2000, 'Für immer jung', 'Sonnenbank Flavour', 'Vergiss mich', 'Jackpot'),
    ...de('Marteria', 2010, 'Kids (2 Finger an den Kopf)', 'Welt der Wunder', 'Verstrahlt', 'Lila Wolken', 'OMG!', 'OMG!'),
    ...de('Casper', 2010, 'XOXO', 'Im Ascheregen', 'Michael X', 'Hinterland', 'So perfekt', 'Lang lebe der Tod'),
    ...de('Kraftklub', 2010, 'Songs für Liam', 'Eure Mädchen', 'Ich will nicht nach Berlin', 'Zu jung', 'Dein Lied', 'Schüsse in die Luft'),
    ...de('Revolverheld', 2000, 'Spinner', 'Lass uns gehen', "Ich lass für dich das Licht an", 'Halt dich an mir fest', 'Generation Rock', 'Keine Liebeslieder'),
    ...de('Silbermond', 2000, 'Irgendwas bleibt', 'Leichtes Gepäck', 'Das Beste', 'Symphonie', 'Krieger des Lichts', 'Zeit für Optimisten'),
    ...de('MIA.', 2000, 'Tanz der Moleküle', 'Hungriges Herz', 'Was es ist', 'Fallschirm', 'Wir sind jung'),
    ...de('Seeed', 2000, 'Augenbling', 'Music Monks', 'Ding', 'Aufstehn', 'Dickes B', 'Waterpumpee', 'Release Me', 'Molotov'),
    ...de('Peter Fox', 2000, 'Schwarz zu Blau', 'Stadtaffe', 'Zukunft Pink', 'Alles neu', 'Haus am See', 'Lok auf 2 Beinen', 'Dickes Ding'),
    ...de('Juli', 2000, 'Geile Zeit', 'Elektrisches Gefühl', 'Dieses Layout', 'Perfekte Welle', 'Warum', 'Regen und Meer'),
    ...de('Die Atzen', 2010, 'Das geht ab (Wir feiern die ganze Nacht)', 'Disco Pogo', 'Strobo Pop', 'Hey Mama', 'Es geht ab'),
    ...de('DJ Antoine', 2010, 'Welcome to St. Tropez', 'Ma Chérie', 'Holiday', 'Sweet Ride', "Sunshine"),
    ...de('Mickie Krause', 2000, 'Orange trägt nur die Müllabfuhr', 'Biste braun, kriegste Frauen', 'Schatzi schenk mir ein Foto', 'Reiß die Hütte ab'),
    ...de('Peter Wackel', 2000, 'Joana', 'Scheiß drauf', 'Verdammt ich lieb dich'), ...de('Josh.', 2010, 'Cordula Grün', 'Expresso & Tschianti', 'Wunderschön'),
    ...de('Lorenz Büffel', 2010, 'Johnny Däpp'), ...de('Gestört aber GeiL', 2010, 'Unter meiner Haut', 'Antiheld', 'Wohin willst du?'),
    ...de('Namika', 2010, 'Lieblingsmensch', 'Je ne parle pas français', 'Hellwach', 'Nie vergessen'), ...de('Sarah Connor', 2010, 'Wie schön du bist', 'Vincent', 'Bounce', 'From Sarah with Love'),
    ...de('Andreas Bourani', 2010, 'Auf uns', 'Hey', 'Nur in meinem Kopf', 'Eisberg', 'Astronaut'),
    ...de('Helene Fischer', 2010, 'Atemlos durch die Nacht', 'Phänomen', 'Du lässt mich sterben', 'Fehlerfrei', 'Herzbeben', 'Mit keinem andern', 'Die Reise'),
    ...de('Xavier Naidoo', 2000, 'Dieser Weg', 'Was wir alleine nicht schaffen', 'Ich kenne nichts', 'Seine Straßen', 'Bitte hör nicht auf zu träumen'),
    ...de('Clueso', 2010, 'Gewinner', 'Chicago', 'Neuanfang', 'Cello', 'Flugzeug'), ...de('Philipp Poisel', 2010, 'Wie soll ein Mensch das ertragen', 'Als gäb\'s kein Morgen mehr', 'Eiserner Steg'),
    ...de('Max Giesinger', 2010, '80 Millionen', 'Wenn sie tanzt', 'Roulette', 'Nur mit dir'), ...de('Lea', 2010, 'Leiser', 'Zu dir', 'Wenn du mich brauchst'),
    ...de('AnnenMayKantereit', 2010, 'Pocahontas', '3. Stock', 'Oft gefragt', 'Barfuß am Klavier'), ...de('Bosse', 2010, 'Schönste Zeit', 'Steine', 'Alles ist jetzt', '3 Millionen', 'Dein Hurra'),
    ...de('Apache 207', 2020, 'Roller', 'Wieso tust du dir das an?', 'Komet', 'Wetter', 'Bläulich'), ...de('Capital Bra', 2010, 'Prinzessin', 'Cherry Lady', 'Neymar', 'Berlin lebt', 'Ohne mein Team'),
];

// Titel, die die Apple-Suche beim Abgleich am 03.10.2026 nicht (oder nur als Cover/Live-Version) gefunden hat: werden gar nicht erst gezogen.
const NOT_AT_APPLE = new Set([
    "What's My Name? | Rihanna",
    "Wild Thoughts | Rihanna",
    "Without You | Usher",
    "And We Danced | Macklemore & Ryan Lewis",
    "Imma Be | The Black Eyed Peas",
    "Shut Up | The Black Eyed Peas",
    "You and I | Lady Gaga",
    "Work B**ch | Britney Spears",
    "Slave 4 U | Britney Spears",
    "Blah Blah Blah | Kesha",
    "Slide | Calvin Harris",
    "Feels | Calvin Harris",
    "U + Ur Hand | P!nk",
    "Stupid Girls | P!nk",
    "Perfect | P!nk",
    "Live While We're Young | One Direction",
    "Finally Found You | Enrique Iglesias",
    "Live It Up | Jennifer Lopez",
    "Sorry | Beyoncé",
    "Belly Dancer (Bananza) | Akon",
    "Look at Me Now | Chris Brown",
    "Loyal | Chris Brown",
    "For the First Time | The Script",
    "Smile | Avril Lavigne",
    "Wish You Were Here | Avril Lavigne",
    "Cold Water | Justin Bieber",
    "Trampoline | Tinie Tempah",
    "Children of the Sun | Tinie Tempah",
    "Kick Start | Example",
    "Jungle | Professor Green",
    "Lullaby | Professor Green",
    "Break Free | Zedd",
    "Moves like Jagger | Christina Aguilera",
    "Bück dich hoch | Deichkind",
    "So 'ne Musik | Deichkind",
    "Like mich am Arsch | Deichkind",
    "Oh Jonny | Jan Delay",
    "Ahnma | Jan Delay",
    "Wir Kinder vom Bahnhof Soul | Jan Delay",
    "Alina | Frida Gold",
    "Gute Reise | Ich + Ich",
    "Prinz | Unheilig",
    "Nachbeben | Madsen",
    "Wenn der Mond | Culcha Candela",
    "Powerfrau | Culcha Candela",
    "Mädchen | LaFee",
    "Bye Bye | Cro",
    "Stück vom Himmel | Johannes Oerding",
    "Beweg dein Arsch | Sido",
    "Sonnenbank Flavour | Bushido",
    "Jackpot | Bushido",
    "Dein Lied | Kraftklub",
    "Wir sind jung | MIA.",
    "Zukunft Pink | Peter Fox",
    "Dickes Ding | Peter Fox",
    "Dieses Layout | Juli",
    "Hey Mama | Die Atzen",
    "Es geht ab | Die Atzen",
    "Sweet Ride | DJ Antoine",
    "Sunshine | DJ Antoine",
    "Biste braun, kriegste Frauen | Mickie Krause",
    "Verdammt ich lieb dich | Peter Wackel",
    "Wunderschön | Josh.",
    "Antiheld | Gestört aber GeiL",
    "Nie vergessen | Namika",
    "Astronaut | Andreas Bourani",
    "Du lässt mich sterben | Helene Fischer",
    "Die Reise | Helene Fischer",
    "Cello | Clueso",
    "Flugzeug | Clueso",
    "Nur mit dir | Max Giesinger",
    "Wenn du mich brauchst | Lea",
    "Roller | Apache 207",
    "Wieso tust du dir das an? | Apache 207",
    "Wetter | Apache 207",
    "Prinzessin | Capital Bra",
    "Neymar | Capital Bra",
    "Ohne mein Team | Capital Bra",
    "Live Forever | Oasis",
    "Good Riddance (Time of Your Life) | Green Day",
    "Dr. Jones | Aqua",
    "Music Sounds Better with You | Stardust",
    "Creep | Radiohead",
    "Little Lion Man | Mumford & Sons",
    "Verdammt lang her | BAP",
]);

// Einträge: [Titel, Künstler, Jahrzehnt, Sprache]. Doppelte (gleicher Titel und Künstler) fallen heraus.
// "core" markiert den Schwerpunkt Party-Pop um 2010: neue Einträge (P, G) und ältere von beliebten Interpreten aus dieser Zeit.
export const CATALOG = (() => {
    const map = new Map();
    const add = ([title, artist, decade, lang], core) => {
        const id = `${title} | ${artist}`;
        const existing = map.get(id);
        if (existing) existing.core = existing.core || core;
        else if (!NOT_AT_APPLE.has(id)) map.set(id, { id, title, artist, decade, lang, core });
    };
    for (const e of P) add(e, true);
    for (const e of G) add(e, true);
    for (const e of L) add(e, e[2] >= 2000 && CORE_ARTISTS.has(e[1]));
    return [...map.values()];
})();
