// Songliste fürs Lieder-Raten: nur Titel, Künstler, Jahrzehnt und Sprache (de = deutsch, en = alle anderen).
// Die Audio-Ausschnitte werden zur Laufzeit über die iTunes-Suche geholt, hier liegt keine Musik.
// Findet die Suche einen Eintrag nicht, wird er in dieser Runde einfach übersprungen.

const L = [
    // ---- 60er und 70er ----
    ['Hey Jude', 'The Beatles', 1960, 'en'], ['Let It Be', 'The Beatles', 1970, 'en'], ['Yesterday', 'The Beatles', 1960, 'en'],
    ['Come Together', 'The Beatles', 1960, 'en'], ['Here Comes the Sun', 'The Beatles', 1960, 'en'], ['Twist and Shout', 'The Beatles', 1960, 'en'],
    ['Penny Lane', 'The Beatles', 1960, 'en'], ['Help!', 'The Beatles', 1960, 'en'],
    ['Satisfaction', 'The Rolling Stones', 1960, 'en'], ['Paint It Black', 'The Rolling Stones', 1960, 'en'], ['Angie', 'The Rolling Stones', 1970, 'en'],
    ['Start Me Up', 'The Rolling Stones', 1980, 'en'], ['Sympathy for the Devil', 'The Rolling Stones', 1960, 'en'],
    ['Bohemian Rhapsody', 'Queen', 1970, 'en'], ["Don't Stop Me Now", 'Queen', 1970, 'en'], ['We Will Rock You', 'Queen', 1970, 'en'],
    ['We Are the Champions', 'Queen', 1970, 'en'], ['Another One Bites the Dust', 'Queen', 1980, 'en'], ['Somebody to Love', 'Queen', 1970, 'en'],
    ['Under Pressure', 'Queen', 1980, 'en'], ['I Want to Break Free', 'Queen', 1980, 'en'], ['Radio Ga Ga', 'Queen', 1980, 'en'],
    ['Killer Queen', 'Queen', 1970, 'en'], ['A Kind of Magic', 'Queen', 1980, 'en'],
    ['Dancing Queen', 'ABBA', 1970, 'en'], ['Mamma Mia', 'ABBA', 1970, 'en'], ['Waterloo', 'ABBA', 1970, 'en'], ['Gimme! Gimme! Gimme!', 'ABBA', 1970, 'en'],
    ['Super Trouper', 'ABBA', 1980, 'en'], ['Take a Chance on Me', 'ABBA', 1970, 'en'], ['Money, Money, Money', 'ABBA', 1970, 'en'],
    ['The Winner Takes It All', 'ABBA', 1980, 'en'], ['Fernando', 'ABBA', 1970, 'en'], ['Voulez-Vous', 'ABBA', 1970, 'en'], ['Chiquitita', 'ABBA', 1970, 'en'],
    ["Stayin' Alive", 'Bee Gees', 1970, 'en'], ['Night Fever', 'Bee Gees', 1970, 'en'], ['How Deep Is Your Love', 'Bee Gees', 1970, 'en'],
    ['Rasputin', 'Boney M.', 1970, 'en'], ['Daddy Cool', 'Boney M.', 1970, 'en'], ['Rivers of Babylon', 'Boney M.', 1970, 'en'], ['Ma Baker', 'Boney M.', 1970, 'en'],
    ['Sunny', 'Boney M.', 1970, 'en'], ['Brown Girl in the Ring', 'Boney M.', 1970, 'en'],
    ['Rocket Man', 'Elton John', 1970, 'en'], ['Your Song', 'Elton John', 1970, 'en'], ['Tiny Dancer', 'Elton John', 1970, 'en'],
    ["I'm Still Standing", 'Elton John', 1980, 'en'], ["Don't Go Breaking My Heart", 'Elton John', 1970, 'en'], ['Crocodile Rock', 'Elton John', 1970, 'en'],
    ['Dreams', 'Fleetwood Mac', 1970, 'en'], ['Go Your Own Way', 'Fleetwood Mac', 1970, 'en'], ['Everywhere', 'Fleetwood Mac', 1980, 'en'],
    ['Hotel California', 'Eagles', 1970, 'en'], ['Take It Easy', 'Eagles', 1970, 'en'],
    ['Another Brick in the Wall', 'Pink Floyd', 1970, 'en'], ['Wish You Were Here', 'Pink Floyd', 1970, 'en'], ['Comfortably Numb', 'Pink Floyd', 1970, 'en'],
    ['Stairway to Heaven', 'Led Zeppelin', 1970, 'en'], ['Whole Lotta Love', 'Led Zeppelin', 1960, 'en'],
    ['Heroes', 'David Bowie', 1970, 'en'], ['Space Oddity', 'David Bowie', 1960, 'en'], ["Let's Dance", 'David Bowie', 1980, 'en'], ['Starman', 'David Bowie', 1970, 'en'],
    ["Da Ya Think I'm Sexy?", 'Rod Stewart', 1970, 'en'], ['Maggie May', 'Rod Stewart', 1970, 'en'], ['Sailing', 'Rod Stewart', 1970, 'en'],
    ['I Feel Love', 'Donna Summer', 1970, 'en'], ['Hot Stuff', 'Donna Summer', 1970, 'en'], ['Last Dance', 'Donna Summer', 1970, 'en'],
    ['I Will Survive', 'Gloria Gaynor', 1970, 'en'], ['Le Freak', 'Chic', 1970, 'en'], ['Good Times', 'Chic', 1970, 'en'],
    ['Y.M.C.A.', 'Village People', 1970, 'en'], ['In the Navy', 'Village People', 1970, 'en'], ['Macho Man', 'Village People', 1970, 'en'],
    ['Celebration', 'Kool & The Gang', 1980, 'en'], ['Get Down on It', 'Kool & The Gang', 1980, 'en'], ["Ladies' Night", 'Kool & The Gang', 1970, 'en'],
    ['September', 'Earth, Wind & Fire', 1970, 'en'], ['Boogie Wonderland', 'Earth, Wind & Fire', 1970, 'en'], ["Let's Groove", 'Earth, Wind & Fire', 1980, 'en'],
    ['Superstition', 'Stevie Wonder', 1970, 'en'], ['Sir Duke', 'Stevie Wonder', 1970, 'en'], ['I Just Called to Say I Love You', 'Stevie Wonder', 1980, 'en'],
    ["Isn't She Lovely", 'Stevie Wonder', 1970, 'en'], ["Let's Get It On", 'Marvin Gaye', 1970, 'en'], ['I Heard It Through the Grapevine', 'Marvin Gaye', 1960, 'en'],
    ['Respect', 'Aretha Franklin', 1960, 'en'], ['Proud Mary', 'Tina Turner', 1970, 'en'], ["What's Love Got to Do with It", 'Tina Turner', 1980, 'en'],
    ['The Best', 'Tina Turner', 1980, 'en'], ['The Logical Song', 'Supertramp', 1970, 'en'], ['Breakfast in America', 'Supertramp', 1970, 'en'],
    ['Ballroom Blitz', 'Sweet', 1970, 'en'], ['Merry Xmas Everybody', 'Slade', 1970, 'en'], ["Cum On Feel the Noize", 'Slade', 1970, 'en'],
    ['Living Next Door to Alice', 'Smokie', 1970, 'en'], ['Get It On', 'T. Rex', 1970, 'en'], ['Born to Be Wild', 'Steppenwolf', 1960, 'en'],
    ['Have You Ever Seen the Rain?', 'Creedence Clearwater Revival', 1970, 'en'], ['Bad Moon Rising', 'Creedence Clearwater Revival', 1960, 'en'],
    ['Smoke on the Water', 'Deep Purple', 1970, 'en'], ['Highway to Hell', 'AC/DC', 1970, 'en'], ['Back in Black', 'AC/DC', 1980, 'en'],
    ['You Shook Me All Night Long', 'AC/DC', 1980, 'en'], ['Thunderstruck', 'AC/DC', 1990, 'en'],
    ['The Sound of Silence', 'Simon & Garfunkel', 1960, 'en'], ['Mrs. Robinson', 'Simon & Garfunkel', 1960, 'en'],
    ["California Dreamin'", 'The Mamas & The Papas', 1960, 'en'], ['Good Vibrations', 'The Beach Boys', 1960, 'en'],
    ['What a Wonderful World', 'Louis Armstrong', 1960, 'en'], ['My Way', 'Frank Sinatra', 1960, 'en'], ['Fly Me to the Moon', 'Frank Sinatra', 1960, 'en'],
    ["Can't Help Falling in Love", 'Elvis Presley', 1960, 'en'], ['Jailhouse Rock', 'Elvis Presley', 1950, 'en'], ['Suspicious Minds', 'Elvis Presley', 1960, 'en'],
    ['No Woman, No Cry', 'Bob Marley & The Wailers', 1970, 'en'], ['Three Little Birds', 'Bob Marley & The Wailers', 1970, 'en'],
    ['Is This Love', 'Bob Marley & The Wailers', 1970, 'en'], ['Buffalo Soldier', 'Bob Marley & The Wailers', 1980, 'en'],
    ['Imagine', 'John Lennon', 1970, 'en'], ['Sweet Caroline', 'Neil Diamond', 1960, 'en'], ["You're the First, the Last, My Everything", 'Barry White', 1970, 'en'],
    ['Funkytown', 'Lipps Inc.', 1980, 'en'], ['You Sexy Thing', 'Hot Chocolate', 1970, 'en'], ['Mr. Blue Sky', 'Electric Light Orchestra', 1970, 'en'],
    ['Heart of Glass', 'Blondie', 1970, 'en'], ['Call Me', 'Blondie', 1980, 'en'], ['Roxanne', 'The Police', 1970, 'en'],
    ['Every Breath You Take', 'The Police', 1980, 'en'], ['Message in a Bottle', 'The Police', 1970, 'en'], ['Sultans of Swing', 'Dire Straits', 1970, 'en'],
    ['Money for Nothing', 'Dire Straits', 1980, 'en'], ['Black Magic Woman', 'Santana', 1970, 'en'], ["I Want You Back", 'The Jackson 5', 1970, 'en'],

    // ---- 80er ----
    ['Thriller', 'Michael Jackson', 1980, 'en'], ['Billie Jean', 'Michael Jackson', 1980, 'en'], ['Beat It', 'Michael Jackson', 1980, 'en'],
    ['Smooth Criminal', 'Michael Jackson', 1980, 'en'], ['Bad', 'Michael Jackson', 1980, 'en'], ['Man in the Mirror', 'Michael Jackson', 1980, 'en'],
    ["Don't Stop 'Til You Get Enough", 'Michael Jackson', 1970, 'en'], ['Black or White', 'Michael Jackson', 1990, 'en'],
    ['Like a Virgin', 'Madonna', 1980, 'en'], ['Material Girl', 'Madonna', 1980, 'en'], ['Like a Prayer', 'Madonna', 1980, 'en'],
    ['La Isla Bonita', 'Madonna', 1980, 'en'], ['Vogue', 'Madonna', 1990, 'en'], ['Holiday', 'Madonna', 1980, 'en'], ["Papa Don't Preach", 'Madonna', 1980, 'en'],
    ['Into the Groove', 'Madonna', 1980, 'en'], ['Hung Up', 'Madonna', 2000, 'en'],
    ['Purple Rain', 'Prince', 1980, 'en'], ['Kiss', 'Prince', 1980, 'en'], ['When Doves Cry', 'Prince', 1980, 'en'], ['1999', 'Prince', 1980, 'en'],
    ['I Wanna Dance with Somebody (Who Loves Me)', 'Whitney Houston', 1980, 'en'], ['I Will Always Love You', 'Whitney Houston', 1990, 'en'],
    ['How Will I Know', 'Whitney Houston', 1980, 'en'], ['Greatest Love of All', 'Whitney Houston', 1980, 'en'],
    ['Girls Just Want to Have Fun', 'Cyndi Lauper', 1980, 'en'], ['Time After Time', 'Cyndi Lauper', 1980, 'en'], ['True Colors', 'Cyndi Lauper', 1980, 'en'],
    ['Last Christmas', 'Wham!', 1980, 'en'], ['Wake Me Up Before You Go-Go', 'Wham!', 1980, 'en'], ['Club Tropicana', 'Wham!', 1980, 'en'],
    ['Careless Whisper', 'George Michael', 1980, 'en'], ['Faith', 'George Michael', 1980, 'en'], ['Freedom! \'90', 'George Michael', 1990, 'en'],
    ['Rio', 'Duran Duran', 1980, 'en'], ['Hungry Like the Wolf', 'Duran Duran', 1980, 'en'], ['Ordinary World', 'Duran Duran', 1990, 'en'],
    ['Take On Me', 'a-ha', 1980, 'en'], ['The Sun Always Shines on T.V.', 'a-ha', 1980, 'en'],
    ['Enjoy the Silence', 'Depeche Mode', 1990, 'en'], ['Personal Jesus', 'Depeche Mode', 1980, 'en'], ["Just Can't Get Enough", 'Depeche Mode', 1980, 'en'],
    ['Sweet Dreams (Are Made of This)', 'Eurythmics', 1980, 'en'], ['Here Comes the Rain Again', 'Eurythmics', 1980, 'en'],
    ['Karma Chameleon', 'Culture Club', 1980, 'en'], ['Do You Really Want to Hurt Me', 'Culture Club', 1980, 'en'],
    ["Livin' on a Prayer", 'Bon Jovi', 1980, 'en'], ['You Give Love a Bad Name', 'Bon Jovi', 1980, 'en'], ["It's My Life", 'Bon Jovi', 2000, 'en'],
    ['Always', 'Bon Jovi', 1990, 'en'], ['Bad Medicine', 'Bon Jovi', 1980, 'en'],
    ["Sweet Child o' Mine", "Guns N' Roses", 1980, 'en'], ['Welcome to the Jungle', "Guns N' Roses", 1980, 'en'], ['Paradise City', "Guns N' Roses", 1980, 'en'],
    ['November Rain', "Guns N' Roses", 1990, 'en'], ['The Final Countdown', 'Europe', 1980, 'en'],
    ['Africa', 'Toto', 1980, 'en'], ['Rosanna', 'Toto', 1980, 'en'], ['Hold the Line', 'Toto', 1970, 'en'],
    ["Don't Stop Believin'", 'Journey', 1980, 'en'], ['Any Way You Want It', 'Journey', 1980, 'en'], ['Eye of the Tiger', 'Survivor', 1980, 'en'],
    ['Total Eclipse of the Heart', 'Bonnie Tyler', 1980, 'en'], ['Holding Out for a Hero', 'Bonnie Tyler', 1980, 'en'],
    ['White Wedding', 'Billy Idol', 1980, 'en'], ['Rebel Yell', 'Billy Idol', 1980, 'en'], ['Never Gonna Give You Up', 'Rick Astley', 1980, 'en'],
    ['Kids in America', 'Kim Wilde', 1980, 'en'], ["You Keep Me Hangin' On", 'Kim Wilde', 1980, 'en'], ['True', 'Spandau Ballet', 1980, 'en'],
    ['Shout', 'Tears for Fears', 1980, 'en'], ['Everybody Wants to Rule the World', 'Tears for Fears', 1980, 'en'],
    ['In the Air Tonight', 'Phil Collins', 1980, 'en'], ['Against All Odds (Take a Look at Me Now)', 'Phil Collins', 1980, 'en'],
    ['Another Day in Paradise', 'Phil Collins', 1980, 'en'], ['Sussudio', 'Phil Collins', 1980, 'en'],
    ['Hello', 'Lionel Richie', 1980, 'en'], ['All Night Long (All Night)', 'Lionel Richie', 1980, 'en'], ['Dancing on the Ceiling', 'Lionel Richie', 1980, 'en'],
    ['I Want to Know What Love Is', 'Foreigner', 1980, 'en'], ['We Built This City', 'Starship', 1980, 'en'], ['The Power of Love', 'Huey Lewis & The News', 1980, 'en'],
    ["Summer of '69", 'Bryan Adams', 1980, 'en'], ['Heaven', 'Bryan Adams', 1980, 'en'], ['(Everything I Do) I Do It for You', 'Bryan Adams', 1990, 'en'],
    ['Born in the U.S.A.', 'Bruce Springsteen', 1980, 'en'], ['Dancing in the Dark', 'Bruce Springsteen', 1980, 'en'],
    ['With or Without You', 'U2', 1980, 'en'], ['Beautiful Day', 'U2', 2000, 'en'], ['One', 'U2', 1990, 'en'], ['Sunday Bloody Sunday', 'U2', 1980, 'en'],
    ["I Still Haven't Found What I'm Looking For", 'U2', 1980, 'en'], ['Losing My Religion', 'R.E.M.', 1990, 'en'],
    ["Don't You (Forget About Me)", 'Simple Minds', 1980, 'en'], ['West End Girls', 'Pet Shop Boys', 1980, 'en'], ["It's a Sin", 'Pet Shop Boys', 1980, 'en'],
    ['Tainted Love', 'Soft Cell', 1980, 'en'], ["Don't You Want Me", 'The Human League', 1980, 'en'], ['Relax', 'Frankie Goes to Hollywood', 1980, 'en'],
    ['Come On Eileen', 'Dexys Midnight Runners', 1980, 'en'], ['Down Under', 'Men at Work', 1980, 'en'], ['Electric Avenue', 'Eddy Grant', 1980, 'en'],
    ['Cruel Summer', 'Bananarama', 1980, 'en'], ['Venus', 'Bananarama', 1980, 'en'], ['You Spin Me Round (Like a Record)', 'Dead or Alive', 1980, 'en'],
    ['The Look', 'Roxette', 1980, 'en'], ['It Must Have Been Love', 'Roxette', 1990, 'en'], ['Listen to Your Heart', 'Roxette', 1980, 'en'],
    ['I Should Be So Lucky', 'Kylie Minogue', 1980, 'en'], ['Need You Tonight', 'INXS', 1980, 'en'], ['Maneater', 'Daryl Hall & John Oates', 1980, 'en'],
    ['You Make My Dreams', 'Daryl Hall & John Oates', 1980, 'en'], ['Drive', 'The Cars', 1980, 'en'], ['Ghostbusters', 'Ray Parker Jr.', 1980, 'en'],
    ['Footloose', 'Kenny Loggins', 1980, 'en'], ['Danger Zone', 'Kenny Loggins', 1980, 'en'], ['Take My Breath Away', 'Berlin', 1980, 'en'],
    ['Flashdance... What a Feeling', 'Irene Cara', 1980, 'en'], ['Love Is a Battlefield', 'Pat Benatar', 1980, 'en'], ["I Love Rock 'n' Roll", 'Joan Jett & The Blackhearts', 1980, 'en'],
    ['Jump', 'Van Halen', 1980, 'en'], ['Pour Some Sugar on Me', 'Def Leppard', 1980, 'en'], ['Every Rose Has Its Thorn', 'Poison', 1980, 'en'],
    ['Here I Go Again', 'Whitesnake', 1980, 'en'], ['Wind of Change', 'Scorpions', 1990, 'en'], ['Rock You Like a Hurricane', 'Scorpions', 1980, 'en'],
    ['Nothing Else Matters', 'Metallica', 1990, 'en'], ['Enter Sandman', 'Metallica', 1990, 'en'],

    // ---- 90er ----
    ['I Want It That Way', 'Backstreet Boys', 1990, 'en'], ["Everybody (Backstreet's Back)", 'Backstreet Boys', 1990, 'en'],
    ['As Long as You Love Me', 'Backstreet Boys', 1990, 'en'], ['Larger than Life', 'Backstreet Boys', 1990, 'en'],
    ['Bye Bye Bye', '*NSYNC', 2000, 'en'], ["It's Gonna Be Me", '*NSYNC', 2000, 'en'], ["Tearin' Up My Heart", '*NSYNC', 1990, 'en'],
    ['Wannabe', 'Spice Girls', 1990, 'en'], ['Spice Up Your Life', 'Spice Girls', 1990, 'en'], ['Stop', 'Spice Girls', 1990, 'en'],
    ['...Baby One More Time', 'Britney Spears', 1990, 'en'], ['Oops!... I Did It Again', 'Britney Spears', 2000, 'en'], ['Toxic', 'Britney Spears', 2000, 'en'],
    ['Womanizer', 'Britney Spears', 2000, 'en'], ['Back for Good', 'Take That', 1990, 'en'], ['Never Forget', 'Take That', 1990, 'en'], ['Patience', 'Take That', 2000, 'en'],
    ['Relight My Fire', 'Take That', 1990, 'en'], ['Wonderwall', 'Oasis', 1990, 'en'], ["Don't Look Back in Anger", 'Oasis', 1990, 'en'],
    ['Champagne Supernova', 'Oasis', 1990, 'en'], ['Live Forever', 'Oasis', 1990, 'en'], ['Song 2', 'Blur', 1990, 'en'], ['Parklife', 'Blur', 1990, 'en'],
    ['Smells Like Teen Spirit', 'Nirvana', 1990, 'en'], ['Come as You Are', 'Nirvana', 1990, 'en'], ['Under the Bridge', 'Red Hot Chili Peppers', 1990, 'en'],
    ['Californication', 'Red Hot Chili Peppers', 1990, 'en'], ['Scar Tissue', 'Red Hot Chili Peppers', 1990, 'en'], ["Can't Stop", 'Red Hot Chili Peppers', 2000, 'en'],
    ['Basket Case', 'Green Day', 1990, 'en'], ['Good Riddance (Time of Your Life)', 'Green Day', 1990, 'en'], ['No Scrubs', 'TLC', 1990, 'en'], ['Waterfalls', 'TLC', 1990, 'en'],
    ['Say My Name', "Destiny's Child", 1990, 'en'], ['Survivor', "Destiny's Child", 2000, 'en'], ['Bootylicious', "Destiny's Child", 2000, 'en'],
    ['Barbie Girl', 'Aqua', 1990, 'en'], ['Dr. Jones', 'Aqua', 1990, 'en'], ['Roses Are Red', 'Aqua', 1990, 'en'], ['Blue (Da Ba Dee)', 'Eiffel 65', 1990, 'en'],
    ['What Is Love', 'Haddaway', 1990, 'en'], ['Rhythm Is a Dancer', 'SNAP!', 1990, 'en'], ['No Limit', '2 Unlimited', 1990, 'en'], ['Get Ready for This', '2 Unlimited', 1990, 'en'],
    ['Mr. Vain', 'Culture Beat', 1990, 'en'], ["It's My Life", 'Dr. Alban', 1990, 'en'], ['Be My Lover', 'La Bouche', 1990, 'en'], ['Cotton Eye Joe', 'Rednex', 1990, 'en'],
    ['More and More', 'Captain Hollywood Project', 1990, 'en'], ['Another Night', 'Real McCoy', 1990, 'en'], ['The Sign', 'Ace of Base', 1990, 'en'],
    ['All That She Wants', 'Ace of Base', 1990, 'en'], ['Lemon Tree', "Fool's Garden", 1990, 'en'], ['We Like to Party!', 'Vengaboys', 1990, 'en'],
    ['Boom, Boom, Boom, Boom!!', 'Vengaboys', 1990, 'en'], ["We're Going to Ibiza!", 'Vengaboys', 1990, 'en'], ['Mambo No. 5 (A Little Bit of...)', 'Lou Bega', 1990, 'en'],
    ['Believe', 'Cher', 1990, 'en'], ['Angels', 'Robbie Williams', 1990, 'en'], ['Rock DJ', 'Robbie Williams', 2000, 'en'], ['Let Me Entertain You', 'Robbie Williams', 1990, 'en'],
    ['Feel', 'Robbie Williams', 2000, 'en'], ['My Heart Will Go On', 'Céline Dion', 1990, 'en'], ['Hero', 'Mariah Carey', 1990, 'en'], ['Fantasy', 'Mariah Carey', 1990, 'en'],
    ['All I Want for Christmas Is You', 'Mariah Carey', 1990, 'en'], ['We Belong Together', 'Mariah Carey', 2000, 'en'],
    ['Man! I Feel Like a Woman!', 'Shania Twain', 1990, 'en'], ["That Don't Impress Me Much", 'Shania Twain', 1990, 'en'],
    ['Livin\' la Vida Loca', 'Ricky Martin', 1990, 'en'], ['Bailamos', 'Enrique Iglesias', 1990, 'en'], ['Fly Away', 'Lenny Kravitz', 1990, 'en'],
    ['Are You Gonna Go My Way', 'Lenny Kravitz', 1990, 'en'], ['Ironic', 'Alanis Morissette', 1990, 'en'], ['You Oughta Know', 'Alanis Morissette', 1990, 'en'],
    ['Zombie', 'The Cranberries', 1990, 'en'], ['Linger', 'The Cranberries', 1990, 'en'], ['Buddy Holly', 'Weezer', 1990, 'en'], ['All Star', 'Smash Mouth', 1990, 'en'],
    ['Tubthumping', 'Chumbawamba', 1990, 'en'], ['Steal My Sunshine', 'Len', 1990, 'en'], ['Torn', 'Natalie Imbruglia', 1990, 'en'],
    ['All I Wanna Do', 'Sheryl Crow', 1990, 'en'], ['Mr. Jones', 'Counting Crows', 1990, 'en'], ['Kiss from a Rose', 'Seal', 1990, 'en'], ['Tears in Heaven', 'Eric Clapton', 1990, 'en'],
    ["Gangsta's Paradise", 'Coolio', 1990, 'en'], ['California Love', '2Pac', 1990, 'en'], ["Gettin' Jiggy wit It", 'Will Smith', 1990, 'en'], ['Men in Black', 'Will Smith', 1990, 'en'],
    ['Killing Me Softly with His Song', 'Fugees', 1990, 'en'], ['Ready or Not', 'Fugees', 1990, 'en'], ['This Is How We Do It', 'Montell Jordan', 1990, 'en'],
    ['Push It', 'Salt-N-Pepa', 1980, 'en'], ['Ice Ice Baby', 'Vanilla Ice', 1990, 'en'], ["U Can't Touch This", 'MC Hammer', 1990, 'en'], ['Pump Up the Jam', 'Technotronic', 1990, 'en'],
    ["I'm Too Sexy", 'Right Said Fred', 1990, 'en'], ['Baby Got Back', 'Sir Mix-A-Lot', 1990, 'en'], ['Macarena (Bayside Boys Mix)', 'Los del Río', 1990, 'en'],
    ['Saturday Night', 'Whigfield', 1990, 'en'], ['Firestarter', 'The Prodigy', 1990, 'en'], ['Praise You', 'Fatboy Slim', 1990, 'en'], ['Insomnia', 'Faithless', 1990, 'en'],
    ['Born Slippy', 'Underworld', 1990, 'en'], ['Sandstorm', 'Darude', 1990, 'en'], ['Freed from Desire', 'Gala', 1990, 'en'], ['Ecuador', 'Sash!', 1990, 'en'],
    ['Coco Jamboo', 'Mr. President', 1990, 'en'], ['Better Off Alone', 'Alice Deejay', 1990, 'en'], ["9 PM (Till I Come)", 'ATB', 1990, 'en'], ['Lady (Hear Me Tonight)', 'Modjo', 2000, 'en'],
    ['Music Sounds Better with You', 'Stardust', 1990, 'en'], ['One More Time', 'Daft Punk', 2000, 'en'], ['Lovefool', 'The Cardigans', 1990, 'en'],
    ['Fields of Gold', 'Sting', 1990, 'en'], ["I'd Do Anything for Love (But I Won't Do That)", 'Meat Loaf', 1990, 'en'],
    ["I Don't Want to Miss a Thing", 'Aerosmith', 1990, 'en'], ['Dream On', 'Aerosmith', 1970, 'en'], ['Crazy', 'Aerosmith', 1990, 'en'],
    ['Alive', 'Pearl Jam', 1990, 'en'], ['Black Hole Sun', 'Soundgarden', 1990, 'en'], ['Creep', 'Radiohead', 1990, 'en'], ['Teardrop', 'Massive Attack', 1990, 'en'],
    ['Stupid Girl', 'Garbage', 1990, 'en'], ['Save Tonight', 'Eagle-Eye Cherry', 1990, 'en'], ['Truly Madly Deeply', 'Savage Garden', 1990, 'en'],
    ["What's Up?", '4 Non Blondes', 1990, 'en'], ['One of Us', 'Joan Osborne', 1990, 'en'], ['Un-Break My Heart', 'Toni Braxton', 1990, 'en'],
    ['No Matter What', 'Boyzone', 1990, 'en'], ['Flying Without Wings', 'Westlife', 1990, 'en'], ['Stay Another Day', 'East 17', 1990, 'en'],
    ['Love Is All Around', 'Wet Wet Wet', 1990, 'en'], ['Dreams', 'Gabrielle', 1990, 'en'],

    // ---- 2000er ----
    ['Lose Yourself', 'Eminem', 2000, 'en'], ['Stan', 'Eminem', 2000, 'en'], ['The Real Slim Shady', 'Eminem', 2000, 'en'], ['Without Me', 'Eminem', 2000, 'en'],
    ['Crazy in Love', 'Beyoncé', 2000, 'en'], ['Single Ladies (Put a Ring on It)', 'Beyoncé', 2000, 'en'], ['Halo', 'Beyoncé', 2000, 'en'], ['Irreplaceable', 'Beyoncé', 2000, 'en'],
    ['Umbrella', 'Rihanna', 2000, 'en'], ['Diamonds', 'Rihanna', 2010, 'en'], ['We Found Love', 'Rihanna', 2010, 'en'], ["Don't Stop the Music", 'Rihanna', 2000, 'en'],
    ['Only Girl (In the World)', 'Rihanna', 2010, 'en'], ['Rude Boy', 'Rihanna', 2010, 'en'], ['Work', 'Rihanna', 2010, 'en'],
    ["Hips Don't Lie", 'Shakira', 2000, 'en'], ['Whenever, Wherever', 'Shakira', 2000, 'en'], ['Waka Waka (This Time for Africa)', 'Shakira', 2010, 'en'],
    ['I Gotta Feeling', 'The Black Eyed Peas', 2000, 'en'], ['Where Is the Love?', 'The Black Eyed Peas', 2000, 'en'], ['Boom Boom Pow', 'The Black Eyed Peas', 2000, 'en'],
    ["Let's Get It Started", 'The Black Eyed Peas', 2000, 'en'], ['My Humps', 'The Black Eyed Peas', 2000, 'en'], ['Hey Ya!', 'OutKast', 2000, 'en'], ['Ms. Jackson', 'OutKast', 2000, 'en'],
    ['Yeah!', 'Usher', 2000, 'en'], ['Burn', 'Usher', 2000, 'en'], ['Cry Me a River', 'Justin Timberlake', 2000, 'en'], ['SexyBack', 'Justin Timberlake', 2000, 'en'],
    ['Rock Your Body', 'Justin Timberlake', 2000, 'en'], ["Can't Stop the Feeling!", 'Justin Timberlake', 2010, 'en'], ['Mirrors', 'Justin Timberlake', 2010, 'en'],
    ['Since U Been Gone', 'Kelly Clarkson', 2000, 'en'], ['Stronger (What Doesn\'t Kill You)', 'Kelly Clarkson', 2010, 'en'], ['Because of You', 'Kelly Clarkson', 2000, 'en'],
    ['In the End', 'Linkin Park', 2000, 'en'], ['Numb', 'Linkin Park', 2000, 'en'], ['Crawling', 'Linkin Park', 2000, 'en'], ["What I've Done", 'Linkin Park', 2000, 'en'],
    ['Viva la Vida', 'Coldplay', 2000, 'en'], ['Clocks', 'Coldplay', 2000, 'en'], ['Yellow', 'Coldplay', 2000, 'en'], ['Fix You', 'Coldplay', 2000, 'en'],
    ['The Scientist', 'Coldplay', 2000, 'en'], ['Paradise', 'Coldplay', 2010, 'en'], ['A Sky Full of Stars', 'Coldplay', 2010, 'en'],
    ['Mr. Brightside', 'The Killers', 2000, 'en'], ['Somebody Told Me', 'The Killers', 2000, 'en'], ['When You Were Young', 'The Killers', 2000, 'en'], ['Human', 'The Killers', 2000, 'en'],
    ['Sex on Fire', 'Kings of Leon', 2000, 'en'], ['Use Somebody', 'Kings of Leon', 2000, 'en'], ['Do I Wanna Know?', 'Arctic Monkeys', 2010, 'en'],
    ['I Bet You Look Good on the Dancefloor', 'Arctic Monkeys', 2000, 'en'], ['Rehab', 'Amy Winehouse', 2000, 'en'], ['Back to Black', 'Amy Winehouse', 2000, 'en'],
    ['Valerie', 'Mark Ronson', 2000, 'en'], ['Crazy', 'Gnarls Barkley', 2000, 'en'], ['Get Busy', 'Sean Paul', 2000, 'en'], ['Temperature', 'Sean Paul', 2000, 'en'],
    ['Hot in Herre', 'Nelly', 2000, 'en'], ['Dilemma', 'Nelly', 2000, 'en'], ['In da Club', '50 Cent', 2000, 'en'], ['Candy Shop', '50 Cent', 2000, 'en'],
    ["Drop It Like It's Hot", 'Snoop Dogg', 2000, 'en'], ['Genie in a Bottle', 'Christina Aguilera', 1990, 'en'], ['Dirrty', 'Christina Aguilera', 2000, 'en'],
    ['Beautiful', 'Christina Aguilera', 2000, 'en'], ['Get the Party Started', 'P!nk', 2000, 'en'], ['Just Like a Pill', 'P!nk', 2000, 'en'], ['So What', 'P!nk', 2000, 'en'],
    ['Raise Your Glass', 'P!nk', 2010, 'en'], ['Just Give Me a Reason', 'P!nk', 2010, 'en'], ['Complicated', 'Avril Lavigne', 2000, 'en'], ['Sk8er Boi', 'Avril Lavigne', 2000, 'en'],
    ['Girlfriend', 'Avril Lavigne', 2000, 'en'], ['Bring Me to Life', 'Evanescence', 2000, 'en'], ["Can't Get You Out of My Head", 'Kylie Minogue', 2000, 'en'],
    ['Spinning Around', 'Kylie Minogue', 2000, 'en'], ['Just Dance', 'Lady Gaga', 2000, 'en'], ['Poker Face', 'Lady Gaga', 2000, 'en'], ['Bad Romance', 'Lady Gaga', 2000, 'en'],
    ['Paparazzi', 'Lady Gaga', 2000, 'en'], ['Born This Way', 'Lady Gaga', 2010, 'en'], ['Shallow', 'Lady Gaga', 2010, 'en'],
    ['I Kissed a Girl', 'Katy Perry', 2000, 'en'], ['Firework', 'Katy Perry', 2010, 'en'], ['California Gurls', 'Katy Perry', 2010, 'en'], ['Roar', 'Katy Perry', 2010, 'en'],
    ['Teenage Dream', 'Katy Perry', 2010, 'en'], ['Dark Horse', 'Katy Perry', 2010, 'en'], ['Dynamite', 'Taio Cruz', 2010, 'en'], ['Low', 'Flo Rida', 2000, 'en'],
    ['Right Round', 'Flo Rida', 2000, 'en'], ['Good Feeling', 'Flo Rida', 2010, 'en'], ['Titanium', 'David Guetta', 2010, 'en'], ['When Love Takes Over', 'David Guetta', 2000, 'en'],
    ['Give Me Everything', 'Pitbull', 2010, 'en'], ['Timber', 'Pitbull', 2010, 'en'], ['Whatcha Say', 'Jason Derulo', 2000, 'en'], ['Talk Dirty', 'Jason Derulo', 2010, 'en'],
    ['TiK ToK', 'Kesha', 2000, 'en'],

    // ---- 2010er und 2020er ----
    ['Just the Way You Are', 'Bruno Mars', 2010, 'en'], ['Grenade', 'Bruno Mars', 2010, 'en'], ['Locked Out of Heaven', 'Bruno Mars', 2010, 'en'],
    ['Uptown Funk', 'Mark Ronson', 2010, 'en'], ['24K Magic', 'Bruno Mars', 2010, 'en'], ["That's What I Like", 'Bruno Mars', 2010, 'en'], ['When I Was Your Man', 'Bruno Mars', 2010, 'en'],
    ['This Love', 'Maroon 5', 2000, 'en'], ['Moves like Jagger', 'Maroon 5', 2010, 'en'], ['Sugar', 'Maroon 5', 2010, 'en'], ['Payphone', 'Maroon 5', 2010, 'en'],
    ['Girls Like You', 'Maroon 5', 2010, 'en'], ['Memories', 'Maroon 5', 2010, 'en'], ['Counting Stars', 'OneRepublic', 2010, 'en'], ['Apologize', 'OneRepublic', 2000, 'en'],
    ['Hey, Soul Sister', 'Train', 2000, 'en'], ['Somebody That I Used to Know', 'Gotye', 2010, 'en'], ['We Are Young', 'fun.', 2010, 'en'], ['Royals', 'Lorde', 2010, 'en'],
    ['Radioactive', 'Imagine Dragons', 2010, 'en'], ['Demons', 'Imagine Dragons', 2010, 'en'], ['Thunder', 'Imagine Dragons', 2010, 'en'], ['Believer', 'Imagine Dragons', 2010, 'en'],
    ["It's Time", 'Imagine Dragons', 2010, 'en'], ['Lonely Boy', 'The Black Keys', 2010, 'en'], ['Kids', 'MGMT', 2000, 'en'], ['Electric Feel', 'MGMT', 2000, 'en'],
    ['Get Lucky', 'Daft Punk', 2010, 'en'], ['Harder, Better, Faster, Stronger', 'Daft Punk', 2000, 'en'], ['Happy', 'Pharrell Williams', 2010, 'en'],
    ['Wake Me Up', 'Avicii', 2010, 'en'], ['Levels', 'Avicii', 2010, 'en'], ['Hey Brother', 'Avicii', 2010, 'en'], ['This Is What You Came For', 'Calvin Harris', 2010, 'en'],
    ['Summer', 'Calvin Harris', 2010, 'en'], ['Feel So Close', 'Calvin Harris', 2010, 'en'], ["Don't You Worry Child", 'Swedish House Mafia', 2010, 'en'], ['Clarity', 'Zedd', 2010, 'en'],
    ['Animals', 'Martin Garrix', 2010, 'en'], ['Firestone', 'Kygo', 2010, 'en'], ['Rather Be', 'Clean Bandit', 2010, 'en'], ['Rockabye', 'Clean Bandit', 2010, 'en'],
    ['Feel the Love', 'Rudimental', 2010, 'en'], ['Latch', 'Disclosure', 2010, 'en'], ['Stay with Me', 'Sam Smith', 2010, 'en'], ['Take Me to Church', 'Hozier', 2010, 'en'],
    ['Shape of You', 'Ed Sheeran', 2010, 'en'], ['Thinking Out Loud', 'Ed Sheeran', 2010, 'en'], ['Perfect', 'Ed Sheeran', 2010, 'en'], ['The A Team', 'Ed Sheeran', 2010, 'en'],
    ['Sing', 'Ed Sheeran', 2010, 'en'], ['Castle on the Hill', 'Ed Sheeran', 2010, 'en'], ['Bad Habits', 'Ed Sheeran', 2020, 'en'],
    ['Rolling in the Deep', 'Adele', 2010, 'en'], ['Someone like You', 'Adele', 2010, 'en'], ['Hello', 'Adele', 2010, 'en'], ['Set Fire to the Rain', 'Adele', 2010, 'en'],
    ['Skyfall', 'Adele', 2010, 'en'], ['Shake It Off', 'Taylor Swift', 2010, 'en'], ['Blank Space', 'Taylor Swift', 2010, 'en'], ['Love Story', 'Taylor Swift', 2000, 'en'],
    ['Bad Blood', 'Taylor Swift', 2010, 'en'], ['You Belong with Me', 'Taylor Swift', 2000, 'en'], ['Anti-Hero', 'Taylor Swift', 2020, 'en'], ['Cruel Summer', 'Taylor Swift', 2010, 'en'],
    ['Baby', 'Justin Bieber', 2010, 'en'], ['Sorry', 'Justin Bieber', 2010, 'en'], ['Love Yourself', 'Justin Bieber', 2010, 'en'], ['Peaches', 'Justin Bieber', 2020, 'en'],
    ['Problem', 'Ariana Grande', 2010, 'en'], ['7 rings', 'Ariana Grande', 2010, 'en'], ['thank u, next', 'Ariana Grande', 2010, 'en'], ['Into You', 'Ariana Grande', 2010, 'en'],
    ['Stitches', 'Shawn Mendes', 2010, 'en'], ['Treat You Better', 'Shawn Mendes', 2010, 'en'], ['Come & Get It', 'Selena Gomez', 2010, 'en'], ['Lose You to Love Me', 'Selena Gomez', 2010, 'en'],
    ['Attention', 'Charlie Puth', 2010, 'en'], ['See You Again', 'Wiz Khalifa', 2010, 'en'], ['Chandelier', 'Sia', 2010, 'en'], ['Cheap Thrills', 'Sia', 2010, 'en'],
    ['All About That Bass', 'Meghan Trainor', 2010, 'en'], ['Stressed Out', 'twenty one pilots', 2010, 'en'], ['New Rules', 'Dua Lipa', 2010, 'en'], ["Don't Start Now", 'Dua Lipa', 2010, 'en'],
    ['Levitating', 'Dua Lipa', 2020, 'en'], ['bad guy', 'Billie Eilish', 2010, 'en'], ['Ocean Eyes', 'Billie Eilish', 2010, 'en'], ['Happier Than Ever', 'Billie Eilish', 2020, 'en'],
    ['Blinding Lights', 'The Weeknd', 2010, 'en'], ["Can't Feel My Face", 'The Weeknd', 2010, 'en'], ['Starboy', 'The Weeknd', 2010, 'en'], ['Save Your Tears', 'The Weeknd', 2020, 'en'],
    ['Watermelon Sugar', 'Harry Styles', 2010, 'en'], ['As It Was', 'Harry Styles', 2020, 'en'], ['Adore You', 'Harry Styles', 2010, 'en'], ['Sign of the Times', 'Harry Styles', 2010, 'en'],
    ['Circles', 'Post Malone', 2010, 'en'], ['Sunflower', 'Post Malone', 2010, 'en'], ['rockstar', 'Post Malone', 2010, 'en'], ['Good as Hell', 'Lizzo', 2010, 'en'], ['About Damn Time', 'Lizzo', 2020, 'en'],
    ['Truth Hurts', 'Lizzo', 2010, 'en'], ['Someone You Loved', 'Lewis Capaldi', 2010, 'en'], ['Before You Go', 'Lewis Capaldi', 2010, 'en'], ['drivers license', 'Olivia Rodrigo', 2020, 'en'],
    ['good 4 u', 'Olivia Rodrigo', 2020, 'en'], ['vampire', 'Olivia Rodrigo', 2020, 'en'], ['Wrecking Ball', 'Miley Cyrus', 2010, 'en'], ['Flowers', 'Miley Cyrus', 2020, 'en'],
    ['Party in the U.S.A.', 'Miley Cyrus', 2000, 'en'], ["We Can't Stop", 'Miley Cyrus', 2010, 'en'], ['Say So', 'Doja Cat', 2010, 'en'], ['Kiss Me More', 'Doja Cat', 2020, 'en'],
    ['Dance Monkey', 'Tones and I', 2010, 'en'], ['Beggin\'', 'Måneskin', 2010, 'en'], ['Zitti e buoni', 'Måneskin', 2020, 'en'], ['Heat Waves', 'Glass Animals', 2020, 'en'],
    ['Let Her Go', 'Passenger', 2010, 'en'], ['Havana', 'Camila Cabello', 2010, 'en'], ['Señorita', 'Shawn Mendes', 2010, 'en'], ['Despacito', 'Luis Fonsi', 2010, 'en'],
    ['Gasolina', 'Daddy Yankee', 2000, 'en'], ['Jenny from the Block', 'Jennifer Lopez', 2000, 'en'], ['On the Floor', 'Jennifer Lopez', 2010, 'en'], ["Let's Get Loud", 'Jennifer Lopez', 1990, 'en'],
    ['Gangnam Style', 'PSY', 2010, 'en'], ["Can't Hold Us", 'Macklemore & Ryan Lewis', 2010, 'en'], ['Thrift Shop', 'Macklemore & Ryan Lewis', 2010, 'en'],
    ['Call Me Maybe', 'Carly Rae Jepsen', 2010, 'en'], ['Blurred Lines', 'Robin Thicke', 2010, 'en'], ['I Like It', 'Cardi B', 2010, 'en'], ['Old Town Road', 'Lil Nas X', 2010, 'en'],
    ['Hotline Bling', 'Drake', 2010, 'en'], ['One Dance', 'Drake', 2010, 'en'], ["God's Plan", 'Drake', 2010, 'en'], ['Lights', 'Ellie Goulding', 2010, 'en'], ['Burn', 'Ellie Goulding', 2010, 'en'],
    ['Love Me like You Do', 'Ellie Goulding', 2010, 'en'], ['Summertime Sadness', 'Lana Del Rey', 2010, 'en'], ['Video Games', 'Lana Del Rey', 2010, 'en'],
    ['Dog Days Are Over', 'Florence + The Machine', 2000, 'en'], ['I Will Wait', 'Mumford & Sons', 2010, 'en'], ['Little Lion Man', 'Mumford & Sons', 2000, 'en'],
    ['Little Talks', 'Of Monsters and Men', 2010, 'en'], ['Ho Hey', 'The Lumineers', 2010, 'en'], ['Pompeii', 'Bastille', 2010, 'en'], ['Pumped Up Kicks', 'Foster the People', 2010, 'en'],
    ['I Took a Pill in Ibiza', 'Mike Posner', 2010, 'en'], ['7 Years', 'Lukas Graham', 2010, 'en'], ['Easy Love', 'Sigala', 2010, 'en'], ['Fast Car', 'Jonas Blue', 2010, 'en'],
    ['Sugar', 'Robin Schulz', 2010, 'en'], ['Prayer in C', 'Lilly Wood & The Prick', 2010, 'en'], ["Ain't Nobody (Loves Me Better)", 'Felix Jaehn', 2010, 'en'],
    ['Are You with Me', 'Lost Frequencies', 2010, 'en'], ['Faded', 'Alan Walker', 2010, 'en'], ['This Girl', 'Kungs', 2010, 'en'], ['Lean On', 'Major Lazer', 2010, 'en'],
    ['Turn Down for What', 'DJ Snake', 2010, 'en'], ['Let Me Love You', 'DJ Snake', 2010, 'en'], ["You Don't Know Me", 'Jax Jones', 2010, 'en'], ['Head & Heart', 'Joel Corry', 2020, 'en'],
    ['Easy on Me', 'Adele', 2020, 'en'], ['Unholy', 'Sam Smith', 2020, 'en'], ['Flowers', 'Miley Cyrus', 2020, 'en'], ['Cold Heart', 'Elton John', 2020, 'en'],

    // ---- Deutsch: Klassiker und Neue Deutsche Welle ----
    ['99 Luftballons', 'Nena', 1980, 'de'], ['Nur geträumt', 'Nena', 1980, 'de'], ['Irgendwie, irgendwo, irgendwann', 'Nena', 1980, 'de'],
    ['Rock Me Amadeus', 'Falco', 1980, 'de'], ['Der Kommissar', 'Falco', 1980, 'de'], ['Jeanny', 'Falco', 1980, 'de'], ['Vienna Calling', 'Falco', 1980, 'de'],
    ['Über sieben Brücken musst du gehn', 'Peter Maffay', 1980, 'de'], ['Männer', 'Herbert Grönemeyer', 1980, 'de'], ['Bochum', 'Herbert Grönemeyer', 1980, 'de'],
    ['Mensch', 'Herbert Grönemeyer', 2000, 'de'], ['Flugzeuge im Bauch', 'Herbert Grönemeyer', 1980, 'de'], ['Du hast den Farbfilm vergessen', 'Nina Hagen', 1970, 'de'],
    ['Da Da Da', 'Trio', 1980, 'de'], ['Major Tom (Völlig losgelöst)', 'Peter Schilling', 1980, 'de'], ['Blaue Augen', 'Ideal', 1980, 'de'],
    ['Hurra, hurra, die Schule brennt', 'Extrabreit', 1980, 'de'], ['Skandal im Sperrbezirk', 'Spider Murphy Gang', 1980, 'de'], ["Ohne dich (schlaf' ich heut' Nacht nicht ein)", 'Münchener Freiheit', 1980, 'de'],
    ["You're My Heart, You're My Soul", 'Modern Talking', 1980, 'en'], ['Brother Louie', 'Modern Talking', 1980, 'en'], ['Cheri, Cheri Lady', 'Modern Talking', 1980, 'en'],
    ['Maria Magdalena', 'Sandra', 1980, 'en'], ['Big in Japan', 'Alphaville', 1980, 'en'], ['Forever Young', 'Alphaville', 1980, 'en'], ['Das Model', 'Kraftwerk', 1970, 'de'],
    ['Cello', 'Udo Lindenberg', 1980, 'de'], ['Sonderzug nach Pankow', 'Udo Lindenberg', 1980, 'de'], ['Aber bitte mit Sahne', 'Udo Jürgens', 1970, 'de'],
    ['Merci, Chérie', 'Udo Jürgens', 1960, 'de'], ['Ein Bett im Kornfeld', 'Jürgen Drews', 1970, 'de'], ['Verlieben, verloren, vergessen, verzeih\'n', 'Wolfgang Petry', 1990, 'de'],
    ['Wahnsinn', 'Wolfgang Petry', 1990, 'de'], ['Santa Maria', 'Roland Kaiser', 1980, 'de'], ['Ein Stern (...der deinen Namen trägt)', 'DJ Ötzi & Nik P.', 2000, 'de'],
    ['Hey Baby', 'DJ Ötzi', 2000, 'de'], ["L'amour toujours", 'Gigi D\'Agostino', 2000, 'en'], ['Das geht ab (Wir feiern die ganze Nacht)', 'Die Atzen', 2010, 'de'],
    ['How Much Is the Fish?', 'Scooter', 1990, 'en'], ['Hyper Hyper', 'Scooter', 1990, 'en'], ['Maria (I Like It Loud)', 'Scooter', 2000, 'en'], ['Fire', 'Scooter', 1990, 'en'],

    // ---- Deutsch: 90er, 2000er, aktuell ----
    ['Die da!?!', 'Die Fantastischen Vier', 1990, 'de'], ['Populär', 'Die Fantastischen Vier', 1990, 'de'], ['Troy', 'Die Fantastischen Vier', 1990, 'de'],
    ['MfG', 'Die Fantastischen Vier', 1990, 'de'], ['Hier kommt Alex', 'Die Toten Hosen', 1980, 'de'], ['Tage wie diese', 'Die Toten Hosen', 2010, 'de'],
    ['Bonnie & Clyde', 'Die Toten Hosen', 1990, 'de'], ['Alles aus Liebe', 'Die Toten Hosen', 1990, 'de'], ['Schrei nach Liebe', 'Die Ärzte', 1990, 'de'],
    ['Männer sind Schweine', 'Die Ärzte', 1990, 'de'], ['Junge', 'Die Ärzte', 2000, 'de'], ['Zu spät', 'Die Ärzte', 1990, 'de'], ['Westerland', 'Die Ärzte', 1990, 'de'],
    ['Küssen verboten', 'Die Prinzen', 1990, 'de'], ['Alles nur geklaut', 'Die Prinzen', 1990, 'de'], ['Millionär', 'Die Prinzen', 1990, 'de'], ['Verdammt lang her', 'BAP', 1980, 'de'],
    ['Du hast', 'Rammstein', 1990, 'de'], ['Sonne', 'Rammstein', 2000, 'de'], ['Engel', 'Rammstein', 1990, 'de'], ['Ich will', 'Rammstein', 2000, 'de'], ['Mein Herz brennt', 'Rammstein', 2000, 'de'],
    ['Amerika', 'Rammstein', 2000, 'de'], ['Liebe ist alles', 'Rosenstolz', 2000, 'de'], ['Abenteuerland', 'PUR', 1990, 'de'], ['Jein', 'Fettes Brot', 1990, 'de'],
    ['Denkmal', 'Wir sind Helden', 2000, 'de'], ['Müssen nur wollen', 'Wir sind Helden', 2000, 'de'], ['Gekommen um zu bleiben', 'Wir sind Helden', 2000, 'de'],
    ['54, 74, 90, 2010', 'Sportfreunde Stiller', 2000, 'de'], ['Ein Kompliment', 'Sportfreunde Stiller', 2000, 'de'], ['Perfekte Welle', 'Juli', 2000, 'de'],
    ['Das Beste', 'Silbermond', 2000, 'de'], ['Symphonie', 'Silbermond', 2000, 'de'], ['Verschwende deine Zeit', 'Silbermond', 2000, 'de'], ['Durch den Monsun', 'Tokio Hotel', 2000, 'de'],
    ['Übers Ende der Welt', 'Tokio Hotel', 2000, 'de'], ['Dickes B', 'Seeed', 2000, 'de'], ['Ding', 'Seeed', 2000, 'de'], ['Aufstehn', 'Seeed', 2000, 'de'],
    ['Alles neu', 'Peter Fox', 2000, 'de'], ['Haus am See', 'Peter Fox', 2000, 'de'], ['Hamma!', 'Culcha Candela', 2000, 'de'], ['Hungriges Herz', 'MIA.', 2000, 'de'],
    ['Halt dich an mir fest', 'Revolverheld', 2000, 'de'], ['Wie soll ein Mensch das ertragen', 'Philipp Poisel', 2010, 'de'], ['Gewinner', 'Clueso', 2000, 'de'],
    ['Easy', 'Cro', 2010, 'de'], ['Traum', 'Cro', 2010, 'de'], ['Hinterland', 'Casper', 2010, 'de'], ['Lila Wolken', 'Marteria', 2010, 'de'],
    ['Ich will nicht nach Berlin', 'Kraftklub', 2010, 'de'], ['Schönste Zeit', 'Bosse', 2010, 'de'], ['Pocahontas', 'AnnenMayKantereit', 2010, 'de'],
    ['Auf uns', 'Andreas Bourani', 2010, 'de'], ['Atemlos durch die Nacht', 'Helene Fischer', 2010, 'de'], ['Phänomen', 'Helene Fischer', 2010, 'de'],
    ['Du lässt mich sterben', 'Helene Fischer', 2010, 'de'], ['Au revoir', 'Mark Forster', 2010, 'de'], ['Chöre', 'Mark Forster', 2010, 'de'], ['Flash mich', 'Mark Forster', 2010, 'de'],
    ['Vincent', 'Sarah Connor', 2000, 'de'], ['Wie schön du bist', 'Sarah Connor', 2010, 'de'], ['Satellite', 'Lena', 2010, 'de'], ['80 Millionen', 'Max Giesinger', 2010, 'de'],
    ['Nur noch kurz die Welt retten', 'Tim Bendzko', 2010, 'de'], ['Lieblingsmensch', 'Namika', 2010, 'de'], ['Sofia', 'Álvaro Soler', 2010, 'en'], ['El Mismo Sol', 'Álvaro Soler', 2010, 'en'],
    ['Leiser', 'LEA', 2010, 'de'], ['Zieh die Schuh aus', 'Roger Cicero', 2000, 'de'], ['Dieser Weg', 'Xavier Naidoo', 2000, 'de'], ['Was wir alleine nicht schaffen', 'Xavier Naidoo', 2000, 'de'],
    ['Roller', 'Apache 207', 2020, 'de'], ['Prinzessin', 'Capital Bra', 2010, 'de'], ['Astronaut', 'Sido', 2010, 'de'],
];

// Doppelte Einträge (gleicher Titel und Künstler) fallen heraus.
export const CATALOG = [...new Map(L.map(([title, artist, decade, lang]) => [`${title} | ${artist}`, { id: `${title} | ${artist}`, title, artist, decade, lang }])).values()];
