// Fragen für das Stufenquiz: 6 Kategorien mit je 10 Schwierigkeitsstufen (1 = ganz leicht, 10 = richtig schwer).
// Jede Frage: [Frage, richtige Antwort, falsch, falsch, falsch]. Die Antworten werden beim Spielen gemischt.
export const CATEGORIES = [
    {
        name: 'Erde & Länder',
        icon: '🌍',
        levels: [
            [
                ['Wie heißt die Hauptstadt von Deutschland?', 'Berlin', 'München', 'Hamburg', 'Köln'],
                ['Auf welchem Kontinent liegt Ägypten?', 'Afrika', 'Asien', 'Europa', 'Südamerika'],
                ['Wie heißt das große Meer zwischen Europa und Amerika?', 'Atlantik', 'Pazifik', 'Indischer Ozean', 'Nordsee'],
                ['In welchem Land steht der Eiffelturm?', 'Frankreich', 'Italien', 'Spanien', 'England'],
                ['Wie heißt der höchste Berg Deutschlands?', 'Zugspitze', 'Brocken', 'Feldberg', 'Watzmann'],
            ],
            [
                ['Wie heißt die Hauptstadt von Italien?', 'Rom', 'Mailand', 'Neapel', 'Venedig'],
                ['Welcher Fluss fließt durch Köln?', 'Rhein', 'Elbe', 'Donau', 'Weser'],
                ['Welches Land hat die Form eines Stiefels?', 'Italien', 'Spanien', 'Griechenland', 'Portugal'],
                ['Welcher ist der größte Ozean der Erde?', 'Pazifik', 'Atlantik', 'Indischer Ozean', 'Arktischer Ozean'],
                ['In welchem Land liegt die Stadt Wien?', 'Österreich', 'Schweiz', 'Ungarn', 'Tschechien'],
            ],
            [
                ['Wie heißt die Hauptstadt von Spanien?', 'Madrid', 'Barcelona', 'Sevilla', 'Valencia'],
                ['Welcher Kontinent ist der kleinste?', 'Australien / Ozeanien', 'Europa', 'Antarktis', 'Südamerika'],
                ['Wie heißt die Hauptstadt der Türkei?', 'Ankara', 'Istanbul', 'Izmir', 'Antalya'],
                ['Durch welche Stadt fließt die Themse?', 'London', 'Paris', 'Dublin', 'Manchester'],
                ['Welches Land ist flächenmäßig das größte der Erde?', 'Russland', 'Kanada', 'China', 'USA'],
            ],
            [
                ['Wie heißt die Hauptstadt von Kanada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
                ['Wie heißt die Hauptstadt von Australien?', 'Canberra', 'Sydney', 'Melbourne', 'Perth'],
                ['Welches Meer liegt zwischen Italien und Kroatien?', 'Adriatisches Meer', 'Ägäis', 'Schwarzes Meer', 'Ostsee'],
                ['In welchem Land liegt die Stadt Marrakesch?', 'Marokko', 'Tunesien', 'Ägypten', 'Algerien'],
                ['Welcher Fluss ist der längste Europas?', 'Wolga', 'Donau', 'Rhein', 'Elbe'],
                ['Wie heißt die Hauptstadt von Serbien?', 'Belgrad', 'Novi Sad', 'Niš', 'Podgorica'],
            ],
            [
                ['Wie heißt die Hauptstadt von Brasilien?', 'Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'],
                ['Welches ist das bevölkerungsreichste Land Afrikas?', 'Nigeria', 'Ägypten', 'Äthiopien', 'Südafrika'],
                ['In welchem Land liegt der Kilimandscharo?', 'Tansania', 'Kenia', 'Uganda', 'Südafrika'],
                ['Welche große Stadt liegt auf zwei Kontinenten?', 'Istanbul', 'Kairo', 'Moskau', 'Athen'],
                ['Wie heißt die Meerenge zwischen Spanien und Marokko?', 'Straße von Gibraltar', 'Bosporus', 'Dardanellen', 'Straße von Messina'],
            ],
            [
                ['Wie heißt die Hauptstadt von Neuseeland?', 'Wellington', 'Auckland', 'Christchurch', 'Hamilton'],
                ['Welches Land hat die Hauptstadt Ulaanbaatar?', 'Mongolei', 'Kasachstan', 'Nepal', 'Kirgisistan'],
                ['Welcher See ist der tiefste der Erde?', 'Baikalsee', 'Tanganjikasee', 'Oberer See', 'Titicacasee'],
                ['Welches dieser Länder hat keinen Zugang zum Meer?', 'Bolivien', 'Peru', 'Chile', 'Ecuador'],
                ['Wie heißt die Hauptstadt von Peru?', 'Lima', 'Quito', 'Bogotá', 'Santiago'],
            ],
            [
                ['Wie heißt die Hauptstadt von Kasachstan?', 'Astana', 'Almaty', 'Taschkent', 'Bischkek'],
                ['Welche ist die größte Insel der Welt (ohne Kontinente)?', 'Grönland', 'Neuguinea', 'Borneo', 'Madagaskar'],
                ['An welchem Meer liegt die Stadt Odessa?', 'Schwarzes Meer', 'Kaspisches Meer', 'Asowsches Meer', 'Ägäis'],
                ['Welches Land hat die Hauptstadt Addis Abeba?', 'Äthiopien', 'Eritrea', 'Somalia', 'Kenia'],
                ['Welche ist die größte heiße Wüste der Erde?', 'Sahara', 'Gobi', 'Kalahari', 'Arabische Wüste'],
            ],
            [
                ['Wie heißt die Hauptstadt von Myanmar?', 'Naypyidaw', 'Rangun', 'Mandalay', 'Bangkok'],
                ['Welcher große Fluss mündet ins Kaspische Meer?', 'Wolga', 'Don', 'Dnepr', 'Donau'],
                ['Welches Land ist vollständig von Südafrika umschlossen?', 'Lesotho', 'Eswatini', 'Botswana', 'Namibia'],
                ['Wie heißt die Hauptstadt der Elfenbeinküste (Regierungssitz)?', 'Yamoussoukro', 'Abidjan', 'Accra', 'Dakar'],
                ['Welches Gebirge gilt traditionell als Grenze zwischen Europa und Asien?', 'Ural', 'Karpaten', 'Alpen', 'Pyrenäen'],
            ],
            [
                ['Wie heißt die Hauptstadt von Kamerun?', 'Jaunde', 'Duala', 'Garoua', 'Bamenda'],
                ['Wie heißt der höchste Berg Südamerikas?', 'Aconcagua', 'Chimborazo', 'Huascarán', 'Ojos del Salado'],
                ['In welchem Land liegt die Stadt Timbuktu?', 'Mali', 'Niger', 'Mauretanien', 'Tschad'],
                ['Welches dieser Länder grenzt ans Kaspische Meer?', 'Turkmenistan', 'Armenien', 'Georgien', 'Usbekistan'],
                ['Wie heißt die Hauptstadt von Usbekistan?', 'Taschkent', 'Samarkand', 'Buchara', 'Duschanbe'],
            ],
            [
                ['Wie heißt die Hauptstadt von Burkina Faso?', 'Ouagadougou', 'Bamako', 'Niamey', 'Accra'],
                ['Welcher See liegt am tiefsten unter dem Meeresspiegel?', 'Totes Meer', 'Assalsee', 'Kaspisches Meer', 'Baikalsee'],
                ['Wie heißt die Hauptstadt von Kirgisistan?', 'Bischkek', 'Duschanbe', 'Aschgabat', 'Taschkent'],
                ['An welchem Fluss liegt Bagdad?', 'Tigris', 'Euphrat', 'Jordan', 'Nil'],
                ['In welchem Land liegt der riesige Salzsee Salar de Uyuni?', 'Bolivien', 'Peru', 'Chile', 'Argentinien'],
            ],
        ],
    },
    {
        name: 'Geschichte',
        icon: '🏛️',
        levels: [
            [
                ['Wer war der erste Mensch auf dem Mond?', 'Neil Armstrong', 'Juri Gagarin', 'Elon Musk', 'John Glenn'],
                ['In welchem Land stehen die berühmten Pyramiden von Gizeh?', 'Ägypten', 'Griechenland', 'Mexiko', 'Italien'],
                ['Womit fuhren die Wikinger über das Meer?', 'Langschiffen', 'Dampfschiffen', 'Flößen', 'Kreuzfahrtschiffen'],
                ['In welcher Stadt stand die Berliner Mauer?', 'Berlin', 'Hamburg', 'Wien', 'Leipzig'],
                ['Wer entdeckte 1492 Amerika für Europa?', 'Christoph Kolumbus', 'Marco Polo', 'Vasco da Gama', 'James Cook'],
            ],
            [
                ['In welchem Jahr fiel die Berliner Mauer?', '1989', '1961', '1975', '1991'],
                ['Wie hieß der Pharao, dessen Grab mit der goldenen Maske 1922 entdeckt wurde?', 'Tutanchamun', 'Ramses', 'Cheops', 'Echnaton'],
                ['Welche Sprache sprachen die alten Römer?', 'Latein', 'Griechisch', 'Italienisch', 'Französisch'],
                ['Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?', 'Konrad Adenauer', 'Willy Brandt', 'Helmut Kohl', 'Ludwig Erhard'],
                ['Welches Schiff sank 1912 auf seiner Jungfernfahrt?', 'Titanic', 'Bismarck', 'Gorch Fock', 'Santa Maria'],
            ],
            [
                ['Welcher französische Kaiser wurde 1815 bei Waterloo besiegt?', 'Napoleon Bonaparte', 'Ludwig XIV.', 'Karl der Große', 'Robespierre'],
                ['Wie nennt man die Epoche zwischen Antike und Neuzeit?', 'Mittelalter', 'Renaissance', 'Steinzeit', 'Aufklärung'],
                ['Welche Stadt wurde im Jahr 79 n. Chr. von einem Vulkanausbruch begraben?', 'Pompeji', 'Rom', 'Athen', 'Karthago'],
                ['Wer malte die Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Raffael', 'Rembrandt'],
                ['Wer war der erste Präsident der USA?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'Benjamin Franklin'],
            ],
            [
                ['In welchem Jahr begann der Zweite Weltkrieg?', '1939', '1914', '1933', '1945'],
                ['Wer veröffentlichte der Überlieferung nach 1517 die 95 Thesen?', 'Martin Luther', 'Johannes Calvin', 'Thomas Müntzer', 'Ulrich Zwingli'],
                ['Wie hieß die Mondlandefähre von Apollo 11?', 'Eagle', 'Columbia', 'Challenger', 'Discovery'],
                ['Welches Ereignis begann 1789 in Frankreich?', 'Die Französische Revolution', 'Der Dreißigjährige Krieg', 'Die Reformation', 'Der Wiener Kongress'],
                ['Wer war die erste Bundeskanzlerin Deutschlands?', 'Angela Merkel', 'Ursula von der Leyen', 'Annegret Kramp-Karrenbauer', 'Claudia Roth'],
            ],
            [
                ['In welchem Jahr wurde Deutschland wiedervereinigt?', '1990', '1989', '1991', '1987'],
                ['Welcher Krieg dauerte von 1618 bis 1648?', 'Der Dreißigjährige Krieg', 'Der Siebenjährige Krieg', 'Der Hundertjährige Krieg', 'Der Erste Weltkrieg'],
                ['Wer war der letzte Kaiser des Deutschen Reiches?', 'Wilhelm II.', 'Wilhelm I.', 'Friedrich III.', 'Franz Joseph'],
                ['Welche Stadt war die Hauptstadt des Byzantinischen Reiches?', 'Konstantinopel', 'Rom', 'Athen', 'Alexandria'],
                ['Welches Ereignis löste 1914 den Ersten Weltkrieg aus?', 'Das Attentat von Sarajevo', 'Der Börsencrash', 'Die Oktoberrevolution', 'Die Schlacht von Verdun'],
            ],
            [
                ['Wer war der erste Kaiser des Römischen Reiches?', 'Augustus', 'Julius Caesar', 'Nero', 'Konstantin'],
                ['Wie heißt der Vertrag von 1919, der den Ersten Weltkrieg für Deutschland beendete?', 'Versailler Vertrag', 'Westfälischer Friede', 'Potsdamer Abkommen', 'Wiener Kongress'],
                ['Wer war ab 1940 britischer Premierminister im Zweiten Weltkrieg?', 'Winston Churchill', 'Neville Chamberlain', 'Clement Attlee', 'Margaret Thatcher'],
                ['Wie wurde der französische König Ludwig XIV. genannt?', 'Sonnenkönig', 'Löwenherz', 'der Weise', 'der Große Kaiser'],
                ['Wer war Anführer der Hunnen im 5. Jahrhundert?', 'Attila', 'Dschingis Khan', 'Hannibal', 'Arminius'],
            ],
            [
                ['In welchem Jahr wurde die Volksrepublik China ausgerufen?', '1949', '1945', '1953', '1961'],
                ['Welche Schlacht von 1066 führte zur normannischen Eroberung Englands?', 'Schlacht bei Hastings', 'Schlacht bei Agincourt', 'Schlacht von Waterloo', 'Schlacht bei Crécy'],
                ['Wer war der erste Kaiser des vereinten China (221 v. Chr.)?', 'Qin Shihuangdi', 'Kublai Khan', 'Konfuzius', 'Sun Yat-sen'],
                ['Welcher Vertrag beendete 1648 den Dreißigjährigen Krieg?', 'Westfälischer Friede', 'Augsburger Religionsfriede', 'Wiener Kongress', 'Friede von Utrecht'],
                ['Wer wurde 1871 der erste Kanzler des Deutschen Kaiserreichs?', 'Otto von Bismarck', 'Bernhard von Bülow', 'Leo von Caprivi', 'Chlodwig zu Hohenlohe'],
            ],
            [
                ['In welchem Jahr wurde die Magna Carta unterzeichnet?', '1215', '1066', '1348', '1492'],
                ['In welchem Jahr eroberten die Osmanen Konstantinopel?', '1453', '1492', '1204', '1526'],
                ['Wer wurde 1959 Ministerpräsident von Kuba nach dem Sturz Batistas?', 'Fidel Castro', 'Che Guevara', 'Hugo Chávez', 'Salvador Allende'],
                ['Welcher Pharao ließ die Große Pyramide von Gizeh bauen?', 'Cheops', 'Ramses II.', 'Tutanchamun', 'Echnaton'],
                ['Welche Organisation wurde 1957 durch die Römischen Verträge gegründet?', 'Die Europäische Wirtschaftsgemeinschaft', 'Die NATO', 'Die OECD', 'Der Europarat'],
            ],
            [
                ['Wer wurde im Jahr 800 in Rom zum Kaiser gekrönt?', 'Karl der Große', 'Otto der Große', 'Friedrich Barbarossa', 'Ludwig der Fromme'],
                ['Welche Schlacht gewann Napoleon 1805 gegen Russland und Österreich?', 'Austerlitz', 'Waterloo', 'Leipzig', 'Borodino'],
                ['Wie hieß der Enkel Dschingis Khans, der China eroberte und die Yuan-Dynastie gründete?', 'Kublai Khan', 'Timur', 'Attila', 'Batu Khan'],
                ['Wer war der erste Reichspräsident der Weimarer Republik?', 'Friedrich Ebert', 'Paul von Hindenburg', 'Gustav Stresemann', 'Philipp Scheidemann'],
                ['Wie hieß die Hauptstadt des Aztekenreiches?', 'Tenochtitlan', 'Cusco', 'Machu Picchu', 'Chichén Itzá'],
            ],
            [
                ['Wie hieß der letzte Zar Russlands?', 'Nikolaus II.', 'Alexander III.', 'Peter III.', 'Iwan IV.'],
                ['In welchem Jahr fand die Seeschlacht von Salamis statt?', '480 v. Chr.', '490 v. Chr.', '431 v. Chr.', '330 v. Chr.'],
                ['Welcher römische Kaiser erhob 380 das Christentum zur Staatsreligion?', 'Theodosius I.', 'Konstantin I.', 'Diokletian', 'Julian'],
                ['Welche Dynastie regierte Russland von 1613 bis 1917?', 'Romanow', 'Rurikiden', 'Habsburger', 'Hohenzollern'],
                ['Wer gewann 1066 die Schlacht bei Hastings?', 'Wilhelm der Eroberer', 'Harald Hardrada', 'Harold Godwinson', 'Knut der Große'],
            ],
        ],
    },
    {
        name: 'Natur & Tiere',
        icon: '🦁',
        levels: [
            [
                ['Welches Tier sagt „Miau“?', 'Katze', 'Hund', 'Kuh', 'Pferd'],
                ['Welches ist das größte Landtier?', 'Elefant', 'Giraffe', 'Nilpferd', 'Nashorn'],
                ['Welche Farbe haben reife Bananen?', 'Gelb', 'Blau', 'Rot', 'Lila'],
                ['Wie nennt man ein Baby der Katze?', 'Kätzchen', 'Fohlen', 'Welpe', 'Küken'],
                ['Wo wachsen Äpfel?', 'Auf Bäumen', 'Unter der Erde', 'Im Wasser', 'Auf Kakteen'],
            ],
            [
                ['Welches Tier gilt als „König der Tiere“?', 'Löwe', 'Tiger', 'Bär', 'Adler'],
                ['Wie viele Beine hat eine Spinne?', 'Acht', 'Sechs', 'Vier', 'Zehn'],
                ['Was frisst ein Pandabär hauptsächlich?', 'Bambus', 'Fisch', 'Gras', 'Beeren'],
                ['Welches Säugetier kann fliegen?', 'Fledermaus', 'Eichhörnchen', 'Pinguin', 'Strauß'],
                ['Aus welchem Tier wird ein Schmetterling?', 'Raupe', 'Libelle', 'Biene', 'Marienkäfer'],
            ],
            [
                ['Wie nennt man Tiere, die nur Pflanzen fressen?', 'Pflanzenfresser', 'Fleischfresser', 'Allesfresser', 'Aasfresser'],
                ['Welcher dieser Vögel kann nicht fliegen?', 'Pinguin', 'Möwe', 'Amsel', 'Storch'],
                ['Welches ist das größte Tier der Welt?', 'Blauwal', 'Elefant', 'Walhai', 'Giraffe'],
                ['Welches Gas nehmen Pflanzen aus der Luft auf?', 'Kohlendioxid', 'Sauerstoff', 'Stickstoff', 'Helium'],
                ['Wie nennt man das Junge eines Pferdes?', 'Fohlen', 'Kalb', 'Lamm', 'Ferkel'],
            ],
            [
                ['Welcher Baum trägt Eicheln?', 'Eiche', 'Buche', 'Tanne', 'Birke'],
                ['Wie nennt man Tiere, die im Wasser und an Land leben?', 'Amphibien', 'Reptilien', 'Säugetiere', 'Insekten'],
                ['Welches ist das schnellste Landtier?', 'Gepard', 'Löwe', 'Antilope', 'Pferd'],
                ['Welches dieser Tiere ist ein Beuteltier?', 'Känguru', 'Lama', 'Alpaka', 'Tapir'],
                ['Was ist die Hauptnahrung von Koalas?', 'Eukalyptusblätter', 'Bambus', 'Palmblätter', 'Gras'],
            ],
            [
                ['Wie viele Herzen hat ein Oktopus?', 'Drei', 'Eins', 'Zwei', 'Acht'],
                ['Welcher Vogel kann rückwärts fliegen?', 'Kolibri', 'Adler', 'Spatz', 'Papagei'],
                ['Welches Landtier hat die längste Tragzeit?', 'Elefant', 'Giraffe', 'Nashorn', 'Nilpferd'],
                ['Wie viele Beine hat jedes Insekt?', 'Sechs', 'Acht', 'Vier', 'Zehn'],
                ['Welcher ist der größte lebende Vogel der Welt?', 'Strauß', 'Kondor', 'Albatros', 'Emu'],
            ],
            [
                ['Wie nennt man den Vorgang, bei dem Pflanzen aus Licht Energie gewinnen?', 'Photosynthese', 'Osmose', 'Fermentation', 'Verdunstung'],
                ['Welcher Zugvogel legt jedes Jahr die längste Strecke zurück?', 'Küstenseeschwalbe', 'Storch', 'Kranich', 'Rauchschwalbe'],
                ['Welches Säugetier legt Eier?', 'Schnabeltier', 'Känguru', 'Koala', 'Gürteltier'],
                ['Welcher Baum ist auf der Flagge Kanadas abgebildet?', 'Ahorn', 'Eiche', 'Fichte', 'Zeder'],
                ['Welches Tier wirft jedes Jahr sein Geweih ab?', 'Hirsch', 'Nashorn', 'Steinbock', 'Antilope'],
            ],
            [
                ['Welcher ist der größte Fisch der Welt?', 'Walhai', 'Blauhai', 'Riesenmanta', 'Weißer Hai'],
                ['Wie nennt man ein junges Robbenbaby auf Deutsch?', 'Heuler', 'Kalb', 'Welpe', 'Küken'],
                ['Was ist ein Axolotl?', 'Ein Schwanzlurch', 'Eine Eidechse', 'Ein Fisch', 'Ein Krebs'],
                ['Welcher Baum erreicht die größte Höhe aller Bäume?', 'Küstenmammutbaum', 'Eukalyptus', 'Eiche', 'Douglasie'],
                ['Welcher große Laufvogel ist neben dem Känguru Wappentier Australiens?', 'Emu', 'Strauß', 'Kiwi', 'Nandu'],
            ],
            [
                ['Wie heißt das männliche Tier in einem Bienenvolk?', 'Drohne', 'Arbeiterin', 'Königin', 'Wächter'],
                ['Zu welcher Tiergruppe gehört der Orang-Utan?', 'Menschenaffen', 'Makaken', 'Gibbons', 'Lemuren'],
                ['Zu welcher Pflanzenfamilie gehören Tomate und Kartoffel?', 'Nachtschattengewächse', 'Kreuzblütler', 'Rosengewächse', 'Hülsenfrüchtler'],
                ['Wie lautet der wissenschaftliche Name der Ordnung der Käfer?', 'Coleoptera', 'Hymenoptera', 'Lepidoptera', 'Diptera'],
                ['Welcher Vogel legt seine Eier in fremde Nester?', 'Kuckuck', 'Spatz', 'Taube', 'Schwalbe'],
            ],
            [
                ['Wie lange dauert die Tragzeit eines Elefanten ungefähr?', '22 Monate', '9 Monate', '12 Monate', '15 Monate'],
                ['Welches ist das größte lebende Reptil der Welt?', 'Salzwasserkrokodil', 'Komodowaran', 'Nilkrokodil', 'Grüne Anakonda'],
                ['Welches Tier kann abwechselnd nur eine Gehirnhälfte schlafen lassen?', 'Delfin', 'Elefant', 'Pferd', 'Wolf'],
                ['Welcher Baum erreicht ein Alter von weit über 4000 Jahren?', 'Grannen-Kiefer', 'Eiche', 'Mammutbaum', 'Linde'],
                ['Welche Meeresschildkröte ist die größte?', 'Lederschildkröte', 'Suppenschildkröte', 'Karettschildkröte', 'Bastardschildkröte'],
            ],
            [
                ['Welcher Vogel hat die größte Flügelspannweite?', 'Wanderalbatros', 'Andenkondor', 'Pelikan', 'Seeadler'],
                ['Wie viele Beine hat ein Zehnfußkrebs?', 'Zehn', 'Acht', 'Zwölf', 'Sechs'],
                ['Welche Pflanze hat die größte Einzelblüte der Welt?', 'Rafflesia', 'Lotus', 'Seerose', 'Orchidee'],
                ['Wie nennt man das Zusammenleben zweier Arten zum gegenseitigen Nutzen?', 'Symbiose', 'Parasitismus', 'Konkurrenz', 'Mutation'],
                ['Wie nennt man Pflanzen, die auf anderen Pflanzen wachsen, ohne sie anzuzapfen?', 'Epiphyten', 'Parasiten', 'Sukkulenten', 'Halophyten'],
            ],
        ],
    },
    {
        name: 'Wissenschaft & Technik',
        icon: '🔬',
        levels: [
            [
                ['Was leuchtet am Tag am Himmel?', 'Die Sonne', 'Der Mond', 'Die Sterne', 'Die Wolken'],
                ['Welcher dieser Stoffe ist bei Zimmertemperatur flüssig?', 'Wasser', 'Eisen', 'Holz', 'Stein'],
                ['Womit kann man telefonieren?', 'Handy', 'Toaster', 'Kühlschrank', 'Föhn'],
                ['Wie nennt man gefrorenes Wasser?', 'Eis', 'Dampf', 'Wolke', 'Tau'],
                ['Wie heißt der Planet, auf dem wir leben?', 'Erde', 'Mars', 'Venus', 'Jupiter'],
            ],
            [
                ['Wie viele Planeten hat unser Sonnensystem?', 'Acht', 'Sieben', 'Neun', 'Zehn'],
                ['Bei wie viel Grad Celsius gefriert Wasser?', '0 Grad', '10 Grad', '−10 Grad', '32 Grad'],
                ['Welches Gas brauchen wir zum Atmen?', 'Sauerstoff', 'Stickstoff', 'Wasserstoff', 'Helium'],
                ['Was misst ein Thermometer?', 'Temperatur', 'Gewicht', 'Länge', 'Zeit'],
                ['Welcher Planet wird „Roter Planet“ genannt?', 'Mars', 'Venus', 'Jupiter', 'Saturn'],
            ],
            [
                ['Wofür steht die Abkürzung WWW?', 'World Wide Web', 'World Web Wide', 'Wide Web World', 'Western World Web'],
                ['Wie lautet die chemische Formel von Wasser?', 'H₂O', 'CO₂', 'O₂', 'NaCl'],
                ['Welcher Planet ist für seine auffälligen Ringe bekannt?', 'Saturn', 'Mars', 'Merkur', 'Venus'],
                ['Wie nennt man die Kraft, die uns auf den Boden zieht?', 'Schwerkraft', 'Reibung', 'Magnetismus', 'Trägheit'],
                ['Wie lautet π auf zwei Nachkommastellen gerundet?', '3,14', '3,41', '3,12', '3,24'],
            ],
            [
                ['In welcher Einheit misst man elektrische Spannung?', 'Volt', 'Watt', 'Ampere', 'Ohm'],
                ['Welches ist das leichteste chemische Element?', 'Wasserstoff', 'Helium', 'Sauerstoff', 'Lithium'],
                ['Wie viele Knochen hat ein erwachsener Mensch?', '206', '150', '250', '300'],
                ['Welches Metall ist bei Raumtemperatur flüssig?', 'Quecksilber', 'Blei', 'Zinn', 'Aluminium'],
                ['Welches Organ filtert das Blut und bildet den Urin?', 'Niere', 'Leber', 'Milz', 'Magen'],
            ],
            [
                ['Wie heißt der kleinste Baustein eines chemischen Elements?', 'Atom', 'Molekül', 'Zelle', 'Ion'],
                ['Wie schnell ist das Licht im Vakuum ungefähr?', '300.000 km/s', '30.000 km/s', '3.000 km/s', '3 Millionen km/s'],
                ['Welcher Planet ist der größte unseres Sonnensystems?', 'Jupiter', 'Saturn', 'Neptun', 'Uranus'],
                ['Wie heißt der rote Blutfarbstoff?', 'Hämoglobin', 'Insulin', 'Melanin', 'Chlorophyll'],
                ['Wer entdeckte das Penicillin?', 'Alexander Fleming', 'Louis Pasteur', 'Robert Koch', 'Marie Curie'],
            ],
            [
                ['Wer entwickelte die Relativitätstheorie?', 'Albert Einstein', 'Isaac Newton', 'Niels Bohr', 'Max Planck'],
                ['Wie lautet das chemische Symbol für Gold?', 'Au', 'Ag', 'Go', 'Gd'],
                ['Welches Gas macht den größten Teil der Erdatmosphäre aus?', 'Stickstoff', 'Sauerstoff', 'Kohlendioxid', 'Argon'],
                ['Was ist die Hauptaufgabe der roten Blutkörperchen?', 'Sauerstofftransport', 'Immunabwehr', 'Blutgerinnung', 'Verdauung'],
                ['Wie viele Chromosomen hat ein Mensch normalerweise?', '46', '23', '44', '48'],
            ],
            [
                ['Wie heißt das negativ geladene Teilchen im Atom?', 'Elektron', 'Proton', 'Neutron', 'Quark'],
                ['Welches Element hat die Ordnungszahl 6?', 'Kohlenstoff', 'Sauerstoff', 'Stickstoff', 'Bor'],
                ['Welcher Planet dreht sich entgegen der Richtung der meisten anderen?', 'Venus', 'Mars', 'Jupiter', 'Merkur'],
                ['Welcher Stern ist der Sonne am nächsten (nach der Sonne selbst)?', 'Proxima Centauri', 'Sirius', 'Polarstern', 'Wega'],
                ['Wofür steht die Abkürzung DNS?', 'Desoxyribonukleinsäure', 'Dinatriumsäure', 'Dynamische Nukleinsequenz', 'Diatomare Nukleinsäure'],
            ],
            [
                ['Wie lautet das chemische Symbol für Kalium?', 'K', 'Ka', 'Kl', 'P'],
                ['Welches Gesetz besagt „Kraft = Masse × Beschleunigung“?', 'Zweites Newtonsches Gesetz', 'Erstes Newtonsches Gesetz', 'Drittes Newtonsches Gesetz', 'Ohmsches Gesetz'],
                ['In welcher Schicht der Atmosphäre findet das Wetter statt?', 'Troposphäre', 'Stratosphäre', 'Mesosphäre', 'Thermosphäre'],
                ['Wer baute den ersten funktionsfähigen programmierbaren Computer „Z3“?', 'Konrad Zuse', 'Alan Turing', 'Charles Babbage', 'John von Neumann'],
                ['Welches Element hat das chemische Symbol W?', 'Wolfram', 'Zink', 'Zinn', 'Wismut'],
            ],
            [
                ['Wie viele Elemente hat das Periodensystem heute?', '118', '92', '100', '126'],
                ['In welcher Einheit wird die Aktivität radioaktiver Stoffe gemessen?', 'Becquerel', 'Sievert', 'Gray', 'Joule'],
                ['Wer entdeckte 1895 die nach ihm benannten Strahlen?', 'Wilhelm Conrad Röntgen', 'Max von Laue', 'Heinrich Hertz', 'Otto Hahn'],
                ['Welches Edelgas kommt in der Luft am häufigsten vor?', 'Argon', 'Neon', 'Helium', 'Krypton'],
                ['Wie heißt der Saturnmond mit einer dichten Atmosphäre?', 'Titan', 'Europa', 'Io', 'Triton'],
            ],
            [
                ['Wie heißt das hypothetische Austauschteilchen der Gravitation?', 'Graviton', 'Gluon', 'Photon', 'Neutrino'],
                ['Welcher Mathematiker wurde „Fürst der Mathematiker“ genannt?', 'Carl Friedrich Gauß', 'Leonhard Euler', 'Gottfried Leibniz', 'Bernhard Riemann'],
                ['Wie hoch ist der Siedepunkt von Wasser bei Normaldruck in Kelvin?', 'etwa 373 K', 'etwa 273 K', 'etwa 100 K', 'etwa 473 K'],
                ['Welche Raumsonde verließ 2012 als erste menschengemachte Sonde den Heliosphärenraum?', 'Voyager 1', 'Pioneer 10', 'Voyager 2', 'New Horizons'],
                ['Wie heißt das Protein, das Sauerstoff im Muskel speichert?', 'Myoglobin', 'Hämoglobin', 'Keratin', 'Kollagen'],
            ],
        ],
    },
    {
        name: 'Film, TV & Musik',
        icon: '🎬',
        levels: [
            [
                ['Wie heißt die Eiskönigin im Disney-Film „Die Eiskönigin“?', 'Elsa', 'Anna', 'Ariel', 'Belle'],
                ['Was für ein Tier ist Simba im Film „Der König der Löwen“?', 'Ein Löwe', 'Ein Tiger', 'Ein Bär', 'Ein Leopard'],
                ['Wie heißt der kleine Müll-Roboter aus dem gleichnamigen Pixar-Film?', 'WALL·E', 'R2-D2', 'Bumblebee', 'C-3PO'],
                ['Welches Instrument hat schwarze und weiße Tasten?', 'Klavier', 'Gitarre', 'Geige', 'Flöte'],
                ['Wie heißt der Zauberlehrling mit der Blitznarbe?', 'Harry Potter', 'Percy Jackson', 'Frodo', 'Luke Skywalker'],
            ],
            [
                ['Welche Band sang „Yesterday“?', 'The Beatles', 'Rolling Stones', 'Queen', 'ABBA'],
                ['Wie heißt der Fisch mit dem schlechten Gedächtnis in „Findet Nemo“?', 'Dorie', 'Marlin', 'Bruce', 'Nigel'],
                ['Wie heißt der grüne Oger aus dem gleichnamigen Animationsfilm?', 'Shrek', 'Fiona', 'Pinocchio', 'Gollum'],
                ['Wer wird „King of Pop“ genannt?', 'Michael Jackson', 'Elvis Presley', 'Prince', 'Justin Bieber'],
                ['Aus welchem Land kommt die Band ABBA?', 'Schweden', 'Norwegen', 'Dänemark', 'Finnland'],
            ],
            [
                ['Welcher Schauspieler spielt Captain Jack Sparrow?', 'Johnny Depp', 'Brad Pitt', 'Orlando Bloom', 'Tom Cruise'],
                ['In welcher Filmreihe geht es um einen Ring, der alle beherrscht?', 'Der Herr der Ringe', 'Harry Potter', 'Star Wars', 'Die Chroniken von Narnia'],
                ['Welche Sängerin ist für „Rolling in the Deep“ bekannt?', 'Adele', 'Rihanna', 'Beyoncé', 'Lady Gaga'],
                ['Wie heißt die Heimatstadt von Batman?', 'Gotham City', 'Metropolis', 'Springfield', 'Star City'],
                ['Wie viele Saiten hat eine normale Gitarre?', 'Sechs', 'Vier', 'Fünf', 'Acht'],
            ],
            [
                ['In welcher Serie spielt die Stadt Bikini Bottom eine Rolle?', 'SpongeBob Schwammkopf', 'Die Simpsons', 'Futurama', 'Familie Feuerstein'],
                ['Welcher Film gewann 1998 elf Oscars?', 'Titanic', 'Avatar', 'Gladiator', 'Braveheart'],
                ['Welche Band hat den Hit „Bohemian Rhapsody“?', 'Queen', 'Led Zeppelin', 'Pink Floyd', 'The Who'],
                ['Wie heißt der Held in „Matrix“?', 'Neo', 'Morpheus', 'Trinity', 'Cypher'],
                ['Welcher Sänger hatte den Hit „Shape of You“?', 'Ed Sheeran', 'Justin Bieber', 'Bruno Mars', 'Shawn Mendes'],
            ],
            [
                ['Wer führte Regie bei „Jurassic Park“ (1993)?', 'Steven Spielberg', 'James Cameron', 'George Lucas', 'Ridley Scott'],
                ['Wie heißt Darth Vaders Sohn?', 'Luke Skywalker', 'Han Solo', 'Obi-Wan Kenobi', 'Lando Calrissian'],
                ['Welche Sängerin ist für „Poker Face“ bekannt?', 'Lady Gaga', 'Katy Perry', 'Rihanna', 'P!nk'],
                ['Wie heißt das „Baby Yoda“ in der Serie „The Mandalorian“?', 'Grogu', 'Yoda Junior', 'Gizmo', 'Ahsoka'],
                ['Welche Band wurde mit „Smells Like Teen Spirit“ berühmt?', 'Nirvana', 'Pearl Jam', 'Soundgarden', 'Green Day'],
            ],
            [
                ['Wer spielte die Hauptrolle in „Forrest Gump“?', 'Tom Hanks', 'Tom Cruise', 'Kevin Costner', 'Bill Murray'],
                ['Wie viele Bücher umfasst die Hauptreihe von Harry Potter?', 'Sieben', 'Fünf', 'Sechs', 'Acht'],
                ['Welcher Rapper heißt mit bürgerlichem Namen Marshall Mathers?', 'Eminem', 'Dr. Dre', '50 Cent', 'Snoop Dogg'],
                ['In welcher Serie spielt die Hauptfigur Walter White?', 'Breaking Bad', 'The Wire', 'Dexter', 'Lost'],
                ['Welche Band veröffentlichte das Album „The Dark Side of the Moon“?', 'Pink Floyd', 'Led Zeppelin', 'Genesis', 'Yes'],
            ],
            [
                ['Wer komponierte die „Mondscheinsonate“?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Frédéric Chopin'],
                ['Welcher Regisseur drehte „Pulp Fiction“?', 'Quentin Tarantino', 'Martin Scorsese', 'David Fincher', 'Guy Ritchie'],
                ['Auf welchem Album von Michael Jackson ist „Billie Jean“?', 'Thriller', 'Bad', 'Dangerous', 'Off the Wall'],
                ['In welcher Stadt spielt die Serie „Friends“?', 'New York', 'Los Angeles', 'Chicago', 'Boston'],
                ['Wer komponierte „Die vier Jahreszeiten“?', 'Antonio Vivaldi', 'Johann Sebastian Bach', 'Georg Friedrich Händel', 'Joseph Haydn'],
            ],
            [
                ['Welcher Film gewann 2020 als erster nicht-englischsprachiger Film den Oscar als bester Film?', 'Parasite', 'Roma', 'Joker', '1917'],
                ['Wer sang „Purple Rain“?', 'Prince', 'David Bowie', 'Lenny Kravitz', 'Stevie Wonder'],
                ['Wer führte Regie bei „Der Pate“?', 'Francis Ford Coppola', 'Martin Scorsese', 'Brian De Palma', 'Sidney Lumet'],
                ['In welchem Jahr erschien der erste „Star Wars“-Film?', '1977', '1973', '1980', '1983'],
                ['Wie heißt der Sänger der Band U2?', 'Bono', 'The Edge', 'Sting', 'Chris Martin'],
            ],
            [
                ['In welchem Film von Stanley Kubrick spielt das Overlook Hotel eine Rolle?', 'Shining', 'Uhrwerk Orange', '2001: Odyssee im Weltraum', 'Full Metal Jacket'],
                ['Von wem stammt die Oper „Carmen“?', 'Georges Bizet', 'Giacomo Puccini', 'Giuseppe Verdi', 'Richard Wagner'],
                ['Wer war der Schlagzeuger der Beatles?', 'Ringo Starr', 'Charlie Watts', 'Keith Moon', 'Phil Collins'],
                ['Wer spielte den Joker in „The Dark Knight“ (2008)?', 'Heath Ledger', 'Joaquin Phoenix', 'Jared Leto', 'Jack Nicholson'],
                ['Welcher deutsche Regisseur drehte den Stummfilm „Metropolis“ (1927)?', 'Fritz Lang', 'F. W. Murnau', 'Wim Wenders', 'Werner Herzog'],
            ],
            [
                ['Welche dieser Opern stammt nicht von Richard Wagner?', 'Aida', 'Parsifal', 'Lohengrin', 'Tristan und Isolde'],
                ['Welcher Film gewann den ersten Oscar als bester Film?', 'Wings (Flügel)', 'Metropolis', 'Sunrise', 'Der Jazzsänger'],
                ['Wer komponierte die „Goldberg-Variationen“?', 'Johann Sebastian Bach', 'Georg Friedrich Händel', 'Georg Philipp Telemann', 'Domenico Scarlatti'],
                ['Wer führte Regie bei „Citizen Kane“?', 'Orson Welles', 'Alfred Hitchcock', 'John Ford', 'Billy Wilder'],
                ['Welches Orchester spielt traditionell das Neujahrskonzert in Wien?', 'Wiener Philharmoniker', 'Wiener Symphoniker', 'Berliner Philharmoniker', 'Staatskapelle Dresden'],
            ],
        ],
    },
    {
        name: 'Essen, Sport & Alltag',
        icon: '🍕',
        levels: [
            [
                ['Woraus wird Brot hauptsächlich gebacken?', 'Mehl', 'Zucker', 'Salz', 'Milch'],
                ['Welche Farbe hat eine reife Zitrone?', 'Gelb', 'Blau', 'Lila', 'Rot'],
                ['Wie viele Spieler hat eine Fußballmannschaft auf dem Feld?', 'Elf', 'Neun', 'Zehn', 'Zwölf'],
                ['Welches Gemüse bringt einen beim Schneiden oft zum Weinen?', 'Zwiebel', 'Karotte', 'Gurke', 'Kartoffel'],
                ['Womit misst man die Zeit?', 'Mit einer Uhr', 'Mit einer Waage', 'Mit einem Lineal', 'Mit einem Thermometer'],
            ],
            [
                ['Aus welchem Land stammt die Pizza?', 'Italien', 'Spanien', 'Frankreich', 'Griechenland'],
                ['Wie viele Ringe hat das olympische Symbol?', 'Fünf', 'Vier', 'Sechs', 'Sieben'],
                ['Aus welcher Frucht wird Wein hergestellt?', 'Trauben', 'Äpfel', 'Kirschen', 'Pflaumen'],
                ['Welche Sportart spielt man mit Schlägern und einem gelben Filzball?', 'Tennis', 'Golf', 'Badminton', 'Hockey'],
                ['Welche Sportart spielt man mit einem Ball und einem Korb?', 'Basketball', 'Volleyball', 'Handball', 'Wasserball'],
            ],
            [
                ['In welcher Sportart gibt es den „Slam Dunk“?', 'Basketball', 'Volleyball', 'Tennis', 'Handball'],
                ['Aus welchen Zutaten wird Bier hauptsächlich gebraut?', 'Hopfen und Malz', 'Trauben und Zucker', 'Mais und Milch', 'Äpfel und Hefe'],
                ['Wie viele Spieler hat ein Volleyballteam auf dem Feld?', 'Sechs', 'Fünf', 'Sieben', 'Acht'],
                ['Welches Land gewann die Fußball-WM 2014?', 'Deutschland', 'Brasilien', 'Argentinien', 'Spanien'],
                ['Wie heißt das japanische Gericht aus Reis und rohem Fisch?', 'Sushi', 'Ramen', 'Tempura', 'Tofu'],
            ],
            [
                ['Welche Frucht ist die Hauptzutat von Guacamole?', 'Avocado', 'Gurke', 'Banane', 'Mango'],
                ['In welcher Sportart gibt es einen „Hattrick“?', 'Fußball', 'Tennis', 'Golf', 'Rudern'],
                ['Wie lang ist ein Marathonlauf?', '42,195 km', '21,0975 km', '50 km', '36,5 km'],
                ['Welches Gewürz gehört zu den teuersten der Welt?', 'Safran', 'Zimt', 'Pfeffer', 'Paprika'],
                ['Wie viele Spieler stehen beim Basketball pro Team auf dem Feld?', 'Fünf', 'Vier', 'Sechs', 'Sieben'],
            ],
            [
                ['Aus welchem Land stammt der Sport Judo?', 'Japan', 'China', 'Korea', 'Thailand'],
                ['Wie heißt Kaffee mit Espresso und aufgeschäumter Milch zu etwa gleichen Teilen?', 'Cappuccino', 'Latte Macchiato', 'Americano', 'Ristretto'],
                ['Wie viele Punkte ist ein Touchdown im American Football wert?', 'Sechs', 'Drei', 'Vier', 'Sieben'],
                ['In welcher Sportart wird der Ryder Cup ausgetragen?', 'Golf', 'Tennis', 'Rudern', 'Segeln'],
                ['Aus welcher Pflanze wird Tofu hergestellt?', 'Sojabohne', 'Erbse', 'Linse', 'Kichererbse'],
            ],
            [
                ['In welcher Stadt fanden die ersten modernen Olympischen Spiele 1896 statt?', 'Athen', 'Paris', 'London', 'Rom'],
                ['Welcher Käse gehört klassischerweise auf eine Pizza Margherita?', 'Mozzarella', 'Gouda', 'Cheddar', 'Parmesan'],
                ['Wie viele Grand-Slam-Turniere gibt es im Tennis pro Jahr?', 'Vier', 'Drei', 'Fünf', 'Sechs'],
                ['Welcher Fußballer wurde „Der Kaiser“ genannt?', 'Franz Beckenbauer', 'Gerd Müller', 'Lothar Matthäus', 'Uwe Seeler'],
                ['Aus welcher Frucht wird traditionell Calvados gebrannt?', 'Äpfeln', 'Birnen', 'Kirschen', 'Trauben'],
            ],
            [
                ['In welcher Sportart gibt es die Wertung „Birdie“?', 'Golf', 'Tennis', 'Badminton', 'Baseball'],
                ['Wie heißt das berühmte spanische Reisgericht?', 'Paella', 'Tapas', 'Gazpacho', 'Tortilla'],
                ['Wer gewann die Fußball-WM 2010?', 'Spanien', 'Niederlande', 'Deutschland', 'Uruguay'],
                ['Wie viele Runden hat ein Profi-Boxkampf um den Weltmeistertitel höchstens?', 'Zwölf', 'Zehn', 'Fünfzehn', 'Acht'],
                ['Aus welchem Land stammt der Käse Feta?', 'Griechenland', 'Türkei', 'Bulgarien', 'Italien'],
            ],
            [
                ['Wie viele Punkte bringt ein Triple-20 beim Darts?', '60', '50', '40', '180'],
                ['In welchem Land wurde das Kartenspiel Skat erfunden?', 'Deutschland', 'Österreich', 'Schweiz', 'Frankreich'],
                ['Wie viele Spieler pro Team stehen beim Rugby Union auf dem Feld?', '15', '11', '13', '17'],
                ['Zu welcher Pflanzenfamilie gehört die Vanille?', 'Orchideen', 'Palmen', 'Farne', 'Kakteen'],
                ['Wo fanden die Olympischen Sommerspiele 2016 statt?', 'Rio de Janeiro', 'London', 'Tokio', 'Peking'],
            ],
            [
                ['Aus welchem Land stammt die Sportart Curling?', 'Schottland', 'Kanada', 'Norwegen', 'Schweden'],
                ['Welche Kaffeesorte wird weltweit am meisten angebaut?', 'Arabica', 'Robusta', 'Liberica', 'Excelsa'],
                ['Aus welcher Region Italiens stammt der Parmesan?', 'Emilia-Romagna', 'Toskana', 'Sizilien', 'Venetien'],
                ['Wie viele Sätze muss ein Herren-Einzelspieler bei Grand-Slam-Turnieren gewinnen?', 'Drei', 'Zwei', 'Vier', 'Fünf'],
                ['Wie nennt man im Golf drei Schläge unter Par bei einem Loch?', 'Albatros', 'Eagle', 'Birdie', 'Bogey'],
            ],
            [
                ['Wer gewann 2022 den Ballon d’Or?', 'Karim Benzema', 'Lionel Messi', 'Robert Lewandowski', 'Kylian Mbappé'],
                ['In welchem Jahr fanden die ersten Olympischen Winterspiele statt?', '1924', '1896', '1936', '1948'],
                ['Wie hoch ist die Summe aller Zahlen von 0 bis 36 beim Roulette?', '666', '555', '777', '636'],
                ['Wie viele Kilokalorien hat ein Gramm Fett ungefähr?', '9 kcal', '4 kcal', '7 kcal', '12 kcal'],
                ['In welcher Höhe hängt ein Basketballkorb über dem Boden?', '3,05 m', '3,00 m', '3,10 m', '2,95 m'],
            ],
        ],
    },
];

export const MAX_LEVEL = 10;
